# Generated by Django 6.0.1 on 2026-03-14 01:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name=r'Attachment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'original_filename', models.CharField(max_length=255)),
                (r'content_type', models.CharField(max_length=128)),
                (r'size_bytes', models.PositiveBigIntegerField()),
                (r'storage_backend', models.CharField(choices=[('ipfs', 'IPFS'), ('s3', 'S3 Vault'), ('encrypted_blob', 'Encrypted Blob Store')], default='ipfs', max_length=16)),
                (r'ipfs_cid', models.CharField(blank=True, db_index=True, max_length=128)),
                (r'encryption_key_b64', models.TextField(blank=True, help_text="Per-file AES key, itself encrypted with user's Kyber key")),
                (r'checksum_sha256', models.CharField(max_length=64)),
                (r'is_deleted', models.BooleanField(default=False)),
                (r'uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'messaging_attachment',
            },
        ),
        migrations.CreateModel(
            name=r'Mention',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'is_read', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'messaging_mention',
            },
        ),
        migrations.CreateModel(
            name=r'Message',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'ciphertext_b64', models.TextField(help_text='AES-256-GCM encrypted message body')),
                (r'nonce_b64', models.CharField(help_text='12-byte GCM nonce, base64', max_length=32)),
                (r'auth_tag_b64', models.CharField(help_text='16-byte GCM auth tag, base64', max_length=32)),
                (r'kyber_ciphertext_b64', models.TextField(blank=True, help_text='Kyber-1024 encapsulated symmetric key')),
                (r'dilithium_signature_b64', models.TextField(blank=True, help_text='Dilithium3 message signature')),
                (r'message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('system', 'System'), ('call', 'Call Event')], default='text', max_length=16)),
                (r'is_edited', models.BooleanField(default=False)),
                (r'is_deleted', models.BooleanField(default=False)),
                (r'deleted_at', models.DateTimeField(blank=True, null=True)),
                (r'ttl_seconds', models.PositiveIntegerField(blank=True, help_text='Seconds until hard-delete. Null = use channel/workspace policy.', null=True)),
                (r'destroy_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                (r'is_destroyed', models.BooleanField(db_index=True, default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                r'db_table': 'messaging_message',
                r'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name=r'MessageBookmark',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'note', models.CharField(blank=True, max_length=256)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'messaging_bookmark',
            },
        ),
        migrations.CreateModel(
            name=r'MessageEdit',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'previous_ciphertext_b64', models.TextField()),
                (r'previous_nonce_b64', models.CharField(max_length=32)),
                (r'edited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'messaging_message_edit',
                r'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name=r'MessageRead',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'messaging_message_read',
            },
        ),
        migrations.CreateModel(
            name=r'Reaction',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'emoji_code', models.CharField(help_text='Unicode or :custom_name:', max_length=64)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'messaging_reaction',
            },
        ),
        migrations.CreateModel(
            name=r'Thread',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'reply_count', models.PositiveIntegerField(default=0)),
                (r'last_reply_at', models.DateTimeField(blank=True, null=True)),
                (r'participant_count', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'messaging_thread',
                r'ordering': ['-last_reply_at'],
            },
        ),
        migrations.CreateModel(
            name=r'TTLPolicy',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'scope', models.CharField(choices=[('workspace', 'Workspace'), ('channel', 'Channel'), ('message', 'Message')], max_length=16)),
                (r'scope_id', models.UUIDField(db_index=True)),
                (r'ttl_seconds', models.PositiveIntegerField()),
                (r'applies_to_type', models.CharField(choices=[('all', 'All'), ('text', 'Text Only'), ('file', 'Files Only')], default='all', max_length=16)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'messaging_ttl_policy',
            },
        ),
        migrations.CreateModel(
            name=r'WebhookEndpoint',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=64)),
                (r'token_hash', models.CharField(max_length=256, unique=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'last_triggered', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                r'db_table': 'messaging_webhook',
            },
        ),
    ]
