# Generated by Django 6.0.1 on 2026-03-14 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (r'messaging', '0001_initial'),
        (r'workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name=r'attachment',
            name=r'uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'mention',
            name=r'mentioned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'mentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'message',
            name=r'channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'messages', to='workspace.channel'),
        ),
        migrations.AddField(
            model_name=r'message',
            name=r'sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=r'sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'mention',
            name=r'message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'mentions', to='messaging.message'),
        ),
        migrations.AddField(
            model_name=r'attachment',
            name=r'message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'attachments', to='messaging.message'),
        ),
        migrations.AddField(
            model_name=r'messagebookmark',
            name=r'message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'bookmarks', to='messaging.message'),
        ),
        migrations.AddField(
            model_name=r'messagebookmark',
            name=r'user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'messageedit',
            name=r'edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'messageedit',
            name=r'message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'edits', to='messaging.message'),
        ),
        migrations.AddField(
            model_name=r'messageread',
            name=r'message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'reads', to='messaging.message'),
        ),
        migrations.AddField(
            model_name=r'messageread',
            name=r'user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'message_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'reaction',
            name=r'message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'reactions', to='messaging.message'),
        ),
        migrations.AddField(
            model_name=r'reaction',
            name=r'user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'thread',
            name=r'channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'threads', to='workspace.channel'),
        ),
        migrations.AddField(
            model_name=r'thread',
            name=r'root_message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name=r'thread_root', to='messaging.message'),
        ),
        migrations.AddField(
            model_name=r'message',
            name=r'thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name=r'replies', to='messaging.thread'),
        ),
        migrations.AddField(
            model_name=r'ttlpolicy',
            name=r'created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'webhookendpoint',
            name=r'channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'webhooks', to='workspace.channel'),
        ),
        migrations.AddField(
            model_name=r'webhookendpoint',
            name=r'created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name=r'mention',
            index=models.Index(fields=[r'mentioned_user', 'is_read'], name='messaging_m_mention_39399e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name=r'messagebookmark',
            unique_together={(r'user', 'message')},
        ),
        migrations.AddIndex(
            model_name=r'messageread',
            index=models.Index(fields=[r'user', 'read_at'], name='messaging_m_user_id_4000fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name=r'messageread',
            unique_together={(r'message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name=r'reaction',
            unique_together={(r'message', 'user', 'emoji_code')},
        ),
        migrations.AddIndex(
            model_name=r'message',
            index=models.Index(fields=[r'channel', 'created_at'], name='messaging_m_channel_2af973_idx'),
        ),
        migrations.AddIndex(
            model_name=r'message',
            index=models.Index(fields=[r'channel', 'is_deleted', 'is_destroyed'], name='messaging_m_channel_e5accf_idx'),
        ),
        migrations.AddIndex(
            model_name=r'message',
            index=models.Index(fields=[r'destroy_at'], name='messaging_m_destroy_e388a6_idx'),
        ),
        migrations.AddIndex(
            model_name=r'message',
            index=models.Index(fields=[r'sender', 'created_at'], name='messaging_m_sender__277197_idx'),
        ),
    ]
