# Generated by Django 6.0.1 on 2026-03-14 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'messaging', '0002_initial'),
        (r'workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'BotCommand',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'command', models.CharField(max_length=50)),
                (r'description', models.TextField()),
                (r'handler_url', models.URLField()),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_bot_command',
            },
        ),
        migrations.CreateModel(
            name=r'MessageForward',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'forwarded_at', models.DateTimeField(auto_now_add=True)),
                (r'forwarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'original_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='messaging.message')),
                (r'target_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.channel')),
            ],
            options={
                r'db_table': 'messaging_forward',
            },
        ),
        migrations.CreateModel(
            name=r'MessageSearchIndex',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'search_hash', models.CharField(max_length=64)),
                (r'indexed_at', models.DateTimeField(auto_now=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.channel')),
                (r'message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_index', to='messaging.message')),
            ],
            options={
                r'db_table': 'messaging_search_index',
            },
        ),
        migrations.CreateModel(
            name=r'MessageTemplate',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'content', models.TextField()),
                (r'is_shared', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_template',
            },
        ),
        migrations.CreateModel(
            name=r'Poll',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'question', models.TextField()),
                (r'options', models.JSONField(default=list)),
                (r'is_anonymous', models.BooleanField(default=False)),
                (r'is_multiple', models.BooleanField(default=False)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='workspace.channel')),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_poll',
            },
        ),
        migrations.CreateModel(
            name=r'Reminder',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'remind_at', models.DateTimeField()),
                (r'is_sent', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='messaging.message')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_reminder',
            },
        ),
        migrations.CreateModel(
            name=r'ScheduledMessage',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'ciphertext_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'scheduled_at', models.DateTimeField()),
                (r'is_sent', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.channel')),
                (r'sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_scheduled_message',
            },
        ),
        migrations.CreateModel(
            name=r'PollVote',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'option_index', models.PositiveSmallIntegerField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='messaging.poll')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_poll_vote',
                r'unique_together': {('poll', 'user', 'option_index')},
            },
        ),
    ]
