# Generated by Django 6.0.1 on 2026-03-14 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'messaging', '0003_botcommand_messageforward_messagesearchindex_and_more'),
        (r'workspace', '0002_bankingchannel_compliancecheckpoint_dealroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'AnonymousReport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'report_token', models.CharField(max_length=64, unique=True)),
                (r'category', models.CharField(choices=[('fraud', 'Fraud'), ('misconduct', 'Misconduct'), ('aml', 'AML Violation'), ('data_breach', 'Data Breach'), ('bribery', 'Bribery'), ('other', 'Other')], max_length=50)),
                (r'ciphertext_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'attachments_cid', models.TextField(blank=True)),
                (r'status', models.CharField(choices=[('received', 'Received'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='received', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'resolved_at', models.DateTimeField(blank=True, null=True)),
                (r'assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_anonymous_report',
            },
        ),
        migrations.CreateModel(
            name=r'ChannelRetentionPolicy',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'retention_days', models.PositiveIntegerField(default=365)),
                (r'auto_wipe', models.BooleanField(default=False)),
                (r'legal_hold', models.BooleanField(default=False)),
                (r'legal_hold_reason', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policy', to='workspace.channel')),
                (r'legal_hold_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_retention_policy',
            },
        ),
        migrations.CreateModel(
            name=r'SecureVideoCall',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'session_key_b64', models.TextField()),
                (r'dtls_fingerprint', models.CharField(blank=True, max_length=255)),
                (r'status', models.CharField(choices=[('ringing', 'Ringing'), ('active', 'Active'), ('ended', 'Ended'), ('missed', 'Missed')], default='ringing', max_length=20)),
                (r'started_at', models.DateTimeField(blank=True, null=True)),
                (r'ended_at', models.DateTimeField(blank=True, null=True)),
                (r'duration_seconds', models.PositiveIntegerField(default=0)),
                (r'recording_cid', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='workspace.channel')),
                (r'initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'participants', models.ManyToManyField(related_name='video_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_video_call',
            },
        ),
        migrations.CreateModel(
            name=r'SecureVoiceMessage',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'audio_cid', models.TextField()),
                (r'ciphertext_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'duration_seconds', models.PositiveIntegerField(default=0)),
                (r'is_transcribed', models.BooleanField(default=False)),
                (r'transcript_encrypted_b64', models.TextField(blank=True)),
                (r'destroy_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_messages', to='workspace.channel')),
                (r'sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_voice_message',
            },
        ),
        migrations.CreateModel(
            name=r'TradingCommunication',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'instrument', models.CharField(blank=True, max_length=50)),
                (r'isin', models.CharField(blank=True, max_length=12)),
                (r'direction', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], max_length=10)),
                (r'quantity', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                (r'price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                (r'currency', models.CharField(blank=True, max_length=3)),
                (r'is_pre_trade', models.BooleanField(default=False)),
                (r'is_post_trade', models.BooleanField(default=False)),
                (r'mifid_reported', models.BooleanField(default=False)),
                (r'reported_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trading_comm', to='messaging.message')),
            ],
            options={
                r'db_table': 'messaging_trading_comm',
            },
        ),
    ]
