# Generated by Django 6.0.1 on 2026-03-14 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'messaging', '0004_anonymousreport_channelretentionpolicy_and_more'),
        (r'workspace', '0003_escalationmatrix_tradingdesk_workspaceannouncement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'ChatbotSession',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'bot_type', models.CharField(choices=[('compliance_assistant', 'Compliance Assistant'), ('trading_assistant', 'Trading Assistant'), ('kyc_assistant', 'KYC Assistant'), ('general', 'General Assistant')], max_length=50)),
                (r'context', models.JSONField(default=dict)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'ended_at', models.DateTimeField(blank=True, null=True)),
                (r'channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.channel')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_chatbot_session',
            },
        ),
        migrations.CreateModel(
            name=r'NotificationQueue',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'notification_type', models.CharField(choices=[('push', 'Push'), ('email', 'Email'), ('sms', 'SMS'), ('in_app', 'In-App')], max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'body', models.TextField()),
                (r'data', models.JSONField(default=dict)),
                (r'priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                (r'retry_count', models.PositiveSmallIntegerField(default=0)),
                (r'scheduled_at', models.DateTimeField(auto_now_add=True)),
                (r'sent_at', models.DateTimeField(blank=True, null=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_notification_queue',
            },
        ),
        migrations.CreateModel(
            name=r'SecureConferenceRoom',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'room_type', models.CharField(choices=[('board', 'Board Meeting'), ('trading', 'Trading Floor'), ('compliance', 'Compliance Review'), ('deal', 'Deal Discussion'), ('crisis', 'Crisis Management'), ('general', 'General')], max_length=50)),
                (r'session_key_b64', models.TextField(blank=True)),
                (r'max_participants', models.PositiveIntegerField(default=50)),
                (r'is_recorded', models.BooleanField(default=False)),
                (r'recording_cid', models.TextField(blank=True)),
                (r'requires_mfa', models.BooleanField(default=True)),
                (r'min_clearance', models.PositiveSmallIntegerField(default=1)),
                (r'is_active', models.BooleanField(default=False)),
                (r'started_at', models.DateTimeField(blank=True, null=True)),
                (r'ended_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conference_rooms', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_conference_room',
            },
        ),
        migrations.CreateModel(
            name=r'MessageTranslation',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'language', models.CharField(max_length=10)),
                (r'translated_ciphertext_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'translated_by', models.CharField(default='deepl', max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='messaging.message')),
            ],
            options={
                r'db_table': 'messaging_translation',
                r'unique_together': {('message', 'language')},
            },
        ),
        migrations.CreateModel(
            name=r'ConferenceParticipant',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'role', models.CharField(choices=[('host', 'Host'), ('presenter', 'Presenter'), ('participant', 'Participant'), ('observer', 'Observer')], default='participant', max_length=20)),
                (r'joined_at', models.DateTimeField(auto_now_add=True)),
                (r'left_at', models.DateTimeField(blank=True, null=True)),
                (r'is_muted', models.BooleanField(default=False)),
                (r'is_video_on', models.BooleanField(default=False)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='messaging.secureconferenceroom')),
            ],
            options={
                r'db_table': 'messaging_conference_participant',
                r'unique_together': {('room', 'user')},
            },
        ),
    ]
