# Generated by Django 6.0.1 on 2026-03-14 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'messaging', '0005_chatbotsession_notificationqueue_and_more'),
        (r'workspace', '0004_servicelevelagreement_workflowinstance_workflowstep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'FileRoomDocument',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'filename', models.CharField(max_length=255)),
                (r'file_cid', models.TextField()),
                (r'ciphertext_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'file_size', models.BigIntegerField(default=0)),
                (r'mime_type', models.CharField(blank=True, max_length=100)),
                (r'version', models.PositiveIntegerField(default=1)),
                (r'view_count', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_file_room_document',
            },
        ),
        migrations.CreateModel(
            name=r'DocumentAccessLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'action', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('print', 'Print'), ('share', 'Share')], max_length=20)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'device_fingerprint', models.CharField(blank=True, max_length=255)),
                (r'watermark_id', models.CharField(blank=True, max_length=64)),
                (r'accessed_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='messaging.fileroomdocument')),
            ],
            options={
                r'db_table': 'messaging_document_access_log',
            },
        ),
        migrations.CreateModel(
            name=r'PinnedResource',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'resource_type', models.CharField(choices=[('message', 'Message'), ('document', 'Document'), ('link', 'Link'), ('contact', 'Contact'), ('deal', 'Deal'), ('report', 'Report')], max_length=50)),
                (r'resource_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'pinned_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_resources', to='workspace.channel')),
                (r'pinned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_pinned_resource',
            },
        ),
        migrations.CreateModel(
            name=r'SecureFileRoom',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'room_type', models.CharField(choices=[('due_diligence', 'Due Diligence'), ('legal', 'Legal Documents'), ('financial', 'Financial Reports'), ('regulatory', 'Regulatory Filing'), ('board', 'Board Documents')], max_length=50)),
                (r'watermark_enabled', models.BooleanField(default=True)),
                (r'download_enabled', models.BooleanField(default=False)),
                (r'print_enabled', models.BooleanField(default=False)),
                (r'screenshot_blocked', models.BooleanField(default=True)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'participants', models.ManyToManyField(related_name='file_rooms', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_rooms', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_file_room',
            },
        ),
        migrations.AddField(
            model_name=r'fileroomdocument',
            name=r'room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'documents', to='messaging.securefileroom'),
        ),
    ]
