# Generated by Django 6.0.1 on 2026-03-15 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'messaging', '0006_fileroomdocument_documentaccesslog_pinnedresource_and_more'),
        (r'workspace', '0008_documenttemplate_githubevent_meetingnotes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name=r'pollvote',
            name=r'poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'poll_votes', to='messaging.poll'),
        ),
        migrations.AlterModelTable(
            name=r'pollvote',
            table=r'messaging_channel_poll_vote',
        ),
        migrations.CreateModel(
            name=r'IceBreaker',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'question', models.TextField()),
                (r'category', models.CharField(max_length=50)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_ice_breaker',
            },
        ),
        migrations.CreateModel(
            name=r'StatusUpdate',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'content_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'mood', models.CharField(choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('stressed', 'Stressed'), ('blocked', 'Blocked')], default='good', max_length=20)),
                (r'blockers', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_status_update',
            },
        ),
        migrations.CreateModel(
            name=r'WaterCooler',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'topic', models.CharField(max_length=255)),
                (r'category', models.CharField(choices=[('fun', 'Fun & Games'), ('news', 'News & Trends'), ('learning', 'Learning'), ('health', 'Health & Wellness'), ('random', 'Random')], max_length=50)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_water_cooler',
            },
        ),
        migrations.CreateModel(
            name=r'WorkspacePoll',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'question', models.TextField()),
                (r'options', models.JSONField(default=list)),
                (r'is_anonymous', models.BooleanField(default=False)),
                (r'is_multiple', models.BooleanField(default=False)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.channel')),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_workspace_poll',
            },
        ),
        migrations.CreateModel(
            name=r'IceBreakerResponse',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'response_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='messaging.icebreaker')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_ice_breaker_response',
                r'unique_together': {('question', 'user')},
            },
        ),
        migrations.CreateModel(
            name=r'WorkspacePollVote',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'option_index', models.PositiveSmallIntegerField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='messaging.workspacepoll')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_workspace_poll_vote',
                r'unique_together': {('poll', 'user', 'option_index')},
            },
        ),
    ]
