# Generated by Django 6.0.1 on 2026-03-15 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'messaging', '0007_alter_pollvote_poll_alter_pollvote_table_icebreaker_and_more'),
        (r'workspace', '0009_budgettracker_budgetexpense_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'AppIntegrationMessage',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'app_name', models.CharField(max_length=100)),
                (r'app_icon_url', models.URLField(blank=True)),
                (r'content', models.JSONField(default=dict)),
                (r'is_interactive', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.channel')),
            ],
            options={
                r'db_table': 'messaging_app_message',
            },
        ),
        migrations.CreateModel(
            name=r'ChannelTopic',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'topic', models.CharField(max_length=255)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='workspace.channel')),
                (r'set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_channel_topic',
            },
        ),
        migrations.CreateModel(
            name=r'GroupDMChannel',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(blank=True, max_length=100)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'members', models.ManyToManyField(related_name='group_dms', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_group_dm',
            },
        ),
        migrations.CreateModel(
            name=r'MessageDraft',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'content_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.channel')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_draft',
            },
        ),
        migrations.CreateModel(
            name=r'MessageReminder',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'remind_at', models.DateTimeField()),
                (r'is_sent', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.message')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_message_reminder',
            },
        ),
        migrations.CreateModel(
            name=r'MessageThread',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'reply_count', models.PositiveIntegerField(default=0)),
                (r'last_reply_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_threads', to='workspace.channel')),
                (r'participants', models.ManyToManyField(blank=True, related_name='thread_participations', to=settings.AUTH_USER_MODEL)),
                (r'root_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_thread_root', to='messaging.message')),
            ],
            options={
                r'db_table': 'messaging_message_thread',
            },
        ),
        migrations.CreateModel(
            name=r'SharedLink',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'url', models.URLField()),
                (r'title', models.CharField(blank=True, max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'image_url', models.URLField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='messaging.message')),
            ],
            options={
                r'db_table': 'messaging_shared_link',
            },
        ),
        migrations.CreateModel(
            name=r'DirectMessageChannel',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'is_blocked', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_as_user1', to=settings.AUTH_USER_MODEL)),
                (r'user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_as_user2', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_dm_channel',
                r'unique_together': {('workspace', 'user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name=r'MessageStar',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='messaging.message')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_star',
                r'unique_together': {('user', 'message')},
            },
        ),
        migrations.CreateModel(
            name=r'UserTypingStatus',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'is_typing', models.BooleanField(default=False)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.channel')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_typing_status',
                r'unique_together': {('user', 'channel')},
            },
        ),
    ]
