# Generated by Django 6.0.1 on 2026-03-15 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'messaging', '0008_appintegrationmessage_channeltopic_groupdmchannel_and_more'),
        (r'workspace', '0010_automation_automationlog_customfield_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name=r'messagetemplate',
            name=r'is_shared',
        ),
        migrations.AddField(
            model_name=r'messagetemplate',
            name=r'category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name=r'messagetemplate',
            name=r'workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'msg_templates', to='workspace.workspace'),
        ),
        migrations.AlterModelTable(
            name=r'messagetemplate',
            table=r'messaging_msg_template',
        ),
        migrations.CreateModel(
            name=r'AutoResponse',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'trigger_keyword', models.CharField(max_length=100)),
                (r'response', models.TextField()),
                (r'is_case_sensitive', models.BooleanField(default=False)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_responses', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_auto_response',
            },
        ),
        migrations.CreateModel(
            name=r'BroadcastMessage',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'ciphertext_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'sent_at', models.DateTimeField(auto_now_add=True)),
                (r'sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'target_channels', models.ManyToManyField(blank=True, related_name='broadcasts', to='workspace.channel')),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_broadcast',
            },
        ),
        migrations.CreateModel(
            name=r'ChannelInvite',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_invites', to='workspace.channel')),
                (r'invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_invites_sent', to=settings.AUTH_USER_MODEL)),
                (r'invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_invites_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_channel_invite',
            },
        ),
        migrations.CreateModel(
            name=r'MessageFlag',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate'), ('misinformation', 'Misinformation'), ('other', 'Other')], max_length=50)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='messaging.message')),
                (r'reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_flag',
            },
        ),
        migrations.CreateModel(
            name=r'MessageVersion',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'ciphertext_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'version_number', models.PositiveIntegerField(default=1)),
                (r'edited_at', models.DateTimeField(auto_now_add=True)),
                (r'message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='messaging.message')),
            ],
            options={
                r'db_table': 'messaging_message_version',
            },
        ),
        migrations.CreateModel(
            name=r'ChannelPermission',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'can_post', models.BooleanField(default=True)),
                (r'can_upload', models.BooleanField(default=True)),
                (r'can_invite', models.BooleanField(default=False)),
                (r'is_moderator', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='workspace.channel')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_channel_permission',
                r'unique_together': {('channel', 'user')},
            },
        ),
        migrations.CreateModel(
            name=r'CustomEmoji',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=50)),
                (r'image_cid', models.TextField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_emojis_set', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'messaging_custom_emoji',
                r'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name=r'EmojiReaction',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'emoji', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_reactions', to='messaging.message')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_emoji_reaction',
                r'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name=r'ReadReceipt',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'read_at', models.DateTimeField(auto_now_add=True)),
                (r'message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='messaging.message')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'messaging_read_receipt',
                r'unique_together': {('message', 'user')},
            },
        ),
    ]
