# Generated by Django 6.0.1 on 2026-03-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'messaging', '0009_remove_messagetemplate_is_shared_and_more'),
        (r'workspace', '0017_apikey_appversion_geolocation_knowledgetag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name=r'messagetemplate',
            name=r'category',
        ),
        migrations.AddField(
            model_name=r'messagetemplate',
            name=r'is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name=r'messagetemplate',
            name=r'workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=r'workspace.workspace'),
        ),
        migrations.AlterModelTable(
            name=r'messagetemplate',
            table=r'messaging_template',
        ),
    ]
