# Generated by Django 6.0.1 on 2026-03-14 01:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name=r'AuditLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'event_type', models.CharField(db_index=True, max_length=64)),
                (r'severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical'), ('alert', 'Security Alert')], default='info', max_length=16)),
                (r'actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                (r'actor_user_agent', models.CharField(blank=True, max_length=512)),
                (r'target_type', models.CharField(blank=True, db_index=True, max_length=32)),
                (r'target_id', models.CharField(blank=True, max_length=64)),
                (r'description', models.TextField()),
                (r'metadata', models.JSONField(default=dict)),
                (r'created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                r'db_table': 'compliance_audit_log',
                r'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name=r'ComplianceReport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'report_type', models.CharField(choices=[('daily_audit', 'Daily Audit Summary'), ('user_activity', 'User Activity Report'), ('vault_access', 'Vault Access Report'), ('message_retention', 'Message Retention Report'), ('security_incidents', 'Security Incidents Report'), ('regulatory', 'Regulatory Submission')], max_length=32)),
                (r'title', models.CharField(max_length=256)),
                (r'date_from', models.DateTimeField()),
                (r'date_to', models.DateTimeField()),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                (r'report_ipfs_cid', models.CharField(blank=True, help_text='IPFS CID of encrypted PDF report', max_length=128)),
                (r'generated_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'compliance_report',
            },
        ),
        migrations.CreateModel(
            name=r'DataRetentionPolicy',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'message_retention_days', models.PositiveIntegerField(default=365)),
                (r'file_retention_days', models.PositiveIntegerField(default=730)),
                (r'audit_log_retention_days', models.PositiveIntegerField(default=2555, help_text='7 years for banking compliance')),
                (r'auto_delete_enabled', models.BooleanField(default=True)),
                (r'legal_hold', models.BooleanField(default=False, help_text='Freeze all deletions during legal hold')),
                (r'legal_hold_reason', models.TextField(blank=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                r'db_table': 'compliance_retention_policy',
            },
        ),
        migrations.CreateModel(
            name=r'ExportRequest',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'export_type', models.CharField(choices=[('messages', 'Messages'), ('audit_logs', 'Audit Logs'), ('user_data', 'User Data')], max_length=32)),
                (r'justification', models.TextField()),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Completed')], default='pending', max_length=16)),
                (r'approved_at', models.DateTimeField(blank=True, null=True)),
                (r'export_ipfs_cid', models.CharField(blank=True, max_length=128)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'compliance_export_request',
            },
        ),
        migrations.CreateModel(
            name=r'ForensicsBlock',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'metadata_scrubbing', models.BooleanField(default=True, help_text='Remove EXIF and file metadata on upload')),
                (r'header_scrubbing', models.BooleanField(default=True, help_text='Strip identifying headers from responses')),
                (r'log_retention_wipe', models.BooleanField(default=False, help_text='Wipe server logs after 30 days')),
                (r'clipboard_protection', models.BooleanField(default=True)),
                (r'screenshot_detection', models.BooleanField(default=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                r'db_table': 'compliance_forensics_block',
            },
        ),
        migrations.CreateModel(
            name=r'RegulatorAccess',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'regulator_name', models.CharField(max_length=128)),
                (r'regulator_email', models.EmailField(max_length=254)),
                (r'access_token_hash', models.CharField(max_length=256, unique=True)),
                (r'scope', models.JSONField(default=list, help_text='List of accessible resource types')),
                (r'valid_from', models.DateTimeField()),
                (r'valid_until', models.DateTimeField()),
                (r'is_active', models.BooleanField(default=True)),
                (r'access_log', models.JSONField(default=list)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'compliance_regulator_access',
            },
        ),
        migrations.CreateModel(
            name=r'SecurityEvent',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAIL', 'Failed Login'), ('ACCOUNT_LOCKED', 'Account Locked'), ('MFA_VERIFIED', 'MFA Verified'), ('MFA_FAIL', 'MFA Failure'), ('PASSWORD_CHANGED', 'Password Changed'), ('VAULT_OPENED', 'Vault Session Opened'), ('VAULT_ACCESS_DENIED', 'Vault Access Denied'), ('HW_KEY_REGISTERED', 'Hardware Key Registered'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('DATA_EXPORT', 'Data Export'), ('TTL_WIPE', 'Message TTL Wipe'), ('SESSION_REVOKED', 'Session Revoked'), ('INVALID_SIGNATURE', 'Invalid Message Signature')], db_index=True, max_length=32)),
                (r'ip_address', models.GenericIPAddressField(blank=True, null=True)),
                (r'is_suspicious', models.BooleanField(db_index=True, default=False)),
                (r'detail', models.JSONField(default=dict)),
                (r'created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                r'db_table': 'compliance_security_event',
                r'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name=r'UserConsent',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'consent_type', models.CharField(choices=[('data_processing', 'Data Processing'), ('message_monitoring', 'Message Monitoring'), ('audit_logging', 'Audit Logging'), ('cross_border_transfer', 'Cross-Border Data Transfer')], max_length=32)),
                (r'version', models.CharField(help_text='Policy version e.g. v2.3', max_length=16)),
                (r'consented', models.BooleanField(default=False)),
                (r'consented_at', models.DateTimeField(blank=True, null=True)),
                (r'revoked_at', models.DateTimeField(blank=True, null=True)),
                (r'ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                r'db_table': 'compliance_user_consent',
            },
        ),
    ]
