# Generated by Django 6.0.1 on 2026-03-14 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (r'compliance', '0001_initial'),
        (r'workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name=r'auditlog',
            name=r'actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=r'audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'auditlog',
            name=r'workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=r'system_audit_logs', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name=r'compliancereport',
            name=r'requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'compliancereport',
            name=r'workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name=r'compliance_reports', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name=r'dataretentionpolicy',
            name=r'workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name=r'retention_policy', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name=r'exportrequest',
            name=r'approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=r'approved_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'exportrequest',
            name=r'requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'export_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'exportrequest',
            name=r'workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=r'workspace.workspace'),
        ),
        migrations.AddField(
            model_name=r'forensicsblock',
            name=r'workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=r'workspace.workspace'),
        ),
        migrations.AddField(
            model_name=r'regulatoraccess',
            name=r'granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'regulatoraccess',
            name=r'workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=r'workspace.workspace'),
        ),
        migrations.AddField(
            model_name=r'securityevent',
            name=r'user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=r'security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'userconsent',
            name=r'user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name=r'auditlog',
            index=models.Index(fields=[r'event_type', 'created_at'], name='compliance__event_t_80624d_idx'),
        ),
        migrations.AddIndex(
            model_name=r'auditlog',
            index=models.Index(fields=[r'actor', 'created_at'], name='compliance__actor_i_1e30fc_idx'),
        ),
        migrations.AddIndex(
            model_name=r'auditlog',
            index=models.Index(fields=[r'severity', 'created_at'], name='compliance__severit_a78fa1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name=r'userconsent',
            unique_together={(r'user', 'consent_type', 'version')},
        ),
    ]
