# Generated by Django 6.0.1 on 2026-03-14 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'SystemHealthLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'service', models.CharField(max_length=50)),
                (r'status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], max_length=20)),
                (r'response_time_ms', models.PositiveIntegerField(default=0)),
                (r'details', models.JSONField(default=dict)),
                (r'checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'compliance_system_health',
            },
        ),
        migrations.CreateModel(
            name=r'ThreatIntelligence',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'threat_type', models.CharField(max_length=50)),
                (r'indicator', models.CharField(max_length=255)),
                (r'severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                (r'description', models.TextField(blank=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'source', models.CharField(blank=True, max_length=100)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                r'db_table': 'compliance_threat_intel',
            },
        ),
    ]
