# Generated by Django 6.0.1 on 2026-03-14 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0003_systemhealthlog_threatintelligence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'AMLAlert',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'alert_type', models.CharField(choices=[('structuring', 'Structuring'), ('layering', 'Layering'), ('smurfing', 'Smurfing'), ('rapid_movement', 'Rapid Movement'), ('unusual_pattern', 'Unusual Pattern'), ('pep_match', 'PEP Match'), ('sanctions_match', 'Sanctions Match')], max_length=50)),
                (r'severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                (r'description', models.TextField()),
                (r'is_resolved', models.BooleanField(default=False)),
                (r'resolved_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_aml_alert',
            },
        ),
        migrations.CreateModel(
            name=r'RegulatoryReport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'report_type', models.CharField(choices=[('ojk_daily', 'OJK Daily'), ('bi_weekly', 'BI Weekly'), ('ppatk_monthly', 'PPATK Monthly'), ('lkd_quarterly', 'LKD Quarterly'), ('swift_annual', 'SWIFT Annual')], max_length=50)),
                (r'regulator', models.CharField(max_length=50)),
                (r'period_start', models.DateTimeField()),
                (r'period_end', models.DateTimeField()),
                (r'total_transactions', models.PositiveIntegerField(default=0)),
                (r'total_alerts', models.PositiveIntegerField(default=0)),
                (r'total_sar', models.PositiveIntegerField(default=0)),
                (r'report_data', models.JSONField(default=dict)),
                (r'file_path', models.TextField(blank=True)),
                (r'is_submitted', models.BooleanField(default=False)),
                (r'submitted_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_regulatory_report',
            },
        ),
        migrations.CreateModel(
            name=r'SARReport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'report_number', models.CharField(max_length=50, unique=True)),
                (r'narrative', models.TextField()),
                (r'submitted_to', models.CharField(default='PPATK', max_length=50)),
                (r'submitted_at', models.DateTimeField(blank=True, null=True)),
                (r'is_submitted', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sar_reports', to='compliance.amlalert')),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_sar_report',
            },
        ),
        migrations.CreateModel(
            name=r'TransactionMonitor',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'transaction_id', models.CharField(max_length=100, unique=True)),
                (r'amount', models.DecimalField(decimal_places=8, max_digits=20)),
                (r'currency', models.CharField(default='IDR', max_length=10)),
                (r'transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('payment', 'Payment'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('fx', 'Foreign Exchange'), ('swift', 'SWIFT')], max_length=50)),
                (r'sender_account', models.CharField(blank=True, max_length=100)),
                (r'receiver_account', models.CharField(blank=True, max_length=100)),
                (r'risk_score', models.FloatField(default=0.0)),
                (r'is_flagged', models.BooleanField(default=False)),
                (r'flag_reason', models.TextField(blank=True)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                (r'metadata', models.JSONField(default=dict)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_transaction_monitor',
            },
        ),
        migrations.AddField(
            model_name=r'amlalert',
            name=r'transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'aml_alerts', to='compliance.transactionmonitor'),
        ),
        migrations.AddIndex(
            model_name=r'transactionmonitor',
            index=models.Index(fields=[r'user', 'created_at'], name='compliance__user_id_9698d8_idx'),
        ),
        migrations.AddIndex(
            model_name=r'transactionmonitor',
            index=models.Index(fields=[r'is_flagged', 'status'], name='compliance__is_flag_6a7ac1_idx'),
        ),
        migrations.AddIndex(
            model_name=r'transactionmonitor',
            index=models.Index(fields=[r'risk_score'], name='compliance__risk_sc_1d2679_idx'),
        ),
    ]
