# Generated by Django 6.0.1 on 2026-03-14 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0004_amlalert_regulatoryreport_sarreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'FraudPattern',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'pattern_name', models.CharField(max_length=100)),
                (r'pattern_type', models.CharField(choices=[('velocity', 'Velocity Check'), ('geolocation', 'Geolocation Anomaly'), ('device', 'Device Fingerprint'), ('behavioral', 'Behavioral Analysis'), ('network', 'Network Analysis')], max_length=50)),
                (r'rules', models.JSONField(default=dict)),
                (r'threshold', models.FloatField(default=0.8)),
                (r'is_active', models.BooleanField(default=True)),
                (r'true_positive_rate', models.FloatField(default=0.0)),
                (r'false_positive_rate', models.FloatField(default=0.0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                r'db_table': 'compliance_fraud_pattern',
            },
        ),
        migrations.CreateModel(
            name=r'ImmutableAuditChain',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'sequence', models.BigIntegerField(default=0, unique=True)),
                (r'event_type', models.CharField(max_length=100)),
                (r'actor_id', models.CharField(max_length=50)),
                (r'resource_type', models.CharField(max_length=50)),
                (r'resource_id', models.CharField(max_length=50)),
                (r'action', models.CharField(max_length=50)),
                (r'data_hash', models.CharField(max_length=64)),
                (r'previous_hash', models.CharField(max_length=64)),
                (r'chain_hash', models.CharField(max_length=64, unique=True)),
                (r'timestamp', models.DateTimeField(auto_now_add=True)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
            ],
            options={
                r'db_table': 'compliance_immutable_chain',
                r'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name=r'FraudCase',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'case_number', models.CharField(max_length=50, unique=True)),
                (r'status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('confirmed', 'Confirmed Fraud'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                (r'evidence', models.JSONField(default=dict)),
                (r'resolved_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                (r'transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.transactionmonitor')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_cases', to=settings.AUTH_USER_MODEL)),
                (r'pattern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.fraudpattern')),
            ],
            options={
                r'db_table': 'compliance_fraud_case',
            },
        ),
        migrations.CreateModel(
            name=r'KYCVerificationFlow',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'step', models.CharField(choices=[('identity', 'Identity Verification'), ('liveness', 'Liveness Check'), ('document', 'Document Scan'), ('address', 'Address Verification'), ('pep_check', 'PEP Screening'), ('sanctions', 'Sanctions Check'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=50)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                (r'provider', models.CharField(blank=True, max_length=50)),
                (r'result_data', models.JSONField(default=dict)),
                (r'confidence_score', models.FloatField(default=0.0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
                (r'reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_flows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_kyc_flow',
            },
        ),
        migrations.CreateModel(
            name=r'PEPScreening',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'is_pep', models.BooleanField(default=False)),
                (r'pep_category', models.CharField(blank=True, max_length=50)),
                (r'pep_country', models.CharField(blank=True, max_length=50)),
                (r'risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                (r'screened_by', models.CharField(default='automated', max_length=50)),
                (r'screened_at', models.DateTimeField(auto_now_add=True)),
                (r'next_review', models.DateTimeField(blank=True, null=True)),
                (r'notes', models.TextField(blank=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pep_screenings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_pep_screening',
            },
        ),
        migrations.CreateModel(
            name=r'SanctionsCheck',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'is_sanctioned', models.BooleanField(default=False)),
                (r'sanctions_list', models.CharField(blank=True, max_length=50)),
                (r'match_score', models.FloatField(default=0.0)),
                (r'match_details', models.JSONField(default=dict)),
                (r'screened_at', models.DateTimeField(auto_now_add=True)),
                (r'screened_by', models.CharField(default='automated', max_length=50)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_sanctions_check',
            },
        ),
    ]
