# Generated by Django 6.0.1 on 2026-03-14 07:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0005_fraudpattern_immutableauditchain_fraudcase_and_more'),
        (r'workspace', '0002_bankingchannel_compliancecheckpoint_dealroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'DataRetentionExecution',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'policy_name', models.CharField(max_length=100)),
                (r'records_deleted', models.PositiveIntegerField(default=0)),
                (r'bytes_freed', models.BigIntegerField(default=0)),
                (r'execution_time_ms', models.PositiveIntegerField(default=0)),
                (r'status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=20)),
                (r'error_log', models.TextField(blank=True)),
                (r'executed_by', models.CharField(default='celery', max_length=50)),
                (r'started_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                r'db_table': 'compliance_retention_execution',
            },
        ),
        migrations.CreateModel(
            name=r'NDARecord',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'document_hash', models.CharField(max_length=64)),
                (r'document_cid', models.TextField(blank=True)),
                (r'signature_b64', models.TextField()),
                (r'signed_at', models.DateTimeField(auto_now_add=True)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'deal_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ndas', to='workspace.dealroom')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_nda_record',
            },
        ),
        migrations.CreateModel(
            name=r'RegulatoryDeadline',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'regulator', models.CharField(choices=[('ojk', 'OJK'), ('bi', 'Bank Indonesia'), ('ppatk', 'PPATK'), ('basel', 'Basel Committee'), ('swift', 'SWIFT'), ('fatf', 'FATF')], max_length=50)),
                (r'requirement', models.CharField(max_length=255)),
                (r'deadline', models.DateTimeField()),
                (r'is_recurring', models.BooleanField(default=False)),
                (r'recurrence', models.CharField(blank=True, max_length=20)),
                (r'is_completed', models.BooleanField(default=False)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
                (r'notes', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_regulatory_deadline',
            },
        ),
        migrations.CreateModel(
            name=r'StressTestScenario',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'scenario_name', models.CharField(max_length=100)),
                (r'scenario_type', models.CharField(choices=[('credit_risk', 'Credit Risk'), ('market_risk', 'Market Risk'), ('liquidity_risk', 'Liquidity Risk'), ('operational_risk', 'Operational Risk'), ('systemic_risk', 'Systemic Risk')], max_length=50)),
                (r'parameters', models.JSONField(default=dict)),
                (r'assumptions', models.TextField(blank=True)),
                (r'is_regulatory', models.BooleanField(default=False)),
                (r'regulator', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_stress_test_scenario',
            },
        ),
        migrations.CreateModel(
            name=r'StressTestResult',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'capital_ratio', models.FloatField(default=0.0)),
                (r'liquidity_ratio', models.FloatField(default=0.0)),
                (r'npv_impact', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                (r'passed', models.BooleanField(default=False)),
                (r'result_data', models.JSONField(default=dict)),
                (r'run_at', models.DateTimeField(auto_now_add=True)),
                (r'run_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compliance.stresstestscenario')),
            ],
            options={
                r'db_table': 'compliance_stress_test_result',
            },
        ),
        migrations.CreateModel(
            name=r'WatchlistEntry',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'watchlist_type', models.CharField(choices=[('aml', 'AML Watchlist'), ('fraud', 'Fraud Watchlist'), ('sanctions', 'Sanctions List'), ('pep', 'PEP List'), ('internal', 'Internal Watchlist')], max_length=50)),
                (r'reason', models.TextField()),
                (r'risk_score', models.FloatField(default=0.0)),
                (r'review_date', models.DateTimeField(blank=True, null=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'removed_at', models.DateTimeField(blank=True, null=True)),
                (r'added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlist_additions', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_watchlist',
            },
        ),
    ]
