# Generated by Django 6.0.1 on 2026-03-14 07:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0006_dataretentionexecution_ndarecord_regulatorydeadline_and_more'),
        (r'workspace', '0003_escalationmatrix_tradingdesk_workspaceannouncement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'AIComplianceAlert',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'alert_source', models.CharField(choices=[('nlp_scan', 'NLP Message Scan'), ('behavior_analysis', 'Behavior Analysis'), ('pattern_match', 'Pattern Matching'), ('anomaly_detection', 'Anomaly Detection'), ('sentiment_analysis', 'Sentiment Analysis')], max_length=50)),
                (r'severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                (r'confidence_score', models.FloatField(default=0.0)),
                (r'resource_type', models.CharField(blank=True, max_length=50)),
                (r'resource_id', models.CharField(blank=True, max_length=50)),
                (r'description', models.TextField()),
                (r'raw_signal', models.JSONField(default=dict)),
                (r'is_false_positive', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'reviewed_at', models.DateTimeField(blank=True, null=True)),
                (r'affected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_alerts', to=settings.AUTH_USER_MODEL)),
                (r'reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_ai_alert',
            },
        ),
        migrations.CreateModel(
            name=r'CommunicationSurveillance',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'scan_type', models.CharField(choices=[('keyword', 'Keyword Scan'), ('nlp', 'NLP Analysis'), ('sentiment', 'Sentiment Analysis'), ('insider_trading', 'Insider Trading Detection'), ('market_manipulation', 'Market Manipulation')], max_length=50)),
                (r'flagged_keywords', models.JSONField(default=list)),
                (r'risk_score', models.FloatField(default=0.0)),
                (r'messages_scanned', models.PositiveIntegerField(default=0)),
                (r'messages_flagged', models.PositiveIntegerField(default=0)),
                (r'scan_period_start', models.DateTimeField()),
                (r'scan_period_end', models.DateTimeField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.channel')),
                (r'reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_comm_surveillance',
            },
        ),
        migrations.CreateModel(
            name=r'MLModelRegistry',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'model_name', models.CharField(max_length=100)),
                (r'model_type', models.CharField(choices=[('fraud_detection', 'Fraud Detection'), ('aml_detection', 'AML Detection'), ('sentiment', 'Sentiment Analysis'), ('anomaly', 'Anomaly Detection'), ('kyc_verification', 'KYC Verification'), ('risk_scoring', 'Risk Scoring')], max_length=50)),
                (r'version', models.CharField(max_length=20)),
                (r'model_hash', models.CharField(max_length=64)),
                (r'accuracy', models.FloatField(default=0.0)),
                (r'precision', models.FloatField(default=0.0)),
                (r'recall', models.FloatField(default=0.0)),
                (r'f1_score', models.FloatField(default=0.0)),
                (r'is_active', models.BooleanField(default=False)),
                (r'deployed_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'trained_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_ml_model',
            },
        ),
        migrations.CreateModel(
            name=r'RiskMatrix',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'risk_category', models.CharField(choices=[('credit', 'Credit Risk'), ('market', 'Market Risk'), ('liquidity', 'Liquidity Risk'), ('operational', 'Operational Risk'), ('reputational', 'Reputational Risk'), ('compliance', 'Compliance Risk'), ('cyber', 'Cyber Risk'), ('strategic', 'Strategic Risk')], max_length=50)),
                (r'risk_name', models.CharField(max_length=255)),
                (r'likelihood', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                (r'impact', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                (r'risk_score', models.FloatField(default=0.0)),
                (r'mitigation', models.TextField(blank=True)),
                (r'review_date', models.DateTimeField(blank=True, null=True)),
                (r'status', models.CharField(choices=[('identified', 'Identified'), ('mitigating', 'Mitigating'), ('accepted', 'Accepted'), ('resolved', 'Resolved')], default='identified', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_risk_matrix',
            },
        ),
    ]
