# Generated by Django 6.0.1 on 2026-03-14 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0007_aicompliancealert_communicationsurveillance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'LiquidityReport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'report_date', models.DateField()),
                (r'hqla_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                (r'net_cash_outflow', models.DecimalField(decimal_places=2, max_digits=20)),
                (r'lcr', models.FloatField()),
                (r'available_stable_funding', models.DecimalField(decimal_places=2, max_digits=20)),
                (r'required_stable_funding', models.DecimalField(decimal_places=2, max_digits=20)),
                (r'nsfr', models.FloatField()),
                (r'is_compliant', models.BooleanField(default=True)),
                (r'alert_triggered', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'compliance_liquidity_report',
            },
        ),
        migrations.CreateModel(
            name=r'BaselCapitalReport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'report_date', models.DateField()),
                (r'tier1_capital', models.DecimalField(decimal_places=2, max_digits=20)),
                (r'tier2_capital', models.DecimalField(decimal_places=2, max_digits=20)),
                (r'total_capital', models.DecimalField(decimal_places=2, max_digits=20)),
                (r'risk_weighted_assets', models.DecimalField(decimal_places=2, max_digits=20)),
                (r'car_ratio', models.FloatField()),
                (r'lcr_ratio', models.FloatField()),
                (r'nsfr_ratio', models.FloatField()),
                (r'leverage_ratio', models.FloatField()),
                (r'is_compliant', models.BooleanField(default=True)),
                (r'submitted_to_ojk', models.BooleanField(default=False)),
                (r'submitted_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_basel_capital',
            },
        ),
    ]
