# Generated by Django 6.0.1 on 2026-03-14 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0008_liquidityreport_baselcapitalreport'),
        (r'workspace', '0004_servicelevelagreement_workflowinstance_workflowstep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'AuditFinding',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'audit_type', models.CharField(choices=[('internal', 'Internal Audit'), ('external', 'External Audit'), ('regulatory', 'Regulatory Examination'), ('penetration_test', 'Penetration Test'), ('iso_27001', 'ISO 27001 Audit')], max_length=50)),
                (r'finding_number', models.CharField(max_length=50, unique=True)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField()),
                (r'severity', models.CharField(choices=[('observation', 'Observation'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], max_length=20)),
                (r'recommendation', models.TextField()),
                (r'management_response', models.TextField(blank=True)),
                (r'status', models.CharField(choices=[('open', 'Open'), ('in_remediation', 'In Remediation'), ('resolved', 'Resolved'), ('accepted', 'Risk Accepted')], default='open', max_length=20)),
                (r'due_date', models.DateTimeField(null=True)),
                (r'resolved_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_audit_finding',
            },
        ),
        migrations.CreateModel(
            name=r'BlackoutPeriod',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'reason', models.CharField(max_length=255)),
                (r'affected_roles', models.JSONField(default=list)),
                (r'affected_instruments', models.JSONField(default=list)),
                (r'start_date', models.DateField()),
                (r'end_date', models.DateField()),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_blackout_period',
            },
        ),
        migrations.CreateModel(
            name=r'GDPRRequest',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'request_type', models.CharField(choices=[('access', 'Right to Access'), ('erasure', 'Right to Erasure'), ('portability', 'Data Portability'), ('rectification', 'Rectification'), ('restriction', 'Restriction'), ('objection', 'Objection')], max_length=50)),
                (r'status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='received', max_length=20)),
                (r'due_date', models.DateTimeField()),
                (r'response_data_cid', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
                (r'processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_gdpr', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gdpr_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_gdpr_request',
            },
        ),
        migrations.CreateModel(
            name=r'InsiderTradingMonitor',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'instrument', models.CharField(max_length=50)),
                (r'isin', models.CharField(blank=True, max_length=12)),
                (r'action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('short', 'Short'), ('option', 'Option')], max_length=20)),
                (r'amount', models.DecimalField(decimal_places=2, max_digits=20)),
                (r'currency', models.CharField(default='IDR', max_length=3)),
                (r'is_during_blackout', models.BooleanField(default=False)),
                (r'has_material_info', models.BooleanField(default=False)),
                (r'risk_score', models.FloatField(default=0.0)),
                (r'is_flagged', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_insider', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insider_monitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_insider_trading',
            },
        ),
    ]
