# Generated by Django 6.0.1 on 2026-03-14 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0009_auditfinding_blackoutperiod_gdprrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'CyberIncidentResponse',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'incident_id', models.CharField(max_length=50, unique=True)),
                (r'incident_type', models.CharField(choices=[('ransomware', 'Ransomware'), ('data_breach', 'Data Breach'), ('ddos', 'DDoS Attack'), ('apt', 'Advanced Persistent Threat'), ('insider', 'Insider Threat'), ('zero_day', 'Zero Day Exploit'), ('supply_chain', 'Supply Chain Attack')], max_length=50)),
                (r'severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                (r'affected_systems', models.JSONField(default=list)),
                (r'affected_users_count', models.PositiveIntegerField(default=0)),
                (r'containment_steps', models.JSONField(default=list)),
                (r'eradication_steps', models.JSONField(default=list)),
                (r'recovery_steps', models.JSONField(default=list)),
                (r'lessons_learned', models.TextField(blank=True)),
                (r'reported_to_ojk', models.BooleanField(default=False)),
                (r'reported_to_bssn', models.BooleanField(default=False)),
                (r'status', models.CharField(choices=[('detected', 'Detected'), ('contained', 'Contained'), ('eradicated', 'Eradicated'), ('recovered', 'Recovered'), ('closed', 'Closed')], default='detected', max_length=20)),
                (r'detected_at', models.DateTimeField(auto_now_add=True)),
                (r'closed_at', models.DateTimeField(blank=True, null=True)),
                (r'lead_responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_cyber_incident',
            },
        ),
        migrations.CreateModel(
            name=r'PrivacyImpactAssessment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'project_name', models.CharField(max_length=255)),
                (r'data_types', models.JSONField(default=list)),
                (r'processing_purpose', models.TextField()),
                (r'legal_basis', models.CharField(max_length=100)),
                (r'risks_identified', models.JSONField(default=list)),
                (r'mitigations', models.JSONField(default=list)),
                (r'residual_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                (r'dpo_approved', models.BooleanField(default=False)),
                (r'approved_at', models.DateTimeField(blank=True, null=True)),
                (r'review_date', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dpias', to=settings.AUTH_USER_MODEL)),
                (r'dpo_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_dpia',
            },
        ),
    ]
