# Generated by Django 6.0.1 on 2026-03-15 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0010_cyberincidentresponse_privacyimpactassessment'),
        (r'workspace', '0008_documenttemplate_githubevent_meetingnotes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'IncidentReport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField()),
                (r'incident_type', models.CharField(choices=[('bug', 'Bug'), ('outage', 'Service Outage'), ('security', 'Security Issue'), ('data_loss', 'Data Loss'), ('performance', 'Performance Issue'), ('other', 'Other')], max_length=50)),
                (r'severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                (r'status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                (r'resolved_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents_rw', to=settings.AUTH_USER_MODEL)),
                (r'reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_incident_report',
            },
        ),
        migrations.CreateModel(
            name=r'IncidentTimeline',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'action', models.TextField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='compliance.incidentreport')),
            ],
            options={
                r'db_table': 'compliance_incident_timeline',
            },
        ),
        migrations.CreateModel(
            name=r'OnCallSchedule',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'start_time', models.DateTimeField()),
                (r'end_time', models.DateTimeField()),
                (r'is_primary', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_shifts', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oncall_schedules', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_oncall_schedule',
            },
        ),
        migrations.CreateModel(
            name=r'PostMortem',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'root_cause', models.TextField()),
                (r'impact', models.TextField()),
                (r'timeline', models.TextField()),
                (r'action_items', models.JSONField(default=list)),
                (r'lessons_learned', models.TextField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_mortem', to='compliance.incidentreport')),
                (r'written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_post_mortem',
            },
        ),
        migrations.CreateModel(
            name=r'RunBook',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'category', models.CharField(choices=[('deployment', 'Deployment'), ('incident', 'Incident Response'), ('onboarding', 'Onboarding'), ('maintenance', 'Maintenance'), ('security', 'Security')], max_length=50)),
                (r'steps', models.JSONField(default=list)),
                (r'content_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'version', models.PositiveIntegerField(default=1)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runbooks', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_runbook',
            },
        ),
    ]
