# Generated by Django 6.0.1 on 2026-03-15 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0011_incidentreport_incidenttimeline_oncallschedule_and_more'),
        (r'workspace', '0009_budgettracker_budgetexpense_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'AlertRule',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'metric', models.CharField(max_length=50)),
                (r'threshold', models.FloatField()),
                (r'comparison', models.CharField(choices=[('gt', 'Greater Than'), ('lt', 'Less Than'), ('eq', 'Equal')], max_length=10)),
                (r'severity', models.CharField(default='warning', max_length=20)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_alert_rule',
            },
        ),
        migrations.CreateModel(
            name=r'AlertInstance',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'value', models.FloatField()),
                (r'is_resolved', models.BooleanField(default=False)),
                (r'resolved_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='compliance.alertrule')),
            ],
            options={
                r'db_table': 'compliance_alert_instance',
            },
        ),
        migrations.CreateModel(
            name=r'AuditExport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'export_type', models.CharField(max_length=50)),
                (r'date_from', models.DateField()),
                (r'date_to', models.DateField()),
                (r'file_cid', models.TextField(blank=True)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_exports', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_audit_export',
            },
        ),
        migrations.CreateModel(
            name=r'ComplianceChecklist',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'items', models.JSONField(default=list)),
                (r'frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                (r'last_completed', models.DateTimeField(null=True)),
                (r'next_due', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_checklist',
            },
        ),
        migrations.CreateModel(
            name=r'ComplianceChecklistRun',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'completed_items', models.JSONField(default=list)),
                (r'notes', models.TextField(blank=True)),
                (r'completed_at', models.DateTimeField(auto_now_add=True)),
                (r'checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='compliance.compliancechecklist')),
                (r'completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_checklist_run',
            },
        ),
        migrations.CreateModel(
            name=r'DataAccessRequest',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'request_type', models.CharField(choices=[('export', 'Data Export'), ('deletion', 'Data Deletion'), ('correction', 'Data Correction'), ('access', 'Data Access')], max_length=50)),
                (r'description', models.TextField()),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_at', models.DateTimeField(null=True)),
                (r'processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL)),
                (r'requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_data_request',
            },
        ),
        migrations.CreateModel(
            name=r'NotificationRule',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'trigger_type', models.CharField(max_length=50)),
                (r'conditions', models.JSONField(default=dict)),
                (r'channels', models.JSONField(default=list)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_notification_rule',
            },
        ),
        migrations.CreateModel(
            name=r'PolicyDocument',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'policy_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('security', 'Security Policy'), ('acceptable_use', 'Acceptable Use'), ('data_retention', 'Data Retention'), ('remote_work', 'Remote Work Policy')], max_length=50)),
                (r'content_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'version', models.CharField(default='1.0', max_length=20)),
                (r'effective_date', models.DateField()),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_policy',
            },
        ),
        migrations.CreateModel(
            name=r'SecurityScan',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'scan_type', models.CharField(choices=[('vulnerability', 'Vulnerability'), ('penetration', 'Penetration Test'), ('code_review', 'Code Review'), ('config_audit', 'Config Audit')], max_length=50)),
                (r'status', models.CharField(default='running', max_length=20)),
                (r'findings', models.JSONField(default=list)),
                (r'score', models.FloatField(default=0.0)),
                (r'started_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_at', models.DateTimeField(null=True)),
                (r'initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_scans', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_security_scan',
            },
        ),
        migrations.CreateModel(
            name=r'SystemLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'level', models.CharField(choices=[('DEBUG', 'DEBUG'), ('INFO', 'INFO'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                (r'service', models.CharField(max_length=50)),
                (r'message', models.TextField()),
                (r'metadata', models.JSONField(default=dict)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_system_log',
            },
        ),
        migrations.CreateModel(
            name=r'PolicyAcknowledgement',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'acknowledged_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='compliance.policydocument')),
            ],
            options={
                r'db_table': 'compliance_policy_ack',
                r'unique_together': {('policy', 'user')},
            },
        ),
    ]
