# Generated by Django 6.0.1 on 2026-03-21 04:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0012_alertrule_alertinstance_auditexport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'EmergencyAccessLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'requested_by', models.CharField(max_length=50)),
                (r'reason', models.TextField()),
                (r'approver_1', models.CharField(blank=True, max_length=50)),
                (r'approver_2', models.CharField(blank=True, max_length=50)),
                (r'approved_at', models.DateTimeField(null=True)),
                (r'target_user_id', models.CharField(max_length=50)),
                (r'access_granted', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'compliance_emergency_access',
            },
        ),
        migrations.CreateModel(
            name=r'ImmutableAuditLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(db_index=True, max_length=50)),
                (r'sender_id', models.CharField(max_length=50)),
                (r'receiver_id', models.CharField(blank=True, max_length=50)),
                (r'message_hash', models.CharField(max_length=64)),
                (r'channel', models.CharField(max_length=100)),
                (r'action', models.CharField(max_length=50)),
                (r'device_info', models.TextField(blank=True)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'prev_hash', models.CharField(max_length=64)),
                (r'chain_hash', models.CharField(max_length=64, unique=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                r'db_table': 'compliance_immutable_audit',
                r'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name=r'ChannelPolicy',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'channel_name', models.CharField(max_length=100)),
                (r'channel_type', models.CharField(choices=[('general', 'General Chat'), ('official', 'Official Instruction'), ('operational', 'Operational')], default='general', max_length=20)),
                (r'allow_self_destruct', models.BooleanField(default=True)),
                (r'retention_days', models.PositiveIntegerField(default=365)),
                (r'require_audit', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'compliance_channel_policy',
                r'unique_together': {('workspace_id', 'channel_name')},
            },
        ),
        migrations.CreateModel(
            name=r'ShamirKeyShare',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'share_index', models.PositiveSmallIntegerField()),
                (r'share_holder', models.CharField(max_length=100)),
                (r'share_holder_id', models.CharField(max_length=50)),
                (r'encrypted_share', models.TextField()),
                (r'threshold', models.PositiveSmallIntegerField(default=2)),
                (r'total_shares', models.PositiveSmallIntegerField(default=3)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'compliance_shamir_share',
                r'unique_together': {('workspace_id', 'share_index')},
            },
        ),
    ]
