# Generated by Django 6.0.1 on 2026-03-31 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'compliance', '0013_emergencyaccesslog_immutableauditlog_channelpolicy_and_more'),
        (r'workspace', '0017_apikey_appversion_geolocation_knowledgetag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'DLPRule',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'pattern', models.TextField(help_text='Regex pattern untuk deteksi data sensitif')),
                (r'data_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('nik', 'NIK'), ('account_number', 'Account Number'), ('phone', 'Phone Number'), ('custom', 'Custom')], max_length=50)),
                (r'action', models.CharField(choices=[('block', 'Block'), ('warn', 'Warn'), ('log', 'Log Only')], default='block', max_length=10)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlp_rules', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_dlp_rule',
            },
        ),
        migrations.CreateModel(
            name=r'HelpdeskTicket',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'ticket_number', models.CharField(max_length=20, unique=True)),
                (r'title', models.CharField(max_length=256)),
                (r'description', models.TextField()),
                (r'category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Network'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=20)),
                (r'priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                (r'status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                (r'channel_id', models.CharField(blank=True, help_text='Linked messaging channel', max_length=100)),
                (r'resolved_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_helpdesk_ticket',
                r'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name=r'HelpdeskComment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'content', models.TextField()),
                (r'is_internal', models.BooleanField(default=False, help_text='Internal IT note, tidak terlihat user')),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='compliance.helpdeskticket')),
            ],
            options={
                r'db_table': 'compliance_helpdesk_comment',
            },
        ),
        migrations.CreateModel(
            name=r'InformationBarrier',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'description', models.TextField(blank=True)),
                (r'blocked_departments', models.JSONField(default=list, help_text='Pasangan divisi yang diblokir')),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_barriers', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_info_barrier',
            },
        ),
        migrations.CreateModel(
            name=r'InstitutionBadge',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'institution_name', models.CharField(max_length=200)),
                (r'institution_code', models.CharField(help_text='Kode bank BI', max_length=20, unique=True)),
                (r'verified_by', models.CharField(help_text='OJK/BI verifier name', max_length=100)),
                (r'verified_at', models.DateTimeField()),
                (r'badge_level', models.CharField(choices=[('verified', 'Verified'), ('premium', 'Premium Institution'), ('regulator', 'Regulator')], default='verified', max_length=20)),
                (r'is_active', models.BooleanField(default=True)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_badge', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_institution_badge',
            },
        ),
        migrations.CreateModel(
            name=r'OJKIncidentReport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'incident_type', models.CharField(max_length=100)),
                (r'severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                (r'description', models.TextField()),
                (r'affected_systems', models.JSONField(default=list)),
                (r'affected_users_count', models.PositiveIntegerField(default=0)),
                (r'detected_at', models.DateTimeField()),
                (r'status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='draft', max_length=20)),
                (r'ojk_reference_number', models.CharField(blank=True, max_length=100)),
                (r'submitted_at', models.DateTimeField(blank=True, null=True)),
                (r'deadline_at', models.DateTimeField(help_text='24 jam sejak detected_at')),
                (r'auto_submitted', models.BooleanField(default=False)),
                (r'metadata', models.JSONField(default=dict)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojk_reports', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_ojk_incident',
                r'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name=r'RemoteWipeRequest',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'reason', models.TextField()),
                (r'device_token', models.CharField(blank=True, help_text='Target device token', max_length=256)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                (r'executed_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_wipes', to=settings.AUTH_USER_MODEL)),
                (r'target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wipe_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'compliance_remote_wipe',
            },
        ),
        migrations.CreateModel(
            name=r'SecureFileLink',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'filename', models.CharField(max_length=256)),
                (r'file_size_bytes', models.BigIntegerField(default=0)),
                (r'ipfs_cid', models.CharField(blank=True, max_length=128)),
                (r'token_hash', models.CharField(max_length=256, unique=True)),
                (r'password_hash', models.CharField(blank=True, max_length=256)),
                (r'expires_at', models.DateTimeField()),
                (r'max_downloads', models.PositiveIntegerField(default=1)),
                (r'download_count', models.PositiveIntegerField(default=0)),
                (r'is_active', models.BooleanField(default=True)),
                (r'access_log', models.JSONField(default=list)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_links', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'compliance_secure_file_link',
            },
        ),
    ]
