# Generated by Django 6.0.1 on 2026-03-31 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_emergencyaccesslog_immutableauditlog_channelpolicy_and_more'),
        ('workspace', '0017_apikey_appversion_geolocation_knowledgetag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DLPRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pattern', models.TextField(help_text='Regex pattern untuk deteksi data sensitif')),
                ('data_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('nik', 'NIK'), ('account_number', 'Account Number'), ('phone', 'Phone Number'), ('custom', 'Custom')], max_length=50)),
                ('action', models.CharField(choices=[('block', 'Block'), ('warn', 'Warn'), ('log', 'Log Only')], default='block', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlp_rules', to='workspace.workspace')),
            ],
            options={
                'db_table': 'compliance_dlp_rule',
            },
        ),
        migrations.CreateModel(
            name='HelpdeskTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('network', 'Network'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('channel_id', models.CharField(blank=True, help_text='Linked messaging channel', max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='workspace.workspace')),
            ],
            options={
                'db_table': 'compliance_helpdesk_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpdeskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal IT note, tidak terlihat user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='compliance.helpdeskticket')),
            ],
            options={
                'db_table': 'compliance_helpdesk_comment',
            },
        ),
        migrations.CreateModel(
            name='InformationBarrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('blocked_departments', models.JSONField(default=list, help_text='Pasangan divisi yang diblokir')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_barriers', to='workspace.workspace')),
            ],
            options={
                'db_table': 'compliance_info_barrier',
            },
        ),
        migrations.CreateModel(
            name='InstitutionBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=200)),
                ('institution_code', models.CharField(help_text='Kode bank BI', max_length=20, unique=True)),
                ('verified_by', models.CharField(help_text='OJK/BI verifier name', max_length=100)),
                ('verified_at', models.DateTimeField()),
                ('badge_level', models.CharField(choices=[('verified', 'Verified'), ('premium', 'Premium Institution'), ('regulator', 'Regulator')], default='verified', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_badge', to='workspace.workspace')),
            ],
            options={
                'db_table': 'compliance_institution_badge',
            },
        ),
        migrations.CreateModel(
            name='OJKIncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('affected_systems', models.JSONField(default=list)),
                ('affected_users_count', models.PositiveIntegerField(default=0)),
                ('detected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('ojk_reference_number', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(help_text='24 jam sejak detected_at')),
                ('auto_submitted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojk_reports', to='workspace.workspace')),
            ],
            options={
                'db_table': 'compliance_ojk_incident',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteWipeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('device_token', models.CharField(blank=True, help_text='Target device token', max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_wipes', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wipe_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_remote_wipe',
            },
        ),
        migrations.CreateModel(
            name='SecureFileLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=256)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('ipfs_cid', models.CharField(blank=True, max_length=128)),
                ('token_hash', models.CharField(max_length=256, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=256)),
                ('expires_at', models.DateTimeField()),
                ('max_downloads', models.PositiveIntegerField(default=1)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('access_log', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_links', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                'db_table': 'compliance_secure_file_link',
            },
        ),
    ]
