# Generated by Django 6.0.4 on 2026-04-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0014_dlprule_helpdeskticket_helpdeskcomment_and_more'),
        ('compliance', '0_medium_fix_migration'),
    ]

    operations = [
    ]
