# Generated by Django 6.0.1 on 2026-03-14 01:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (r'auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'LoginSession',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'refresh_jti', models.CharField(db_index=True, max_length=255, unique=True)),
                (r'ip_address', models.GenericIPAddressField()),
                (r'user_agent', models.CharField(blank=True, max_length=512)),
                (r'device_fingerprint', models.CharField(blank=True, max_length=128)),
                (r'country_code', models.CharField(blank=True, max_length=4)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'last_seen', models.DateTimeField(auto_now=True)),
                (r'expires_at', models.DateTimeField()),
                (r'is_revoked', models.BooleanField(default=False)),
                (r'revoked_reason', models.CharField(blank=True, max_length=64)),
            ],
            options={
                r'db_table': 'users_login_session',
            },
        ),
        migrations.CreateModel(
            name=r'MFADevice',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'device_type', models.CharField(choices=[('totp', 'TOTP (Authenticator App)'), ('fido2', 'FIDO2 / WebAuthn'), ('sms', 'SMS OTP'), ('hardware_key', 'USB Hardware Key'), ('backup', 'Backup Codes')], max_length=16)),
                (r'name', models.CharField(help_text="User-visible label e.g. 'iPhone 15'", max_length=64)),
                (r'secret_encrypted', models.TextField(help_text='AES-GCM encrypted TOTP secret or FIDO2 credential')),
                (r'is_primary', models.BooleanField(default=False)),
                (r'is_confirmed', models.BooleanField(default=False)),
                (r'last_used', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'failure_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                r'db_table': 'users_mfa_device',
                r'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name=r'PasswordHistory',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'password_hash', models.CharField(max_length=256)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'users_password_history',
                r'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name=r'UserProfile',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'phone_encrypted', models.TextField(blank=True, help_text='AES-256-GCM encrypted phone')),
                (r'title', models.CharField(blank=True, max_length=64)),
                (r'bio_encrypted', models.TextField(blank=True)),
                (r'timezone', models.CharField(default='UTC', max_length=64)),
                (r'locale', models.CharField(default='en-US', max_length=16)),
                (r'notification_prefs', models.JSONField(default=dict)),
                (r'theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=16)),
            ],
            options={
                r'db_table': 'users_profile',
            },
        ),
        migrations.CreateModel(
            name=r'UserPublicKey',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'key_type', models.CharField(choices=[('rsa_4096', 'RSA-4096'), ('ec_p384', 'ECDH P-384'), ('kyber_1024', 'Kyber-1024 (PQC KEM)'), ('ml_dsa_65', 'Dilithium3 (PQC Sig)')], max_length=16)),
                (r'public_key_b64', models.TextField(help_text='Base64-encoded DER/raw key')),
                (r'fingerprint', models.CharField(db_index=True, max_length=128)),
                (r'is_current', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'rotated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                r'db_table': 'users_public_key',
            },
        ),
        migrations.CreateModel(
            name=r'UserRole',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'name', models.CharField(choices=[('super_admin', 'Super Administrator'), ('compliance_officer', 'Compliance Officer'), ('branch_manager', 'Branch Manager'), ('senior_analyst', 'Senior Analyst'), ('analyst', 'Analyst'), ('trader', 'Trader'), ('support', 'Support Staff'), ('auditor', 'Auditor (Read-Only)'), ('external_counsel', 'External Counsel'), ('guest', 'Guest')], max_length=32, unique=True)),
                (r'display_name', models.CharField(max_length=64)),
                (r'permissions', models.JSONField(default=list, help_text='List of permission codenames')),
                (r'max_clearance', models.PositiveSmallIntegerField(default=3)),
                (r'can_access_vault', models.BooleanField(default=False)),
                (r'can_export_messages', models.BooleanField(default=False)),
            ],
            options={
                r'db_table': 'users_role',
            },
        ),
        migrations.CreateModel(
            name=r'UserRoleAssignment',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'granted_at', models.DateTimeField(auto_now_add=True)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'is_active', models.BooleanField(default=True)),
            ],
            options={
                r'db_table': 'users_role_assignment',
            },
        ),
        migrations.CreateModel(
            name=r'BankUser',
            fields=[
                (r'password', models.CharField(max_length=128, verbose_name='password')),
                (r'last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                (r'is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                (r'username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                (r'first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                (r'last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                (r'email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                (r'is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                (r'is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                (r'date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(db_index=True, max_length=32, unique=True)),
                (r'department', models.CharField(blank=True, max_length=128)),
                (r'clearance_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1, help_text='1=Basic, 5=Executive. Controls vault access.')),
                (r'is_mfa_enforced', models.BooleanField(default=True)),
                (r'is_mfa_verified', models.BooleanField(default=False)),
                (r'pqc_public_key_kyber', models.TextField(blank=True, help_text='Kyber-1024 public key (base64)')),
                (r'pqc_public_key_dilithium', models.TextField(blank=True, help_text='Dilithium3 verify key (base64)')),
                (r'avatar_ipfs_cid', models.CharField(blank=True, max_length=128)),
                (r'last_ip', models.GenericIPAddressField(blank=True, null=True)),
                (r'last_active', models.DateTimeField(blank=True, null=True)),
                (r'is_locked', models.BooleanField(default=False, help_text='Admin/Axes hard lock')),
                (r'deactivated_at', models.DateTimeField(blank=True, null=True)),
                (r'groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                (r'user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                r'verbose_name': 'Bank User',
                r'verbose_name_plural': 'Bank Users',
                r'db_table': 'users_bankuser',
            },
            managers=[
                (r'objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name=r'APIKey',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=64)),
                (r'key_prefix', models.CharField(db_index=True, max_length=12)),
                (r'key_hash', models.CharField(max_length=256, unique=True)),
                (r'scopes', models.JSONField(default=list, help_text="e.g. ['read:messages', 'write:messages']")),
                (r'is_active', models.BooleanField(default=True)),
                (r'last_used', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_api_key',
            },
        ),
        migrations.CreateModel(
            name=r'DeviceFingerprint',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'fingerprint_hash', models.CharField(db_index=True, max_length=128)),
                (r'device_label', models.CharField(blank=True, max_length=128)),
                (r'trust_level', models.PositiveSmallIntegerField(choices=[(1, 'Partial'), (2, 'Full')], default=1)),
                (r'first_seen', models.DateTimeField(auto_now_add=True)),
                (r'last_seen', models.DateTimeField(auto_now=True)),
                (r'is_blocked', models.BooleanField(default=False)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_device_fingerprint',
            },
        ),
        migrations.CreateModel(
            name=r'HistoricalBankUser',
            fields=[
                (r'password', models.CharField(max_length=128, verbose_name='password')),
                (r'last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                (r'is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                (r'username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                (r'first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                (r'last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                (r'email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                (r'is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                (r'is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                (r'date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                (r'id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (r'employee_id', models.CharField(db_index=True, max_length=32)),
                (r'department', models.CharField(blank=True, max_length=128)),
                (r'clearance_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=1, help_text='1=Basic, 5=Executive. Controls vault access.')),
                (r'is_mfa_enforced', models.BooleanField(default=True)),
                (r'is_mfa_verified', models.BooleanField(default=False)),
                (r'pqc_public_key_kyber', models.TextField(blank=True, help_text='Kyber-1024 public key (base64)')),
                (r'pqc_public_key_dilithium', models.TextField(blank=True, help_text='Dilithium3 verify key (base64)')),
                (r'avatar_ipfs_cid', models.CharField(blank=True, max_length=128)),
                (r'last_ip', models.GenericIPAddressField(blank=True, null=True)),
                (r'last_active', models.DateTimeField(blank=True, null=True)),
                (r'is_locked', models.BooleanField(default=False, help_text='Admin/Axes hard lock')),
                (r'deactivated_at', models.DateTimeField(blank=True, null=True)),
                (r'history_id', models.AutoField(primary_key=True, serialize=False)),
                (r'history_date', models.DateTimeField(db_index=True)),
                (r'history_change_reason', models.CharField(max_length=100, null=True)),
                (r'history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                (r'history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'verbose_name': 'historical Bank User',
                r'verbose_name_plural': 'historical Bank Users',
                r'ordering': ('-history_date', '-history_id'),
                r'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name=r'InviteToken',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'email', models.EmailField(max_length=254)),
                (r'token_hash', models.CharField(max_length=256, unique=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'expires_at', models.DateTimeField()),
                (r'used_at', models.DateTimeField(blank=True, null=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'used_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_invite_token',
            },
        ),
    ]
