# Generated by Django 6.0.1 on 2026-03-14 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (r'users', '0001_initial'),
        (r'workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name=r'invitetoken',
            name=r'workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'invites', to='workspace.workspace'),
        ),
        migrations.AddField(
            model_name=r'loginsession',
            name=r'user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'mfadevice',
            name=r'user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'mfa_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'passwordhistory',
            name=r'user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'userprofile',
            name=r'user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name=r'profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'userpublickey',
            name=r'user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'public_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'invitetoken',
            name=r'role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=r'users.userrole'),
        ),
        migrations.AddField(
            model_name=r'userroleassignment',
            name=r'granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name=r'granted_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'userroleassignment',
            name=r'role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name=r'assignments', to='users.userrole'),
        ),
        migrations.AddField(
            model_name=r'userroleassignment',
            name=r'user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'role_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name=r'userroleassignment',
            name=r'workspace',
            field=models.ForeignKey(blank=True, help_text=r'Null = global role', null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace'),
        ),
        migrations.AddIndex(
            model_name=r'bankuser',
            index=models.Index(fields=[r'employee_id'], name='users_banku_employe_d26e15_idx'),
        ),
        migrations.AddIndex(
            model_name=r'bankuser',
            index=models.Index(fields=[r'clearance_level'], name='users_banku_clearan_325cdb_idx'),
        ),
        migrations.AddIndex(
            model_name=r'bankuser',
            index=models.Index(fields=[r'last_active'], name='users_banku_last_ac_99d6f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name=r'devicefingerprint',
            unique_together={(r'user', 'fingerprint_hash')},
        ),
        migrations.AddIndex(
            model_name=r'loginsession',
            index=models.Index(fields=[r'user', 'is_revoked'], name='users_login_user_id_d02f0c_idx'),
        ),
        migrations.AddIndex(
            model_name=r'loginsession',
            index=models.Index(fields=[r'expires_at'], name='users_login_expires_18538e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name=r'userpublickey',
            unique_together={(r'user', 'key_type', 'is_current')},
        ),
        migrations.AddIndex(
            model_name=r'userroleassignment',
            index=models.Index(fields=[r'user', 'is_active'], name='users_role__user_id_8bc4ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name=r'userroleassignment',
            unique_together={(r'user', 'role', 'workspace')},
        ),
    ]
