# Generated by Django 6.0.1 on 2026-03-14 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'users', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'UserActivityLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'action', models.CharField(max_length=100)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'user_agent', models.TextField(blank=True)),
                (r'metadata', models.JSONField(default=dict)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_activity_log',
            },
        ),
        migrations.CreateModel(
            name=r'UserBadge',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'badge_type', models.CharField(max_length=50)),
                (r'awarded_at', models.DateTimeField(auto_now_add=True)),
                (r'awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_badge',
            },
        ),
        migrations.CreateModel(
            name=r'UserCustomStatus',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'text', models.CharField(blank=True, max_length=100)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_custom_status',
            },
        ),
        migrations.CreateModel(
            name=r'UserDevice',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'device_name', models.CharField(max_length=100)),
                (r'device_type', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop'), ('tablet', 'Tablet')], max_length=20)),
                (r'device_fingerprint', models.CharField(max_length=255, unique=True)),
                (r'push_token', models.TextField(blank=True)),
                (r'is_trusted', models.BooleanField(default=False)),
                (r'last_active', models.DateTimeField(auto_now=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_device',
            },
        ),
        migrations.CreateModel(
            name=r'UserNotification',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'body', models.TextField()),
                (r'notification_type', models.CharField(max_length=50)),
                (r'is_read', models.BooleanField(default=False)),
                (r'data', models.JSONField(default=dict)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_notification',
            },
        ),
        migrations.CreateModel(
            name=r'UserPreference',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'theme', models.CharField(default='dark', max_length=20)),
                (r'language', models.CharField(default='en', max_length=10)),
                (r'notification_sound', models.BooleanField(default=True)),
                (r'compact_mode', models.BooleanField(default=False)),
                (r'settings', models.JSONField(default=dict)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_preference',
            },
        ),
        migrations.CreateModel(
            name=r'UserBlocked',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'reason', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                (r'blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_blocked',
                r'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name=r'UserContact',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'nickname', models.CharField(blank=True, max_length=100)),
                (r'is_favourite', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_of', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_contact',
                r'unique_together': {('user', 'contact')},
            },
        ),
    ]
