# Generated by Django 6.0.1 on 2026-03-14 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'users', '0003_useractivitylog_userbadge_usercustomstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'CurrencyRate',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'base_currency', models.CharField(max_length=3)),
                (r'target_currency', models.CharField(max_length=3)),
                (r'rate', models.DecimalField(decimal_places=8, max_digits=20)),
                (r'source', models.CharField(default='BI', max_length=50)),
                (r'is_active', models.BooleanField(default=True)),
                (r'effective_at', models.DateTimeField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'users_currency_rate',
                r'unique_together': {('base_currency', 'target_currency', 'effective_at')},
            },
        ),
        migrations.CreateModel(
            name=r'RBACPolicy',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100, unique=True)),
                (r'description', models.TextField(blank=True)),
                (r'permissions', models.JSONField(default=list)),
                (r'resources', models.JSONField(default=list)),
                (r'conditions', models.JSONField(default=dict)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_rbac_policy',
            },
        ),
        migrations.CreateModel(
            name=r'RBACPolicyAssignment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_policies', to=settings.AUTH_USER_MODEL)),
                (r'policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.rbacpolicy')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_rbac_assignment',
                r'unique_together': {('user', 'policy')},
            },
        ),
    ]
