# Generated by Django 6.0.1 on 2026-03-14 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'users', '0004_currencyrate_rbacpolicy_rbacpolicyassignment'),
        (r'workspace', '0002_bankingchannel_compliancecheckpoint_dealroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'AccessTimeRestriction',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'allowed_days', models.JSONField(default=list)),
                (r'allowed_hours_start', models.TimeField()),
                (r'allowed_hours_end', models.TimeField()),
                (r'timezone', models.CharField(default='Asia/Jakarta', max_length=50)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_restrictions', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_restrictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_access_time_restriction',
            },
        ),
        migrations.CreateModel(
            name=r'BiometricAuth',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'biometric_type', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face', 'Face Recognition'), ('voice', 'Voice Print'), ('iris', 'Iris Scan')], max_length=30)),
                (r'template_hash', models.CharField(max_length=64)),
                (r'encrypted_template_b64', models.TextField()),
                (r'is_active', models.BooleanField(default=True)),
                (r'last_used', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_biometric_auth',
            },
        ),
        migrations.CreateModel(
            name=r'DataClassification',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'resource_type', models.CharField(max_length=50)),
                (r'resource_id', models.CharField(max_length=50)),
                (r'classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('restricted', 'Restricted'), ('top_secret', 'Top Secret')], max_length=30)),
                (r'classified_at', models.DateTimeField(auto_now_add=True)),
                (r'review_date', models.DateTimeField(blank=True, null=True)),
                (r'classified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'users_data_classification',
            },
        ),
        migrations.CreateModel(
            name=r'IPWhitelist',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'ip_address', models.GenericIPAddressField()),
                (r'ip_range', models.CharField(blank=True, max_length=50)),
                (r'label', models.CharField(blank=True, max_length=100)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_whitelists', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_whitelist', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'users_ip_whitelist',
            },
        ),
        migrations.CreateModel(
            name=r'SecurityIncident',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'incident_number', models.CharField(max_length=50, unique=True)),
                (r'incident_type', models.CharField(choices=[('unauthorized_access', 'Unauthorized Access'), ('data_breach', 'Data Breach'), ('brute_force', 'Brute Force'), ('insider_threat', 'Insider Threat'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('ddos', 'DDoS')], max_length=50)),
                (r'severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                (r'description', models.TextField()),
                (r'remediation', models.TextField(blank=True)),
                (r'status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved')], default='open', max_length=20)),
                (r'detected_at', models.DateTimeField(auto_now_add=True)),
                (r'resolved_at', models.DateTimeField(blank=True, null=True)),
                (r'affected_users', models.ManyToManyField(blank=True, related_name='security_incidents', to=settings.AUTH_USER_MODEL)),
                (r'assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_security_incident',
            },
        ),
    ]
