# Generated by Django 6.0.1 on 2026-03-14 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'users', '0005_accesstimerestriction_biometricauth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'EmployeeOffboarding',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'reason', models.CharField(choices=[('resignation', 'Resignation'), ('termination', 'Termination'), ('retirement', 'Retirement'), ('transfer', 'Transfer')], max_length=50)),
                (r'access_revoked', models.BooleanField(default=False)),
                (r'keys_rotated', models.BooleanField(default=False)),
                (r'data_archived', models.BooleanField(default=False)),
                (r'equipment_returned', models.BooleanField(default=False)),
                (r'exit_interview_done', models.BooleanField(default=False)),
                (r'last_day', models.DateField(blank=True, null=True)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_offboardings', to=settings.AUTH_USER_MODEL)),
                (r'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_employee_offboarding',
            },
        ),
        migrations.CreateModel(
            name=r'EmployeeOnboarding',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'department', models.CharField(max_length=100)),
                (r'position', models.CharField(max_length=100)),
                (r'steps_completed', models.JSONField(default=list)),
                (r'background_check_passed', models.BooleanField(default=False)),
                (r'nda_signed', models.BooleanField(default=False)),
                (r'security_training_done', models.BooleanField(default=False)),
                (r'systems_access_granted', models.BooleanField(default=False)),
                (r'is_complete', models.BooleanField(default=False)),
                (r'start_date', models.DateField(blank=True, null=True)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_onboardings', to=settings.AUTH_USER_MODEL)),
                (r'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_employee_onboarding',
            },
        ),
        migrations.CreateModel(
            name=r'TrainingRecord',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'training_type', models.CharField(choices=[('aml_awareness', 'AML Awareness'), ('data_privacy', 'Data Privacy'), ('cybersecurity', 'Cybersecurity'), ('code_of_conduct', 'Code of Conduct'), ('insider_trading', 'Insider Trading Policy'), ('gdpr', 'GDPR Compliance'), ('iso27001', 'ISO 27001')], max_length=100)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                (r'score', models.FloatField(blank=True, null=True)),
                (r'passed', models.BooleanField(default=False)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_training_record',
            },
        ),
        migrations.CreateModel(
            name=r'VPNSession',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'vpn_ip', models.GenericIPAddressField()),
                (r'real_ip', models.GenericIPAddressField(null=True)),
                (r'protocol', models.CharField(choices=[('wireguard', 'WireGuard'), ('openvpn', 'OpenVPN'), ('ipsec', 'IPSec')], default='wireguard', max_length=20)),
                (r'is_active', models.BooleanField(default=True)),
                (r'connected_at', models.DateTimeField(auto_now_add=True)),
                (r'disconnected_at', models.DateTimeField(blank=True, null=True)),
                (r'bytes_sent', models.BigIntegerField(default=0)),
                (r'bytes_received', models.BigIntegerField(default=0)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_vpn_session',
            },
        ),
        migrations.CreateModel(
            name=r'ZeroTrustPolicy',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'description', models.TextField(blank=True)),
                (r'conditions', models.JSONField(default=dict)),
                (r'actions', models.JSONField(default=dict)),
                (r'priority', models.PositiveIntegerField(default=100)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_zero_trust_policy',
                r'ordering': ['priority'],
            },
        ),
    ]
