# Generated by Django 6.0.1 on 2026-03-14 07:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'users', '0006_employeeoffboarding_employeeonboarding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'AdaptiveAuthPolicy',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'trigger_conditions', models.JSONField(default=dict)),
                (r'auth_requirements', models.JSONField(default=list)),
                (r'risk_threshold', models.FloatField(default=0.7)),
                (r'action', models.CharField(choices=[('allow', 'Allow'), ('step_up_mfa', 'Step-Up MFA'), ('block', 'Block'), ('notify', 'Notify Only'), ('challenge', 'Challenge')], default='step_up_mfa', max_length=50)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_adaptive_auth_policy',
            },
        ),
        migrations.CreateModel(
            name=r'PrivilegedAccessManagement',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'resource', models.CharField(max_length=100)),
                (r'access_type', models.CharField(choices=[('database', 'Database'), ('server', 'Server'), ('network', 'Network Device'), ('application', 'Application'), ('cloud', 'Cloud Console')], max_length=50)),
                (r'justification', models.TextField()),
                (r'session_recording_cid', models.TextField(blank=True)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                (r'expires_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
                (r'approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pam_approvals', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_pam_session',
            },
        ),
        migrations.CreateModel(
            name=r'SessionRiskScore',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'session_id', models.CharField(max_length=100)),
                (r'risk_score', models.FloatField(default=0.0)),
                (r'risk_factors', models.JSONField(default=dict)),
                (r'action_taken', models.CharField(blank=True, max_length=50)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'device_fingerprint', models.CharField(blank=True, max_length=255)),
                (r'location', models.CharField(blank=True, max_length=100)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_session_risk_score',
            },
        ),
    ]
