# Generated by Django 6.0.1 on 2026-03-15 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'users', '0007_adaptiveauthpolicy_privilegedaccessmanagement_and_more'),
        (r'workspace', '0008_documenttemplate_githubevent_meetingnotes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'TeamMembership',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'description', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
                (r'team_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'users_team',
            },
        ),
        migrations.CreateModel(
            name=r'UserCertification',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=255)),
                (r'issuer', models.CharField(max_length=100)),
                (r'credential_id', models.CharField(blank=True, max_length=100)),
                (r'issued_date', models.DateField()),
                (r'expiry_date', models.DateField(blank=True, null=True)),
                (r'certificate_cid', models.TextField(blank=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_certification',
            },
        ),
        migrations.CreateModel(
            name=r'UserFeedback',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'feedback_type', models.CharField(choices=[('praise', 'Praise'), ('suggestion', 'Suggestion'), ('constructive', 'Constructive')], max_length=20)),
                (r'content_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'is_anonymous', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                (r'to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_feedback',
            },
        ),
        migrations.CreateModel(
            name=r'UserGoal',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'goal_type', models.CharField(choices=[('skill', 'Skill Development'), ('career', 'Career Growth'), ('project', 'Project Goal'), ('personal', 'Personal')], max_length=20)),
                (r'progress', models.FloatField(default=0.0)),
                (r'due_date', models.DateField(blank=True, null=True)),
                (r'is_completed', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_goal',
            },
        ),
        migrations.CreateModel(
            name=r'UserPerformanceReview',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'period', models.CharField(max_length=20)),
                (r'overall_score', models.FloatField(default=0.0)),
                (r'strengths', models.TextField(blank=True)),
                (r'improvements', models.TextField(blank=True)),
                (r'goals_next_period', models.TextField(blank=True)),
                (r'is_acknowledged', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_performance_review',
            },
        ),
        migrations.CreateModel(
            name=r'UserAvailability',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'day_of_week', models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                (r'start_time', models.TimeField()),
                (r'end_time', models.TimeField()),
                (r'timezone', models.CharField(default='Asia/Jakarta', max_length=50)),
                (r'is_active', models.BooleanField(default=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_availability',
                r'unique_together': {('user', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name=r'UserSkill',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'skill_name', models.CharField(max_length=100)),
                (r'proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                (r'years_experience', models.PositiveSmallIntegerField(default=0)),
                (r'is_verified', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_skill',
                r'unique_together': {('user', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name=r'UserWorkload',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'week_start', models.DateField()),
                (r'planned_hours', models.FloatField(default=40.0)),
                (r'actual_hours', models.FloatField(default=0.0)),
                (r'task_count', models.PositiveIntegerField(default=0)),
                (r'completed_count', models.PositiveIntegerField(default=0)),
                (r'workload_score', models.FloatField(default=0.0)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_workload',
                r'unique_together': {('user', 'week_start')},
            },
        ),
    ]
