# Generated by Django 6.0.1 on 2026-03-15 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'users', '0008_teammembership_usercertification_userfeedback_and_more'),
        (r'workspace', '0009_budgettracker_budgetexpense_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'Payslip',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'period', models.CharField(max_length=20)),
                (r'gross_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'net_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'payslip_cid', models.TextField(blank=True)),
                (r'is_paid', models.BooleanField(default=False)),
                (r'paid_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_payslip',
            },
        ),
        migrations.CreateModel(
            name=r'UserEducation',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'institution', models.CharField(max_length=255)),
                (r'degree', models.CharField(max_length=100)),
                (r'field_of_study', models.CharField(max_length=100)),
                (r'start_year', models.PositiveSmallIntegerField()),
                (r'end_year', models.PositiveSmallIntegerField(null=True)),
                (r'is_current', models.BooleanField(default=False)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_education',
            },
        ),
        migrations.CreateModel(
            name=r'UserPortfolio',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'url', models.URLField(blank=True)),
                (r'file_cid', models.TextField(blank=True)),
                (r'tags', models.JSONField(default=list)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_portfolio',
            },
        ),
        migrations.CreateModel(
            name=r'UserReward',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'reward_type', models.CharField(choices=[('kudos', 'Kudos'), ('star', 'Star Employee'), ('innovation', 'Innovation Award'), ('teamwork', 'Teamwork Award')], max_length=50)),
                (r'points', models.PositiveIntegerField(default=0)),
                (r'message', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rewards_given', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_reward',
            },
        ),
        migrations.CreateModel(
            name=r'UserTimeOff',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick'), ('personal', 'Personal'), ('parental', 'Parental'), ('unpaid', 'Unpaid')], max_length=20)),
                (r'start_date', models.DateField()),
                (r'end_date', models.DateField()),
                (r'reason', models.TextField(blank=True)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_time_off',
            },
        ),
        migrations.CreateModel(
            name=r'UserWorkHistory',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'company', models.CharField(max_length=255)),
                (r'position', models.CharField(max_length=100)),
                (r'description', models.TextField(blank=True)),
                (r'start_date', models.DateField()),
                (r'end_date', models.DateField(null=True)),
                (r'is_current', models.BooleanField(default=False)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_work_history',
            },
        ),
        migrations.CreateModel(
            name=r'UserAnalytics',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'date', models.DateField()),
                (r'messages_sent', models.PositiveIntegerField(default=0)),
                (r'tasks_completed', models.PositiveIntegerField(default=0)),
                (r'meeting_minutes', models.PositiveIntegerField(default=0)),
                (r'focus_minutes', models.PositiveIntegerField(default=0)),
                (r'login_count', models.PositiveIntegerField(default=0)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_analytics',
                r'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name=r'UserLanguage',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'language', models.CharField(max_length=50)),
                (r'proficiency', models.CharField(choices=[('basic', 'Basic'), ('conversational', 'Conversational'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=20)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_language',
                r'unique_together': {('user', 'language')},
            },
        ),
        migrations.CreateModel(
            name=r'UserLeaveBalance',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'year', models.PositiveSmallIntegerField()),
                (r'annual_total', models.FloatField(default=12.0)),
                (r'annual_used', models.FloatField(default=0.0)),
                (r'sick_total', models.FloatField(default=12.0)),
                (r'sick_used', models.FloatField(default=0.0)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_leave_balance',
                r'unique_together': {('user', 'year')},
            },
        ),
        migrations.CreateModel(
            name=r'UserMentor',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'focus_areas', models.JSONField(default=list)),
                (r'meeting_frequency', models.CharField(default='weekly', max_length=20)),
                (r'is_active', models.BooleanField(default=True)),
                (r'started_at', models.DateTimeField(auto_now_add=True)),
                (r'mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to=settings.AUTH_USER_MODEL)),
                (r'mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'users_mentor',
                r'unique_together': {('mentor', 'mentee')},
            },
        ),
    ]
