# Generated by Django 6.0.1 on 2026-03-15 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'users', '0009_payslip_usereducation_userportfolio_userreward_and_more'),
        (r'workspace', '0010_automation_automationlog_customfield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'UserActivity',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'activity_type', models.CharField(max_length=50)),
                (r'description', models.TextField()),
                (r'metadata', models.JSONField(default=dict)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_activity',
            },
        ),
        migrations.CreateModel(
            name=r'UserEmailPreference',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'mentions', models.BooleanField(default=True)),
                (r'direct_messages', models.BooleanField(default=True)),
                (r'task_assignments', models.BooleanField(default=True)),
                (r'weekly_digest', models.BooleanField(default=True)),
                (r'security_alerts', models.BooleanField(default=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_email_pref',
            },
        ),
        migrations.CreateModel(
            name=r'UserPushToken',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'token', models.TextField(unique=True)),
                (r'platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_push_token',
            },
        ),
        migrations.CreateModel(
            name=r'UserSavedItem',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'item_type', models.CharField(choices=[('message', 'Message'), ('file', 'File'), ('task', 'Task'), ('wiki', 'Wiki Page')], max_length=20)),
                (r'item_id', models.CharField(max_length=50)),
                (r'note', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_saved_item',
            },
        ),
        migrations.CreateModel(
            name=r'UserSearchHistory',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'query', models.CharField(max_length=255)),
                (r'result_count', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_search_history',
            },
        ),
        migrations.CreateModel(
            name=r'UserShortcut',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'shortcut_type', models.CharField(choices=[('channel', 'Channel'), ('dm', 'Direct Message'), ('file', 'File'), ('task', 'Task')], max_length=20)),
                (r'target_id', models.CharField(max_length=50)),
                (r'label', models.CharField(max_length=100)),
                (r'order', models.PositiveSmallIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_shortcut',
            },
        ),
        migrations.CreateModel(
            name=r'UserStreak',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'current_streak', models.PositiveIntegerField(default=0)),
                (r'longest_streak', models.PositiveIntegerField(default=0)),
                (r'last_active', models.DateField(null=True)),
                (r'total_active_days', models.PositiveIntegerField(default=0)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_streak',
            },
        ),
        migrations.CreateModel(
            name=r'UserTheme',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'mode', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='dark', max_length=10)),
                (r'accent_color', models.CharField(default='#6366f1', max_length=7)),
                (r'font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                (r'compact_mode', models.BooleanField(default=False)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_theme',
            },
        ),
        migrations.CreateModel(
            name=r'UserAchievement',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'achievement_type', models.CharField(choices=[('first_message', 'First Message'), ('100_messages', '100 Messages'), ('task_master', 'Task Master'), ('early_bird', 'Early Bird'), ('night_owl', 'Night Owl'), ('helper', 'Team Helper')], max_length=50)),
                (r'earned_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_achievement',
                r'unique_together': {('user', 'achievement_type')},
            },
        ),
        migrations.CreateModel(
            name=r'UserFollower',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                (r'following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_follower',
                r'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name=r'UserReadStatus',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'last_read_message_id', models.CharField(blank=True, max_length=50)),
                (r'last_read_at', models.DateTimeField(auto_now=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.channel')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'users_read_status',
                r'unique_together': {('user', 'channel')},
            },
        ),
    ]
