# Generated by Django 6.0.1 on 2026-03-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'users', '0010_useractivity_useremailpreference_userpushtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name=r'invitetoken',
            name=r'expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name=r'loginsession',
            name=r'expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name=r'privilegedaccessmanagement',
            name=r'expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
