# Generated by Django 6.0.1 on 2026-03-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'users', '0011_alter_invitetoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name=r'loginsession',
            name=r'refresh_jti',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, unique=True),
        ),
    ]
