# Generated by Django 6.0.1 on 2026-03-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'auth', '0012_alter_user_first_name_max_length'),
        (r'users', '0012_alter_loginsession_refresh_jti'),
    ]

    operations = [
        migrations.AlterField(
            model_name=r'bankuser',
            name=r'groups',
            field=models.ManyToManyField(blank=True, related_name=r'bankuser_groups_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name=r'bankuser',
            name=r'user_permissions',
            field=models.ManyToManyField(blank=True, related_name=r'bankuser_permissions_set', to='auth.permission'),
        ),
    ]
