# Generated by Django 6.0.1 on 2026-03-14 01:55

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (r'messaging', '0001_initial'),
        (r'users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'HistoricalWorkspace',
            fields=[
                (r'id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                (r'name', models.CharField(max_length=128)),
                (r'slug', models.SlugField(max_length=64)),
                (r'description', models.TextField(blank=True)),
                (r'icon_ipfs_cid', models.CharField(blank=True, max_length=128)),
                (r'compliance_region', models.CharField(choices=[('APAC', 'Asia-Pacific'), ('EMEA', 'Europe/Middle East/Africa'), ('AMER', 'Americas')], default='APAC', max_length=16)),
                (r'retention_days', models.PositiveIntegerField(default=365, help_text='Message retention period')),
                (r'is_e2ee_enforced', models.BooleanField(default=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(blank=True, editable=False)),
                (r'updated_at', models.DateTimeField(blank=True, editable=False)),
                (r'history_id', models.AutoField(primary_key=True, serialize=False)),
                (r'history_date', models.DateTimeField(db_index=True)),
                (r'history_change_reason', models.CharField(max_length=100, null=True)),
                (r'history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                (r'history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                (r'owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'verbose_name': 'historical workspace',
                r'verbose_name_plural': 'historical workspaces',
                r'ordering': ('-history_date', '-history_id'),
                r'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name=r'Workspace',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=128)),
                (r'slug', models.SlugField(max_length=64, unique=True)),
                (r'description', models.TextField(blank=True)),
                (r'icon_ipfs_cid', models.CharField(blank=True, max_length=128)),
                (r'compliance_region', models.CharField(choices=[('APAC', 'Asia-Pacific'), ('EMEA', 'Europe/Middle East/Africa'), ('AMER', 'Americas')], default='APAC', max_length=16)),
                (r'retention_days', models.PositiveIntegerField(default=365, help_text='Message retention period')),
                (r'is_e2ee_enforced', models.BooleanField(default=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'workspace',
                r'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name=r'UserPresence',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'status', models.CharField(choices=[('active', 'Active'), ('away', 'Away'), ('dnd', 'Do Not Disturb'), ('offline', 'Offline')], default='offline', max_length=16)),
                (r'status_text', models.CharField(blank=True, max_length=100)),
                (r'status_emoji', models.CharField(blank=True, max_length=32)),
                (r'last_seen', models.DateTimeField(auto_now=True)),
                (r'dnd_until', models.DateTimeField(blank=True, null=True)),
                (r'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_user_presence',
            },
        ),
        migrations.CreateModel(
            name=r'Channel',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=80)),
                (r'slug', models.SlugField(max_length=80)),
                (r'description', models.TextField(blank=True)),
                (r'channel_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('dm', 'Direct Message'), ('group_dm', 'Group DM'), ('announcement', 'Announcement'), ('compliance', 'Compliance (Read-Only)')], default='public', max_length=16)),
                (r'is_archived', models.BooleanField(default=False)),
                (r'is_read_only', models.BooleanField(default=False)),
                (r'message_retention_override', models.PositiveIntegerField(blank=True, help_text='Days. Null = workspace default', null=True)),
                (r'topic', models.CharField(blank=True, max_length=256)),
                (r'purpose', models.CharField(blank=True, max_length=512)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'last_activity', models.DateTimeField(auto_now=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_channel',
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceAuditLog',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'action', models.CharField(db_index=True, max_length=64)),
                (r'target_type', models.CharField(blank=True, max_length=32)),
                (r'target_id', models.CharField(blank=True, max_length=64)),
                (r'detail', models.JSONField(default=dict)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (r'actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_audit_log',
                r'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceInvite',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'email', models.EmailField(max_length=254)),
                (r'token_hash', models.CharField(max_length=256, unique=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'expires_at', models.DateTimeField()),
                (r'accepted_at', models.DateTimeField(blank=True, null=True)),
                (r'invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userrole')),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_invites', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_invite',
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceMember',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending Approval')], default='pending', max_length=16)),
                (r'joined_at', models.DateTimeField(auto_now_add=True)),
                (r'display_name_override', models.CharField(blank=True, max_length=64)),
                (r'notification_level', models.CharField(choices=[('all', 'All'), ('mentions', 'Mentions Only'), ('none', 'None')], default='all', max_length=16)),
                (r'invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                (r'role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userrole')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_member',
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceSettings',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'allow_guest_access', models.BooleanField(default=False)),
                (r'require_mfa_for_all', models.BooleanField(default=True)),
                (r'allowed_file_types', models.JSONField(default=list, help_text='e.g. ["pdf","docx"]')),
                (r'max_file_size_mb', models.PositiveSmallIntegerField(default=25)),
                (r'enable_message_editing', models.BooleanField(default=True)),
                (r'editing_window_seconds', models.PositiveIntegerField(default=300, help_text='0 = disable editing after send')),
                (r'enable_link_preview', models.BooleanField(default=False, help_text='Disabled by default — security')),
                (r'screenshot_protection', models.BooleanField(default=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_settings',
            },
        ),
        migrations.CreateModel(
            name=r'ChannelMember',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'joined_at', models.DateTimeField(auto_now_add=True)),
                (r'is_admin', models.BooleanField(default=False)),
                (r'last_read_at', models.DateTimeField(blank=True, null=True)),
                (r'mention_count', models.PositiveIntegerField(default=0)),
                (r'is_muted', models.BooleanField(default=False)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspace.channel')),
                (r'last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.message')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'workspace_channel_member',
                r'indexes': [models.Index(fields=['user', 'channel'], name='workspace_c_user_id_09e239_idx')],
                r'unique_together': {('channel', 'user')},
            },
        ),
        migrations.CreateModel(
            name=r'ChannelPin',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'pinned_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='workspace.channel')),
                (r'message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='messaging.message')),
                (r'pinned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'workspace_channel_pin',
                r'unique_together': {('channel', 'message')},
            },
        ),
        migrations.CreateModel(
            name=r'Emoji',
            fields=[
                (r'id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (r'name', models.CharField(db_index=True, max_length=32)),
                (r'ipfs_cid', models.CharField(max_length=128)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_emojis', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_emoji',
                r'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name=r'channel',
            index=models.Index(fields=[r'workspace', 'channel_type', 'is_archived'], name='workspace_c_workspa_ed121f_idx'),
        ),
        migrations.AddIndex(
            model_name=r'channel',
            index=models.Index(fields=[r'last_activity'], name='workspace_c_last_ac_1d70f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name=r'channel',
            unique_together={(r'workspace', 'slug')},
        ),
        migrations.AddIndex(
            model_name=r'workspacemember',
            index=models.Index(fields=[r'workspace', 'status'], name='workspace_m_workspa_17ef29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name=r'workspacemember',
            unique_together={(r'workspace', 'user')},
        ),
    ]
