# Generated by Django 6.0.1 on 2026-03-14 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'BankingChannel',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'channel_category', models.CharField(choices=[('trading_desk', 'Trading Desk'), ('risk_management', 'Risk Management'), ('compliance', 'Compliance'), ('treasury', 'Treasury'), ('retail_banking', 'Retail Banking'), ('corporate_banking', 'Corporate Banking'), ('investment', 'Investment Banking'), ('swift_ops', 'SWIFT Operations')], max_length=50)),
                (r'requires_compliance_review', models.BooleanField(default=False)),
                (r'max_message_ttl', models.PositiveIntegerField(default=86400)),
                (r'requires_mfa', models.BooleanField(default=True)),
                (r'min_clearance_level', models.PositiveSmallIntegerField(default=1)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banking_config', to='workspace.channel')),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_channels', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_banking_channel',
            },
        ),
        migrations.CreateModel(
            name=r'ComplianceCheckpoint',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'checkpoint_type', models.CharField(choices=[('pre_trade', 'Pre-Trade Check'), ('post_trade', 'Post-Trade Check'), ('communication', 'Communication Review'), ('document', 'Document Approval')], max_length=50)),
                (r'is_required', models.BooleanField(default=True)),
                (r'approver_role', models.CharField(blank=True, max_length=50)),
                (r'sla_minutes', models.PositiveIntegerField(default=30)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='workspace.channel')),
            ],
            options={
                r'db_table': 'workspace_compliance_checkpoint',
            },
        ),
        migrations.CreateModel(
            name=r'DealRoom',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=255)),
                (r'deal_type', models.CharField(choices=[('ma', 'Mergers & Acquisitions'), ('loan', 'Loan Syndication'), ('ipo', 'IPO'), ('bond', 'Bond Issuance'), ('fx', 'FX Deal')], max_length=50)),
                (r'deal_value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                (r'currency', models.CharField(default='IDR', max_length=3)),
                (r'nda_required', models.BooleanField(default=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'closes_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'participants', models.ManyToManyField(related_name='deal_rooms', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_rooms', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_deal_room',
            },
        ),
        migrations.CreateModel(
            name=r'MessageApproval',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'message_hash', models.CharField(max_length=64)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                (r'notes', models.TextField(blank=True)),
                (r'expires_at', models.DateTimeField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'decided_at', models.DateTimeField(blank=True, null=True)),
                (r'approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_given', to=settings.AUTH_USER_MODEL)),
                (r'checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.compliancecheckpoint')),
                (r'requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'workspace_message_approval',
            },
        ),
    ]
