# Generated by Django 6.0.1 on 2026-03-14 07:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0002_bankingchannel_compliancecheckpoint_dealroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'EscalationMatrix',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'issue_type', models.CharField(max_length=50)),
                (r'severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                (r'sla_minutes_l1', models.PositiveIntegerField(default=30)),
                (r'sla_minutes_l2', models.PositiveIntegerField(default=60)),
                (r'sla_minutes_l3', models.PositiveIntegerField(default=120)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'level_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_l1', to=settings.AUTH_USER_MODEL)),
                (r'level_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_l2', to=settings.AUTH_USER_MODEL)),
                (r'level_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_l3', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_matrix', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_escalation_matrix',
            },
        ),
        migrations.CreateModel(
            name=r'TradingDesk',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'desk_type', models.CharField(choices=[('equity', 'Equity'), ('fixed_income', 'Fixed Income'), ('fx', 'Foreign Exchange'), ('derivatives', 'Derivatives'), ('commodities', 'Commodities'), ('crypto', 'Digital Assets')], max_length=50)),
                (r'risk_limit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                (r'daily_var_limit', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'head_trader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_desks', to=settings.AUTH_USER_MODEL)),
                (r'members', models.ManyToManyField(related_name='trading_desks', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_desks', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_trading_desk',
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceAnnouncement',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'ciphertext_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                (r'requires_acknowledgement', models.BooleanField(default=False)),
                (r'published_at', models.DateTimeField(auto_now_add=True)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'published_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_announcement',
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceIntegration',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'integration_type', models.CharField(choices=[('bloomberg', 'Bloomberg Terminal'), ('reuters', 'Reuters Eikon'), ('swift', 'SWIFT Alliance'), ('murex', 'Murex'), ('calypso', 'Calypso'), ('temenos', 'Temenos'), ('fiserv', 'Fiserv')], max_length=50)),
                (r'api_endpoint', models.URLField(blank=True)),
                (r'encrypted_credentials_b64', models.TextField(blank=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'last_sync', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_integration',
            },
        ),
        migrations.CreateModel(
            name=r'AnnouncementAcknowledgement',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'acknowledged_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='workspace.workspaceannouncement')),
            ],
            options={
                r'db_table': 'workspace_announcement_ack',
                r'unique_together': {('announcement', 'user')},
            },
        ),
    ]
