# Generated by Django 6.0.1 on 2026-03-14 07:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0003_escalationmatrix_tradingdesk_workspaceannouncement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'ServiceLevelAgreement',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'service_name', models.CharField(max_length=100)),
                (r'metric_type', models.CharField(choices=[('response_time', 'Response Time'), ('uptime', 'Uptime'), ('transaction_speed', 'Transaction Speed'), ('resolution_time', 'Resolution Time')], max_length=50)),
                (r'target_value', models.FloatField()),
                (r'current_value', models.FloatField(default=0.0)),
                (r'unit', models.CharField(max_length=20)),
                (r'is_breached', models.BooleanField(default=False)),
                (r'breach_count', models.PositiveIntegerField(default=0)),
                (r'last_measured', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_sla',
            },
        ),
        migrations.CreateModel(
            name=r'WorkflowInstance',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'reference_id', models.CharField(max_length=50)),
                (r'reference_type', models.CharField(max_length=50)),
                (r'current_step', models.PositiveIntegerField(default=0)),
                (r'status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                (r'due_at', models.DateTimeField(blank=True, null=True)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workflows', to=settings.AUTH_USER_MODEL)),
                (r'initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'workspace_workflow_instance',
            },
        ),
        migrations.CreateModel(
            name=r'WorkflowStep',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'step_number', models.PositiveIntegerField()),
                (r'step_name', models.CharField(max_length=100)),
                (r'action_taken', models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated'), ('returned', 'Returned'), ('skipped', 'Skipped')], max_length=50)),
                (r'comments_encrypted_b64', models.TextField(blank=True)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workspace.workflowinstance')),
            ],
            options={
                r'db_table': 'workspace_workflow_step',
            },
        ),
        migrations.CreateModel(
            name=r'WorkflowTemplate',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'workflow_type', models.CharField(choices=[('loan_approval', 'Loan Approval'), ('account_opening', 'Account Opening'), ('kyc_review', 'KYC Review'), ('trade_approval', 'Trade Approval'), ('complaint_handling', 'Complaint Handling'), ('fraud_investigation', 'Fraud Investigation'), ('contract_signing', 'Contract Signing')], max_length=50)),
                (r'steps', models.JSONField(default=list)),
                (r'sla_hours', models.PositiveIntegerField(default=24)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_templates', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_workflow_template',
            },
        ),
        migrations.AddField(
            model_name=r'workflowinstance',
            name=r'template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'instances', to='workspace.workflowtemplate'),
        ),
    ]
