# Generated by Django 6.0.1 on 2026-03-14 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0004_servicelevelagreement_workflowinstance_workflowstep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'BankingLicense',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'license_type', models.CharField(choices=[('commercial_bank', 'Commercial Bank'), ('investment_bank', 'Investment Bank'), ('digital_bank', 'Digital Bank'), ('payment_institution', 'Payment Institution'), ('securities_firm', 'Securities Firm'), ('asset_management', 'Asset Management')], max_length=50)),
                (r'license_number', models.CharField(max_length=100, unique=True)),
                (r'issuing_authority', models.CharField(choices=[('ojk', 'OJK'), ('bi', 'Bank Indonesia'), ('bappebti', 'BAPPEBTI'), ('sec', 'SEC')], max_length=50)),
                (r'issued_date', models.DateField()),
                (r'expiry_date', models.DateField()),
                (r'is_active', models.BooleanField(default=True)),
                (r'document_cid', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_banking_license',
            },
        ),
        migrations.CreateModel(
            name=r'BoardResolution',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'resolution_number', models.CharField(max_length=50, unique=True)),
                (r'title', models.CharField(max_length=255)),
                (r'content_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'resolution_date', models.DateField()),
                (r'effective_date', models.DateField()),
                (r'document_cid', models.TextField(blank=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'signatories', models.ManyToManyField(related_name='board_resolutions', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_resolutions', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_board_resolution',
            },
        ),
        migrations.CreateModel(
            name=r'BranchOffice',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'branch_code', models.CharField(max_length=20, unique=True)),
                (r'branch_name', models.CharField(max_length=100)),
                (r'branch_type', models.CharField(choices=[('head_office', 'Head Office'), ('regional', 'Regional Office'), ('branch', 'Branch'), ('sub_branch', 'Sub Branch'), ('atm', 'ATM'), ('digital', 'Digital Branch')], max_length=30)),
                (r'address', models.TextField()),
                (r'city', models.CharField(max_length=100)),
                (r'country', models.CharField(default='Indonesia', max_length=50)),
                (r'swift_code', models.CharField(blank=True, max_length=11)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_branches', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_branch_office',
            },
        ),
        migrations.CreateModel(
            name=r'CorporateHierarchy',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'entity_name', models.CharField(max_length=100)),
                (r'entity_type', models.CharField(choices=[('holding', 'Holding Company'), ('subsidiary', 'Subsidiary'), ('affiliate', 'Affiliate'), ('joint_venture', 'Joint Venture'), ('special_purpose', 'Special Purpose Vehicle')], max_length=50)),
                (r'ownership_percentage', models.FloatField(default=100.0)),
                (r'country', models.CharField(max_length=50)),
                (r'is_regulated', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='workspace.corporatehierarchy')),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_corporate_hierarchy',
            },
        ),
    ]
