# Generated by Django 6.0.1 on 2026-03-15 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0005_bankinglicense_boardresolution_branchoffice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'RemoteWorkSession',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'session_type', models.CharField(choices=[('focus', 'Focus Mode'), ('meeting', 'Meeting'), ('break', 'Break'), ('available', 'Available'), ('dnd', 'Do Not Disturb')], default='available', max_length=50)),
                (r'started_at', models.DateTimeField(auto_now_add=True)),
                (r'ended_at', models.DateTimeField(blank=True, null=True)),
                (r'productive_minutes', models.PositiveIntegerField(default=0)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_remote_session',
            },
        ),
        migrations.CreateModel(
            name=r'TaskBoard',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'description', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_boards', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_task_board',
            },
        ),
        migrations.CreateModel(
            name=r'Task',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('done', 'Done')], default='todo', max_length=20)),
                (r'priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                (r'due_date', models.DateField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                (r'board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspace.taskboard')),
            ],
            options={
                r'db_table': 'workspace_task',
            },
        ),
        migrations.CreateModel(
            name=r'VirtualMeetingRoom',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'room_type', models.CharField(choices=[('standup', 'Daily Standup'), ('planning', 'Sprint Planning'), ('review', 'Code Review'), ('all_hands', 'All Hands'), ('one_on_one', '1-on-1'), ('open', 'Open Room')], max_length=50)),
                (r'max_participants', models.PositiveIntegerField(default=20)),
                (r'is_active', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_rooms', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_virtual_room',
            },
        ),
        migrations.CreateModel(
            name=r'AttendanceLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'check_in', models.DateTimeField()),
                (r'check_out', models.DateTimeField(blank=True, null=True)),
                (r'work_hours', models.FloatField(default=0.0)),
                (r'location', models.CharField(blank=True, max_length=100)),
                (r'date', models.DateField()),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_attendance',
                r'unique_together': {('user', 'date')},
            },
        ),
    ]
