# Generated by Django 6.0.1 on 2026-03-15 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0006_remoteworksession_taskboard_task_virtualmeetingroom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'OKR',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'quarter', models.CharField(max_length=10)),
                (r'progress', models.FloatField(default=0.0)),
                (r'status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('behind', 'Behind'), ('done', 'Done')], default='on_track', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okrs', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_okr',
            },
        ),
        migrations.CreateModel(
            name=r'KeyResult',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'target_value', models.FloatField(default=100.0)),
                (r'current_value', models.FloatField(default=0.0)),
                (r'unit', models.CharField(blank=True, max_length=20)),
                (r'due_date', models.DateField(blank=True, null=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'okr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='workspace.okr')),
            ],
            options={
                r'db_table': 'workspace_key_result',
            },
        ),
        migrations.CreateModel(
            name=r'Sprint',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'goal', models.TextField(blank=True)),
                (r'status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('review', 'Review'), ('done', 'Done')], default='planning', max_length=20)),
                (r'start_date', models.DateField(blank=True, null=True)),
                (r'end_date', models.DateField(blank=True, null=True)),
                (r'velocity', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_sprint',
            },
        ),
        migrations.CreateModel(
            name=r'TeamCalendar',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'event_type', models.CharField(choices=[('meeting', 'Meeting'), ('deadline', 'Deadline'), ('review', 'Review'), ('holiday', 'Holiday'), ('training', 'Training'), ('one_on_one', '1-on-1')], max_length=50)),
                (r'start_time', models.DateTimeField()),
                (r'end_time', models.DateTimeField()),
                (r'meeting_url', models.URLField(blank=True)),
                (r'is_recurring', models.BooleanField(default=False)),
                (r'recurrence_rule', models.CharField(blank=True, max_length=100)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'attendees', models.ManyToManyField(blank=True, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_calendar_event',
            },
        ),
        migrations.CreateModel(
            name=r'TeamGoal',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'target_date', models.DateField(blank=True, null=True)),
                (r'progress', models.FloatField(default=0.0)),
                (r'is_completed', models.BooleanField(default=False)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'assigned_to', models.ManyToManyField(blank=True, related_name='team_goals', to=settings.AUTH_USER_MODEL)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_goals', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_team_goal',
            },
        ),
        migrations.CreateModel(
            name=r'TimeTracking',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'minutes', models.PositiveIntegerField(default=0)),
                (r'description', models.TextField(blank=True)),
                (r'logged_at', models.DateTimeField(auto_now_add=True)),
                (r'date', models.DateField()),
                (r'task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='workspace.task')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'workspace_time_tracking',
            },
        ),
        migrations.CreateModel(
            name=r'WikiPage',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'content_encrypted_b64', models.TextField(blank=True)),
                (r'nonce_b64', models.TextField(blank=True)),
                (r'auth_tag_b64', models.TextField(blank=True)),
                (r'icon', models.CharField(blank=True, max_length=10)),
                (r'cover_ipfs_cid', models.TextField(blank=True)),
                (r'is_published', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='workspace.wikipage')),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_wiki_page',
            },
        ),
        migrations.CreateModel(
            name=r'WikiPageVersion',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'content_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'version_number', models.PositiveIntegerField(default=1)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workspace.wikipage')),
            ],
            options={
                r'db_table': 'workspace_wiki_version',
            },
        ),
        migrations.CreateModel(
            name=r'SprintTask',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'story_points', models.PositiveSmallIntegerField(default=1)),
                (r'added_at', models.DateTimeField(auto_now_add=True)),
                (r'sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_tasks', to='workspace.sprint')),
                (r'task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.task')),
            ],
            options={
                r'db_table': 'workspace_sprint_task',
                r'unique_together': {('sprint', 'task')},
            },
        ),
        migrations.CreateModel(
            name=r'Standup',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'yesterday', models.TextField()),
                (r'today', models.TextField()),
                (r'blockers', models.TextField(blank=True)),
                (r'mood', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                (r'date', models.DateField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standups', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_standup',
                r'unique_together': {('user', 'date')},
            },
        ),
    ]
