# Generated by Django 6.0.1 on 2026-03-15 13:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0007_okr_keyresult_sprint_teamcalendar_teamgoal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'DocumentTemplate',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'template_type', models.CharField(choices=[('meeting_notes', 'Meeting Notes'), ('project_brief', 'Project Brief'), ('retrospective', 'Retrospective'), ('one_on_one', '1-on-1 Notes'), ('incident', 'Incident Report'), ('rfc', 'RFC Document')], max_length=50)),
                (r'content_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_templates', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_doc_template',
            },
        ),
        migrations.CreateModel(
            name=r'GitHubEvent',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'event_type', models.CharField(max_length=50)),
                (r'repository', models.CharField(max_length=255)),
                (r'actor', models.CharField(max_length=100)),
                (r'payload', models.JSONField(default=dict)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.channel')),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_events', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_github_event',
            },
        ),
        migrations.CreateModel(
            name=r'MeetingNotes',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'content_encrypted_b64', models.TextField(blank=True)),
                (r'nonce_b64', models.TextField(blank=True)),
                (r'auth_tag_b64', models.TextField(blank=True)),
                (r'action_items', models.JSONField(default=list)),
                (r'meeting_date', models.DateTimeField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'attendees', models.ManyToManyField(blank=True, related_name='meeting_notes', to=settings.AUTH_USER_MODEL)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_notes', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_meeting_notes',
            },
        ),
        migrations.CreateModel(
            name=r'ProjectMilestone',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'due_date', models.DateField(blank=True, null=True)),
                (r'status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='upcoming', max_length=20)),
                (r'progress', models.FloatField(default=0.0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_milestone',
            },
        ),
        migrations.CreateModel(
            name=r'ProjectTemplate',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'description', models.TextField(blank=True)),
                (r'template_type', models.CharField(choices=[('software', 'Software Development'), ('marketing', 'Marketing Campaign'), ('design', 'Design Project'), ('research', 'Research'), ('onboarding', 'Employee Onboarding'), ('product', 'Product Launch')], max_length=50)),
                (r'structure', models.JSONField(default=dict)),
                (r'is_public', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_project_template',
            },
        ),
        migrations.CreateModel(
            name=r'TaskAttachment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'filename', models.CharField(max_length=255)),
                (r'file_cid', models.TextField()),
                (r'file_size', models.BigIntegerField(default=0)),
                (r'mime_type', models.CharField(blank=True, max_length=100)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workspace.task')),
                (r'uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'workspace_task_attachment',
            },
        ),
        migrations.CreateModel(
            name=r'TaskComment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'content_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'is_edited', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workspace.task')),
            ],
            options={
                r'db_table': 'workspace_task_comment',
            },
        ),
        migrations.CreateModel(
            name=r'TaskLabel',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=50)),
                (r'color', models.CharField(default='#6366f1', max_length=7)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_label',
                r'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceIntegrationToken',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'integration_type', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('jira', 'Jira'), ('notion', 'Notion'), ('figma', 'Figma'), ('google_calendar', 'Google Calendar'), ('zoom', 'Zoom'), ('lark', 'Lark')], max_length=50)),
                (r'token_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_tokens', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_integration_token',
            },
        ),
        migrations.CreateModel(
            name=r'TaskLabelAssignment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.tasklabel')),
                (r'task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='workspace.task')),
            ],
            options={
                r'db_table': 'workspace_task_label',
                r'unique_together': {('task', 'label')},
            },
        ),
    ]
