# Generated by Django 6.0.1 on 2026-03-15 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0008_documenttemplate_githubevent_meetingnotes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'BudgetTracker',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'category', models.CharField(max_length=50)),
                (r'allocated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'period', models.CharField(max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_budget',
            },
        ),
        migrations.CreateModel(
            name=r'BudgetExpense',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'amount', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'receipt_cid', models.TextField(blank=True)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                (r'submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='workspace.budgettracker')),
            ],
            options={
                r'db_table': 'workspace_expense',
            },
        ),
        migrations.CreateModel(
            name=r'Department',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'description', models.TextField(blank=True)),
                (r'budget', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                (r'parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='workspace.department')),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_department',
            },
        ),
        migrations.AddField(
            model_name=r'budgettracker',
            name=r'department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=r'workspace.department'),
        ),
        migrations.CreateModel(
            name=r'ProjectRoadmap',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'start_date', models.DateField(null=True)),
                (r'end_date', models.DateField(null=True)),
                (r'status', models.CharField(default='active', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_roadmap',
            },
        ),
        migrations.CreateModel(
            name=r'ResourceBooking',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'resource_type', models.CharField(choices=[('room', 'Meeting Room'), ('equipment', 'Equipment'), ('license', 'Software License'), ('server', 'Server')], max_length=50)),
                (r'resource_name', models.CharField(max_length=100)),
                (r'start_time', models.DateTimeField()),
                (r'end_time', models.DateTimeField()),
                (r'purpose', models.TextField(blank=True)),
                (r'status', models.CharField(default='confirmed', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_resource_booking',
            },
        ),
        migrations.CreateModel(
            name=r'RoadmapItem',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'status', models.CharField(default='planned', max_length=20)),
                (r'start_date', models.DateField(null=True)),
                (r'end_date', models.DateField(null=True)),
                (r'progress', models.FloatField(default=0.0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                (r'roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workspace.projectroadmap')),
            ],
            options={
                r'db_table': 'workspace_roadmap_item',
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceSubscription',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20)),
                (r'max_members', models.PositiveIntegerField(default=10)),
                (r'max_storage_gb', models.PositiveIntegerField(default=10)),
                (r'features', models.JSONField(default=list)),
                (r'billing_cycle', models.CharField(default='monthly', max_length=20)),
                (r'next_billing', models.DateField(null=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_subscription',
            },
        ),
        migrations.CreateModel(
            name=r'ChannelAnalytics',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'date', models.DateField()),
                (r'messages_sent', models.PositiveIntegerField(default=0)),
                (r'active_members', models.PositiveIntegerField(default=0)),
                (r'reactions_given', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='workspace.channel')),
            ],
            options={
                r'db_table': 'workspace_channel_analytics',
                r'unique_together': {('channel', 'date')},
            },
        ),
        migrations.CreateModel(
            name=r'DepartmentMember',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'role', models.CharField(default='member', max_length=50)),
                (r'joined_at', models.DateTimeField(auto_now_add=True)),
                (r'department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspace.department')),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'workspace_department_member',
                r'unique_together': {('department', 'user')},
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceAnalytics',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'date', models.DateField()),
                (r'active_users', models.PositiveIntegerField(default=0)),
                (r'messages_sent', models.PositiveIntegerField(default=0)),
                (r'files_uploaded', models.PositiveIntegerField(default=0)),
                (r'tasks_completed', models.PositiveIntegerField(default=0)),
                (r'meeting_minutes', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_analytics',
                r'unique_together': {('workspace', 'date')},
            },
        ),
    ]
