# Generated by Django 6.0.1 on 2026-03-15 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0009_budgettracker_budgetexpense_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'Automation',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'trigger', models.CharField(choices=[('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('message_sent', 'Message Sent'), ('member_joined', 'Member Joined'), ('due_date', 'Due Date Reached')], max_length=50)),
                (r'conditions', models.JSONField(default=dict)),
                (r'actions', models.JSONField(default=list)),
                (r'is_active', models.BooleanField(default=True)),
                (r'run_count', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_automation',
            },
        ),
        migrations.CreateModel(
            name=r'AutomationLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'trigger_data', models.JSONField(default=dict)),
                (r'actions_taken', models.JSONField(default=list)),
                (r'status', models.CharField(default='success', max_length=20)),
                (r'error_message', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workspace.automation')),
            ],
            options={
                r'db_table': 'workspace_automation_log',
            },
        ),
        migrations.CreateModel(
            name=r'CustomField',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multi-Select'), ('checkbox', 'Checkbox'), ('url', 'URL'), ('email', 'Email')], max_length=20)),
                (r'options', models.JSONField(default=list)),
                (r'is_required', models.BooleanField(default=False)),
                (r'apply_to', models.CharField(choices=[('task', 'Task'), ('project', 'Project'), ('user', 'User')], max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_custom_field',
            },
        ),
        migrations.CreateModel(
            name=r'CustomFieldValue',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'object_id', models.CharField(max_length=50)),
                (r'value', models.TextField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='workspace.customfield')),
            ],
            options={
                r'db_table': 'workspace_custom_field_value',
            },
        ),
        migrations.CreateModel(
            name=r'DataExport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'export_type', models.CharField(choices=[('messages', 'Messages'), ('files', 'Files'), ('tasks', 'Tasks'), ('users', 'Users'), ('full', 'Full Workspace')], max_length=50)),
                (r'format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV'), ('zip', 'ZIP')], max_length=10)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'file_cid', models.TextField(blank=True)),
                (r'size_bytes', models.BigIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_at', models.DateTimeField(null=True)),
                (r'requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_data_export',
            },
        ),
        migrations.CreateModel(
            name=r'DataImport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'source', models.CharField(choices=[('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('notion', 'Notion'), ('jira', 'Jira'), ('csv', 'CSV'), ('json', 'JSON')], max_length=50)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'total_records', models.PositiveIntegerField(default=0)),
                (r'imported_records', models.PositiveIntegerField(default=0)),
                (r'failed_records', models.PositiveIntegerField(default=0)),
                (r'error_log', models.TextField(blank=True)),
                (r'started_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_at', models.DateTimeField(null=True)),
                (r'initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_data_import',
            },
        ),
        migrations.CreateModel(
            name=r'WorkflowTrigger',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'trigger_type', models.CharField(max_length=50)),
                (r'schedule', models.CharField(blank=True, max_length=100)),
                (r'webhook_url', models.URLField(blank=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'last_triggered', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_triggers', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_workflow_trigger',
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceApp',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'app_name', models.CharField(max_length=100)),
                (r'app_type', models.CharField(choices=[('bot', 'Bot'), ('integration', 'Integration'), ('webhook', 'Webhook'), ('slash_command', 'Slash Command')], max_length=50)),
                (r'app_url', models.URLField(blank=True)),
                (r'token_encrypted_b64', models.TextField(blank=True)),
                (r'nonce_b64', models.TextField(blank=True)),
                (r'auth_tag_b64', models.TextField(blank=True)),
                (r'permissions', models.JSONField(default=list)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'installed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_app',
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceTheme',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'primary_color', models.CharField(default='#6366f1', max_length=7)),
                (r'secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                (r'background_color', models.CharField(default='#0a0a0f', max_length=7)),
                (r'sidebar_color', models.CharField(default='#1a1d21', max_length=7)),
                (r'is_active', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'workspace_theme',
            },
        ),
        migrations.CreateModel(
            name=r'SlashCommand',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'command', models.CharField(max_length=50)),
                (r'description', models.CharField(max_length=255)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slash_commands', to='workspace.workspace')),
                (r'app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='workspace.workspaceapp')),
            ],
            options={
                r'db_table': 'workspace_slash_command',
                r'unique_together': {('workspace', 'command')},
            },
        ),
    ]
