# Generated by Django 6.0.1 on 2026-03-15 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0010_automation_automationlog_customfield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'Announcement',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'content', models.TextField()),
                (r'priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                (r'target_all', models.BooleanField(default=True)),
                (r'expires_at', models.DateTimeField(null=True)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'comms_announcement',
            },
        ),
        migrations.CreateModel(
            name=r'BenefitPlan',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'plan_type', models.CharField(choices=[('health', 'Health'), ('dental', 'Dental'), ('vision', 'Vision'), ('life', 'Life Insurance'), ('pension', 'Pension'), ('education', 'Education')], max_length=50)),
                (r'description', models.TextField()),
                (r'employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (r'employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'hr_benefit_plan',
            },
        ),
        migrations.CreateModel(
            name=r'Bug',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField()),
                (r'severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                (r'status', models.CharField(default='open', max_length=20)),
                (r'reporter_id', models.CharField(max_length=50)),
                (r'assignee_id', models.CharField(blank=True, max_length=50)),
                (r'environment', models.CharField(blank=True, max_length=50)),
                (r'steps_to_reproduce', models.TextField(blank=True)),
                (r'expected_behavior', models.TextField(blank=True)),
                (r'actual_behavior', models.TextField(blank=True)),
                (r'fixed_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pm_bug',
            },
        ),
        migrations.CreateModel(
            name=r'Dependency',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'task_id', models.CharField(max_length=50)),
                (r'depends_on_id', models.CharField(max_length=50)),
                (r'dependency_type', models.CharField(choices=[('blocks', 'Blocks'), ('blocked_by', 'Blocked By'), ('relates_to', 'Relates To')], max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pm_dependency',
            },
        ),
        migrations.CreateModel(
            name=r'DisciplinaryAction',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'action_type', models.CharField(choices=[('verbal_warning', 'Verbal Warning'), ('written_warning', 'Written Warning'), ('suspension', 'Suspension'), ('termination', 'Termination')], max_length=50)),
                (r'reason', models.TextField()),
                (r'issued_by', models.CharField(max_length=50)),
                (r'action_date', models.DateField()),
                (r'appeal_deadline', models.DateField(null=True)),
                (r'is_appealed', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'hr_disciplinary',
            },
        ),
        migrations.CreateModel(
            name=r'EmailTemplate',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'subject', models.CharField(max_length=255)),
                (r'body', models.TextField()),
                (r'variables', models.JSONField(default=list)),
                (r'category', models.CharField(max_length=50)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'comms_email_template',
            },
        ),
        migrations.CreateModel(
            name=r'EmployeeAsset',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'asset_type', models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('monitor', 'Monitor'), ('keyboard', 'Keyboard'), ('access_card', 'Access Card'), ('vehicle', 'Vehicle')], max_length=50)),
                (r'asset_name', models.CharField(max_length=100)),
                (r'serial_number', models.CharField(blank=True, max_length=100)),
                (r'assigned_date', models.DateField()),
                (r'returned_date', models.DateField(null=True)),
                (r'condition', models.CharField(default='good', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'hr_asset',
            },
        ),
        migrations.CreateModel(
            name=r'EmployeeContract',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship')], max_length=20)),
                (r'start_date', models.DateField()),
                (r'end_date', models.DateField(null=True)),
                (r'salary', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'benefits', models.JSONField(default=dict)),
                (r'contract_cid', models.TextField(blank=True)),
                (r'is_signed', models.BooleanField(default=False)),
                (r'signed_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'hr_contract',
            },
        ),
        migrations.CreateModel(
            name=r'Epic',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'color', models.CharField(default='#6366f1', max_length=7)),
                (r'status', models.CharField(default='open', max_length=20)),
                (r'start_date', models.DateField(null=True)),
                (r'end_date', models.DateField(null=True)),
                (r'progress', models.FloatField(default=0.0)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pm_epic',
            },
        ),
        migrations.CreateModel(
            name=r'JobApplication',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'applicant_name', models.CharField(max_length=100)),
                (r'applicant_email', models.EmailField(max_length=254)),
                (r'resume_cid', models.TextField(blank=True)),
                (r'cover_letter', models.TextField(blank=True)),
                (r'status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                (r'applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'hr_job_application',
            },
        ),
        migrations.CreateModel(
            name=r'JobOpening',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'description', models.TextField()),
                (r'requirements', models.TextField()),
                (r'status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('on_hold', 'On Hold')], default='open', max_length=20)),
                (r'openings_count', models.PositiveSmallIntegerField(default=1)),
                (r'deadline', models.DateField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'hr_job_opening',
            },
        ),
        migrations.CreateModel(
            name=r'JobPosition',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=100)),
                (r'department', models.CharField(max_length=100)),
                (r'level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager'), ('director', 'Director'), ('vp', 'VP'), ('c_level', 'C-Level')], max_length=20)),
                (r'min_salary', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                (r'max_salary', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'hr_job_position',
            },
        ),
        migrations.CreateModel(
            name=r'NotificationPreference',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50, unique=True)),
                (r'email_enabled', models.BooleanField(default=True)),
                (r'sms_enabled', models.BooleanField(default=False)),
                (r'push_enabled', models.BooleanField(default=True)),
                (r'quiet_hours_start', models.TimeField(null=True)),
                (r'quiet_hours_end', models.TimeField(null=True)),
                (r'timezone', models.CharField(default='Asia/Jakarta', max_length=50)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                r'db_table': 'comms_notif_pref',
            },
        ),
        migrations.CreateModel(
            name=r'ProjectHealth',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'date', models.DateField()),
                (r'health_score', models.FloatField(default=100.0)),
                (r'velocity', models.FloatField(default=0.0)),
                (r'bug_rate', models.FloatField(default=0.0)),
                (r'completion_rate', models.FloatField(default=0.0)),
                (r'team_happiness', models.FloatField(default=5.0)),
                (r'notes', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pm_health',
            },
        ),
        migrations.CreateModel(
            name=r'PushNotification',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=100)),
                (r'body', models.TextField()),
                (r'data', models.JSONField(default=dict)),
                (r'is_read', models.BooleanField(default=False)),
                (r'read_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'comms_push',
            },
        ),
        migrations.CreateModel(
            name=r'Release',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'version', models.CharField(max_length=20)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'release_date', models.DateField(null=True)),
                (r'status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pm_release',
            },
        ),
        migrations.CreateModel(
            name=r'SalaryHistory',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'previous_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'new_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'change_reason', models.CharField(max_length=100)),
                (r'effective_date', models.DateField()),
                (r'approved_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'hr_salary_history',
            },
        ),
        migrations.CreateModel(
            name=r'SMSLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'to_number', models.CharField(max_length=20)),
                (r'message', models.TextField()),
                (r'status', models.CharField(default='sent', max_length=20)),
                (r'provider', models.CharField(blank=True, max_length=50)),
                (r'sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'comms_sms_log',
            },
        ),
        migrations.CreateModel(
            name=r'TestCase',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'test_type', models.CharField(choices=[('unit', 'Unit'), ('integration', 'Integration'), ('e2e', 'E2E'), ('performance', 'Performance'), ('security', 'Security')], max_length=20)),
                (r'steps', models.JSONField(default=list)),
                (r'expected_result', models.TextField()),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pm_test_case',
            },
        ),
        migrations.CreateModel(
            name=r'VideoCall',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(blank=True, max_length=255)),
                (r'host_id', models.CharField(max_length=50)),
                (r'room_id', models.CharField(max_length=100, unique=True)),
                (r'started_at', models.DateTimeField(auto_now_add=True)),
                (r'ended_at', models.DateTimeField(null=True)),
                (r'duration_seconds', models.PositiveIntegerField(default=0)),
                (r'recording_cid', models.TextField(blank=True)),
            ],
            options={
                r'db_table': 'comms_video_call',
            },
        ),
        migrations.CreateModel(
            name=r'WebhookEndpoint',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'url', models.URLField()),
                (r'events', models.JSONField(default=list)),
                (r'secret_hash', models.CharField(max_length=64)),
                (r'is_active', models.BooleanField(default=True)),
                (r'last_triggered', models.DateTimeField(null=True)),
                (r'failure_count', models.PositiveSmallIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'comms_webhook',
            },
        ),
        migrations.CreateModel(
            name=r'AnnouncementRead',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'read_at', models.DateTimeField(auto_now_add=True)),
                (r'announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.announcement')),
            ],
            options={
                r'db_table': 'comms_announcement_read',
            },
        ),
        migrations.CreateModel(
            name=r'BugComment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'author_id', models.CharField(max_length=50)),
                (r'content', models.TextField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workspace.bug')),
            ],
            options={
                r'db_table': 'pm_bug_comment',
            },
        ),
        migrations.CreateModel(
            name=r'EmailLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'to_email', models.EmailField(max_length=254)),
                (r'subject', models.CharField(max_length=255)),
                (r'status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('opened', 'Opened')], max_length=20)),
                (r'sent_at', models.DateTimeField(auto_now_add=True)),
                (r'opened_at', models.DateTimeField(null=True)),
                (r'template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.emailtemplate')),
            ],
            options={
                r'db_table': 'comms_email_log',
            },
        ),
        migrations.CreateModel(
            name=r'EmployeeBenefit',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'enrolled_at', models.DateField()),
                (r'is_active', models.BooleanField(default=True)),
                (r'plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.benefitplan')),
            ],
            options={
                r'db_table': 'hr_employee_benefit',
            },
        ),
        migrations.CreateModel(
            name=r'Interview',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'interviewer_id', models.CharField(max_length=50)),
                (r'interview_type', models.CharField(choices=[('phone', 'Phone'), ('video', 'Video'), ('technical', 'Technical'), ('hr', 'HR'), ('final', 'Final')], max_length=20)),
                (r'scheduled_at', models.DateTimeField()),
                (r'duration_minutes', models.PositiveSmallIntegerField(default=60)),
                (r'feedback', models.TextField(blank=True)),
                (r'score', models.FloatField(null=True)),
                (r'status', models.CharField(default='scheduled', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='workspace.jobapplication')),
            ],
            options={
                r'db_table': 'hr_interview',
            },
        ),
        migrations.AddField(
            model_name=r'jobapplication',
            name=r'opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'applications', to='workspace.jobopening'),
        ),
        migrations.AddField(
            model_name=r'jobopening',
            name=r'position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=r'workspace.jobposition'),
        ),
        migrations.CreateModel(
            name=r'ReleaseNote',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'category', models.CharField(choices=[('feature', 'Feature'), ('fix', 'Bug Fix'), ('improvement', 'Improvement'), ('breaking', 'Breaking Change')], max_length=20)),
                (r'description', models.TextField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workspace.release')),
            ],
            options={
                r'db_table': 'pm_release_note',
            },
        ),
        migrations.CreateModel(
            name=r'Story',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'story_points', models.PositiveSmallIntegerField(default=1)),
                (r'priority', models.CharField(default='medium', max_length=20)),
                (r'status', models.CharField(default='backlog', max_length=20)),
                (r'assignee_id', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='workspace.epic')),
            ],
            options={
                r'db_table': 'pm_story',
            },
        ),
        migrations.CreateModel(
            name=r'TestRun',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('blocked', 'Blocked')], max_length=20)),
                (r'actual_result', models.TextField(blank=True)),
                (r'run_by', models.CharField(max_length=50)),
                (r'run_at', models.DateTimeField(auto_now_add=True)),
                (r'test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workspace.testcase')),
            ],
            options={
                r'db_table': 'pm_test_run',
            },
        ),
        migrations.CreateModel(
            name=r'VideoCallParticipant',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'joined_at', models.DateTimeField(auto_now_add=True)),
                (r'left_at', models.DateTimeField(null=True)),
                (r'is_host', models.BooleanField(default=False)),
                (r'call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='workspace.videocall')),
            ],
            options={
                r'db_table': 'comms_video_participant',
            },
        ),
    ]
