# Generated by Django 6.0.1 on 2026-03-15 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0011_announcement_benefitplan_bug_dependency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'AccountingEntry',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                (r'account', models.CharField(max_length=100)),
                (r'amount', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'description', models.TextField()),
                (r'reference', models.CharField(blank=True, max_length=100)),
                (r'entry_date', models.DateField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'fin_entry',
            },
        ),
        migrations.CreateModel(
            name=r'Budget',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'category', models.CharField(max_length=50)),
                (r'allocated', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'period_start', models.DateField()),
                (r'period_end', models.DateField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'fin_budget',
            },
        ),
        migrations.CreateModel(
            name=r'CurrencyRate',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'from_currency', models.CharField(max_length=3)),
                (r'to_currency', models.CharField(max_length=3)),
                (r'rate', models.DecimalField(decimal_places=6, max_digits=15)),
                (r'date', models.DateField()),
                (r'source', models.CharField(default='manual', max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'fin_currency',
            },
        ),
        migrations.CreateModel(
            name=r'Customer',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'email', models.EmailField(max_length=254)),
                (r'phone', models.CharField(blank=True, max_length=20)),
                (r'company', models.CharField(blank=True, max_length=100)),
                (r'industry', models.CharField(blank=True, max_length=50)),
                (r'status', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('customer', 'Customer'), ('churned', 'Churned')], default='lead', max_length=20)),
                (r'source', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'crm_customer',
            },
        ),
        migrations.CreateModel(
            name=r'CustomerSegment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'criteria', models.JSONField(default=dict)),
                (r'customer_count', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'crm_segment',
            },
        ),
        migrations.CreateModel(
            name=r'Expense',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'amount', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'currency', models.CharField(default='IDR', max_length=3)),
                (r'category', models.CharField(max_length=50)),
                (r'description', models.TextField(blank=True)),
                (r'receipt_cid', models.TextField(blank=True)),
                (r'submitted_by', models.CharField(max_length=50)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'approved_by', models.CharField(blank=True, max_length=50)),
                (r'expense_date', models.DateField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'fin_expense',
            },
        ),
        migrations.CreateModel(
            name=r'FAQ',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'question', models.TextField()),
                (r'answer', models.TextField()),
                (r'category', models.CharField(blank=True, max_length=100)),
                (r'order', models.PositiveSmallIntegerField(default=0)),
                (r'is_published', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'km_faq',
            },
        ),
        migrations.CreateModel(
            name=r'FinancialReport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'report_type', models.CharField(choices=[('income', 'Income Statement'), ('balance', 'Balance Sheet'), ('cashflow', 'Cash Flow'), ('budget', 'Budget Report')], max_length=50)),
                (r'period', models.CharField(max_length=20)),
                (r'data', models.JSONField(default=dict)),
                (r'generated_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'fin_report',
            },
        ),
        migrations.CreateModel(
            name=r'Glossary',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'term', models.CharField(max_length=100)),
                (r'definition', models.TextField()),
                (r'category', models.CharField(blank=True, max_length=50)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'km_glossary',
            },
        ),
        migrations.CreateModel(
            name=r'Invoice',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'invoice_number', models.CharField(max_length=50, unique=True)),
                (r'client_name', models.CharField(max_length=100)),
                (r'client_email', models.EmailField(max_length=254)),
                (r'items', models.JSONField(default=list)),
                (r'subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'total', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                (r'due_date', models.DateField()),
                (r'paid_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'fin_invoice',
            },
        ),
        migrations.CreateModel(
            name=r'KBArticle',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'content', models.TextField()),
                (r'category', models.CharField(blank=True, max_length=100)),
                (r'tags', models.JSONField(default=list)),
                (r'views', models.PositiveIntegerField(default=0)),
                (r'helpful_count', models.PositiveIntegerField(default=0)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                r'db_table': 'km_article',
            },
        ),
        migrations.CreateModel(
            name=r'KnowledgeBase',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'description', models.TextField(blank=True)),
                (r'is_public', models.BooleanField(default=False)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'km_knowledge_base',
            },
        ),
        migrations.CreateModel(
            name=r'LearningPath',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField()),
                (r'level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                (r'estimated_hours', models.FloatField(default=0)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'km_learning_path',
            },
        ),
        migrations.CreateModel(
            name=r'MarketingCampaign',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'campaign_type', models.CharField(choices=[('email', 'Email'), ('social', 'Social Media'), ('ads', 'Paid Ads'), ('event', 'Event')], max_length=20)),
                (r'budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'leads_generated', models.PositiveIntegerField(default=0)),
                (r'start_date', models.DateField()),
                (r'end_date', models.DateField(null=True)),
                (r'status', models.CharField(default='draft', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'crm_campaign',
            },
        ),
        migrations.CreateModel(
            name=r'Pipeline',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'stages', models.JSONField(default=list)),
                (r'is_default', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'crm_pipeline',
            },
        ),
        migrations.CreateModel(
            name=r'Subscription',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'service_name', models.CharField(max_length=100)),
                (r'amount', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'currency', models.CharField(default='IDR', max_length=3)),
                (r'billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                (r'next_billing', models.DateField()),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'fin_subscription',
            },
        ),
        migrations.CreateModel(
            name=r'TaxRecord',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'tax_type', models.CharField(choices=[('vat', 'VAT'), ('income', 'Income Tax'), ('corporate', 'Corporate Tax'), ('withholding', 'Withholding Tax')], max_length=50)),
                (r'period', models.CharField(max_length=20)),
                (r'amount', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'filed_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'fin_tax',
            },
        ),
        migrations.CreateModel(
            name=r'CRMActivity',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'activity_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Demo'), ('follow_up', 'Follow Up')], max_length=20)),
                (r'subject', models.CharField(max_length=255)),
                (r'notes', models.TextField(blank=True)),
                (r'outcome', models.CharField(blank=True, max_length=100)),
                (r'performed_by', models.CharField(max_length=50)),
                (r'activity_date', models.DateTimeField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workspace.customer')),
            ],
            options={
                r'db_table': 'crm_activity',
            },
        ),
        migrations.CreateModel(
            name=r'CustomerFeedback',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                (r'feedback', models.TextField(blank=True)),
                (r'category', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.customer')),
            ],
            options={
                r'db_table': 'crm_feedback',
            },
        ),
        migrations.CreateModel(
            name=r'CustomerNote',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'content', models.TextField()),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workspace.customer')),
            ],
            options={
                r'db_table': 'crm_note',
            },
        ),
        migrations.CreateModel(
            name=r'Deal',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'stage', models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], default='prospecting', max_length=20)),
                (r'probability', models.PositiveSmallIntegerField(default=0)),
                (r'expected_close', models.DateField(null=True)),
                (r'assigned_to', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='workspace.customer')),
            ],
            options={
                r'db_table': 'crm_deal',
            },
        ),
        migrations.CreateModel(
            name=r'KBArticleVersion',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'content', models.TextField()),
                (r'version', models.PositiveIntegerField(default=1)),
                (r'edited_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workspace.kbarticle')),
            ],
            options={
                r'db_table': 'km_article_version',
            },
        ),
        migrations.CreateModel(
            name=r'KBComment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'author_id', models.CharField(max_length=50)),
                (r'content', models.TextField()),
                (r'is_helpful', models.BooleanField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_comments', to='workspace.kbarticle')),
            ],
            options={
                r'db_table': 'km_comment',
            },
        ),
        migrations.AddField(
            model_name=r'kbarticle',
            name=r'kb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name=r'articles', to='workspace.knowledgebase'),
        ),
        migrations.CreateModel(
            name=r'LearningModule',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'content', models.TextField()),
                (r'module_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('quiz', 'Quiz'), ('exercise', 'Exercise')], max_length=20)),
                (r'duration_minutes', models.PositiveSmallIntegerField(default=0)),
                (r'order', models.PositiveSmallIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='workspace.learningpath')),
            ],
            options={
                r'db_table': 'km_module',
            },
        ),
        migrations.CreateModel(
            name=r'LearningProgress',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'completed_modules', models.JSONField(default=list)),
                (r'progress_percent', models.FloatField(default=0)),
                (r'started_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_at', models.DateTimeField(null=True)),
                (r'path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.learningpath')),
            ],
            options={
                r'db_table': 'km_progress',
            },
        ),
        migrations.CreateModel(
            name=r'Payment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'amount', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('cash', 'Cash'), ('crypto', 'Crypto')], max_length=50)),
                (r'reference', models.CharField(blank=True, max_length=100)),
                (r'paid_at', models.DateTimeField(auto_now_add=True)),
                (r'invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workspace.invoice')),
            ],
            options={
                r'db_table': 'fin_payment',
            },
        ),
        migrations.CreateModel(
            name=r'Quiz',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'question', models.TextField()),
                (r'options', models.JSONField(default=list)),
                (r'correct_answer', models.PositiveSmallIntegerField()),
                (r'explanation', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='workspace.learningmodule')),
            ],
            options={
                r'db_table': 'km_quiz',
            },
        ),
        migrations.CreateModel(
            name=r'Reimbursement',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'amount', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'processed_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.expense')),
            ],
            options={
                r'db_table': 'fin_reimbursement',
            },
        ),
        migrations.CreateModel(
            name=r'SupportTicket',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'subject', models.CharField(max_length=255)),
                (r'description', models.TextField()),
                (r'priority', models.CharField(default='medium', max_length=20)),
                (r'status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                (r'assigned_to', models.CharField(blank=True, max_length=50)),
                (r'resolved_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='workspace.customer')),
            ],
            options={
                r'db_table': 'crm_ticket',
            },
        ),
        migrations.CreateModel(
            name=r'TicketReply',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'content', models.TextField()),
                (r'is_internal', models.BooleanField(default=False)),
                (r'author_id', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='workspace.supportticket')),
            ],
            options={
                r'db_table': 'crm_reply',
            },
        ),
    ]
