# Generated by Django 6.0.1 on 2026-03-15 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0012_accountingentry_budget_currencyrate_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'ABTest',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'hypothesis', models.TextField()),
                (r'variants', models.JSONField(default=list)),
                (r'metric', models.CharField(max_length=100)),
                (r'status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='draft', max_length=20)),
                (r'started_at', models.DateTimeField(null=True)),
                (r'ended_at', models.DateTimeField(null=True)),
                (r'winner', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'analytics_abtest',
            },
        ),
        migrations.CreateModel(
            name=r'APIMetric',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'endpoint', models.CharField(max_length=255)),
                (r'method', models.CharField(max_length=10)),
                (r'status_code', models.PositiveSmallIntegerField()),
                (r'response_time_ms', models.PositiveIntegerField()),
                (r'user_id', models.CharField(blank=True, max_length=50)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_metric',
            },
        ),
        migrations.CreateModel(
            name=r'CIBuild',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'repo', models.CharField(max_length=255)),
                (r'branch', models.CharField(max_length=100)),
                (r'commit_hash', models.CharField(max_length=40)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], max_length=20)),
                (r'duration_seconds', models.PositiveIntegerField(default=0)),
                (r'triggered_by', models.CharField(max_length=50)),
                (r'started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_ci_build',
            },
        ),
        migrations.CreateModel(
            name=r'Cohort',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'criteria', models.JSONField(default=dict)),
                (r'user_count', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'analytics_cohort',
            },
        ),
        migrations.CreateModel(
            name=r'CustomDimension',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'dimension_type', models.CharField(choices=[('user', 'User'), ('session', 'Session'), ('event', 'Event')], max_length=20)),
                (r'description', models.TextField(blank=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'analytics_dimension',
            },
        ),
        migrations.CreateModel(
            name=r'DashboardWidget',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'user_id', models.CharField(max_length=50)),
                (r'widget_type', models.CharField(choices=[('chart', 'Chart'), ('table', 'Table'), ('metric', 'Metric'), ('list', 'List'), ('map', 'Map')], max_length=50)),
                (r'title', models.CharField(max_length=100)),
                (r'config', models.JSONField(default=dict)),
                (r'position_x', models.PositiveSmallIntegerField(default=0)),
                (r'position_y', models.PositiveSmallIntegerField(default=0)),
                (r'width', models.PositiveSmallIntegerField(default=4)),
                (r'height', models.PositiveSmallIntegerField(default=3)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'analytics_widget',
            },
        ),
        migrations.CreateModel(
            name=r'DatabaseBackup',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'database_name', models.CharField(max_length=100)),
                (r'size_mb', models.PositiveIntegerField(default=0)),
                (r'storage_cid', models.TextField(blank=True)),
                (r'backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], max_length=20)),
                (r'status', models.CharField(default='completed', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_backup',
            },
        ),
        migrations.CreateModel(
            name=r'Deployment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'service_name', models.CharField(max_length=100)),
                (r'version', models.CharField(max_length=50)),
                (r'environment', models.CharField(choices=[('dev', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=20)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('success', 'Success'), ('failed', 'Failed'), ('rollback', 'Rollback')], max_length=20)),
                (r'deployed_by', models.CharField(max_length=50)),
                (r'started_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_at', models.DateTimeField(null=True)),
                (r'logs', models.TextField(blank=True)),
            ],
            options={
                r'db_table': 'devops_deployment',
            },
        ),
        migrations.CreateModel(
            name=r'DockerImage',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=255)),
                (r'tag', models.CharField(max_length=100)),
                (r'size_mb', models.PositiveIntegerField(default=0)),
                (r'digest', models.CharField(blank=True, max_length=100)),
                (r'pushed_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_image',
            },
        ),
        migrations.CreateModel(
            name=r'ErrorTracking',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'error_type', models.CharField(max_length=100)),
                (r'message', models.TextField()),
                (r'stack_trace', models.TextField(blank=True)),
                (r'service', models.CharField(max_length=100)),
                (r'count', models.PositiveIntegerField(default=1)),
                (r'first_seen', models.DateTimeField(auto_now_add=True)),
                (r'last_seen', models.DateTimeField(auto_now=True)),
                (r'is_resolved', models.BooleanField(default=False)),
            ],
            options={
                r'db_table': 'devops_error',
            },
        ),
        migrations.CreateModel(
            name=r'EventTracking',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'event_name', models.CharField(max_length=100)),
                (r'properties', models.JSONField(default=dict)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'analytics_event',
            },
        ),
        migrations.CreateModel(
            name=r'FeatureFlag',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'description', models.TextField(blank=True)),
                (r'is_enabled', models.BooleanField(default=False)),
                (r'rollout_percent', models.PositiveSmallIntegerField(default=0)),
                (r'environments', models.JSONField(default=list)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_flag',
            },
        ),
        migrations.CreateModel(
            name=r'FunnelStep',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'funnel_name', models.CharField(max_length=100)),
                (r'step_name', models.CharField(max_length=100)),
                (r'step_order', models.PositiveSmallIntegerField()),
                (r'users_entered', models.PositiveIntegerField(default=0)),
                (r'users_completed', models.PositiveIntegerField(default=0)),
                (r'conversion_rate', models.FloatField(default=0)),
                (r'date', models.DateField()),
            ],
            options={
                r'db_table': 'analytics_funnel',
            },
        ),
        migrations.CreateModel(
            name=r'GoalTracking',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'goal_name', models.CharField(max_length=100)),
                (r'target_value', models.FloatField()),
                (r'current_value', models.FloatField(default=0)),
                (r'unit', models.CharField(blank=True, max_length=20)),
                (r'deadline', models.DateField(null=True)),
                (r'status', models.CharField(default='in_progress', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'analytics_goal',
            },
        ),
        migrations.CreateModel(
            name=r'HeatmapData',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'page_path', models.CharField(max_length=255)),
                (r'click_x', models.PositiveSmallIntegerField()),
                (r'click_y', models.PositiveSmallIntegerField()),
                (r'element', models.CharField(blank=True, max_length=255)),
                (r'user_id', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'analytics_heatmap',
            },
        ),
        migrations.CreateModel(
            name=r'InfrastructureCost',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'provider', models.CharField(max_length=50)),
                (r'service_name', models.CharField(max_length=100)),
                (r'cost', models.DecimalField(decimal_places=2, max_digits=10)),
                (r'currency', models.CharField(default='USD', max_length=3)),
                (r'period', models.CharField(max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_cost',
            },
        ),
        migrations.CreateModel(
            name=r'K8sCluster',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'provider', models.CharField(choices=[('aws', 'AWS EKS'), ('gcp', 'GCP GKE'), ('azure', 'Azure AKS'), ('self', 'Self-hosted')], max_length=20)),
                (r'region', models.CharField(max_length=50)),
                (r'node_count', models.PositiveSmallIntegerField(default=1)),
                (r'status', models.CharField(default='active', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_k8s',
            },
        ),
        migrations.CreateModel(
            name=r'LogEntry',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'service', models.CharField(max_length=100)),
                (r'level', models.CharField(max_length=10)),
                (r'message', models.TextField()),
                (r'trace', models.TextField(blank=True)),
                (r'metadata', models.JSONField(default=dict)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_log',
            },
        ),
        migrations.CreateModel(
            name=r'Metric',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'value', models.FloatField()),
                (r'unit', models.CharField(blank=True, max_length=20)),
                (r'tags', models.JSONField(default=dict)),
                (r'recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'analytics_metric',
            },
        ),
        migrations.CreateModel(
            name=r'MonitoringAlert',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'service', models.CharField(max_length=100)),
                (r'alert_type', models.CharField(max_length=50)),
                (r'severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                (r'message', models.TextField()),
                (r'is_resolved', models.BooleanField(default=False)),
                (r'resolved_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_alert',
            },
        ),
        migrations.CreateModel(
            name=r'Report',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'report_type', models.CharField(max_length=50)),
                (r'filters', models.JSONField(default=dict)),
                (r'schedule', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('manual', 'Manual')], default='manual', max_length=20)),
                (r'recipients', models.JSONField(default=list)),
                (r'last_run', models.DateTimeField(null=True)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'analytics_report',
            },
        ),
        migrations.CreateModel(
            name=r'RetentionData',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'cohort_date', models.DateField()),
                (r'period', models.PositiveSmallIntegerField()),
                (r'users', models.PositiveIntegerField(default=0)),
                (r'retained', models.PositiveIntegerField(default=0)),
                (r'retention_rate', models.FloatField(default=0)),
            ],
            options={
                r'db_table': 'analytics_retention',
            },
        ),
        migrations.CreateModel(
            name=r'SearchAnalytic',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'query', models.CharField(max_length=255)),
                (r'results_count', models.PositiveIntegerField(default=0)),
                (r'clicked_result', models.CharField(blank=True, max_length=255)),
                (r'user_id', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'analytics_search',
            },
        ),
        migrations.CreateModel(
            name=r'Server',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'hostname', models.CharField(max_length=255)),
                (r'ip_address', models.GenericIPAddressField()),
                (r'server_type', models.CharField(choices=[('web', 'Web'), ('db', 'Database'), ('cache', 'Cache'), ('queue', 'Queue'), ('storage', 'Storage'), ('cdn', 'CDN')], max_length=20)),
                (r'os', models.CharField(blank=True, max_length=50)),
                (r'cpu_cores', models.PositiveSmallIntegerField(default=1)),
                (r'ram_gb', models.PositiveSmallIntegerField(default=1)),
                (r'disk_gb', models.PositiveIntegerField(default=50)),
                (r'status', models.CharField(default='running', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_server',
            },
        ),
        migrations.CreateModel(
            name=r'ServiceHealth',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'service_name', models.CharField(max_length=100)),
                (r'status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], max_length=20)),
                (r'response_time_ms', models.PositiveIntegerField(default=0)),
                (r'uptime_percent', models.FloatField(default=100.0)),
                (r'checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_health',
            },
        ),
        migrations.CreateModel(
            name=r'SLAReport',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'service', models.CharField(max_length=100)),
                (r'period', models.CharField(max_length=20)),
                (r'uptime_percent', models.FloatField()),
                (r'avg_response_ms', models.FloatField()),
                (r'incidents', models.PositiveSmallIntegerField(default=0)),
                (r'sla_met', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'devops_sla',
            },
        ),
        migrations.CreateModel(
            name=r'UserSession',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'device', models.CharField(blank=True, max_length=50)),
                (r'browser', models.CharField(blank=True, max_length=50)),
                (r'os', models.CharField(blank=True, max_length=50)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'started_at', models.DateTimeField(auto_now_add=True)),
                (r'ended_at', models.DateTimeField(null=True)),
                (r'duration_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                r'db_table': 'analytics_session',
            },
        ),
        migrations.CreateModel(
            name=r'K8sPod',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=255)),
                (r'namespace', models.CharField(default='default', max_length=100)),
                (r'status', models.CharField(max_length=20)),
                (r'cpu_usage', models.FloatField(default=0)),
                (r'memory_mb', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pods', to='workspace.k8scluster')),
            ],
            options={
                r'db_table': 'devops_pod',
            },
        ),
        migrations.CreateModel(
            name=r'ReportRun',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'status', models.CharField(default='completed', max_length=20)),
                (r'file_cid', models.TextField(blank=True)),
                (r'row_count', models.PositiveIntegerField(default=0)),
                (r'ran_at', models.DateTimeField(auto_now_add=True)),
                (r'report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workspace.report')),
            ],
            options={
                r'db_table': 'analytics_run',
            },
        ),
        migrations.CreateModel(
            name=r'PageView',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'path', models.CharField(max_length=255)),
                (r'duration_seconds', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='workspace.usersession')),
            ],
            options={
                r'db_table': 'analytics_pageview',
            },
        ),
    ]
