# Generated by Django 6.0.1 on 2026-03-15 22:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0013_abtest_apimetric_cibuild_cohort_customdimension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'AccessPolicy',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'description', models.TextField(blank=True)),
                (r'rules', models.JSONField(default=list)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sec_policy',
            },
        ),
        migrations.CreateModel(
            name=r'AuditTrail',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'user_id', models.CharField(max_length=50)),
                (r'action', models.CharField(max_length=50)),
                (r'resource', models.CharField(max_length=50)),
                (r'resource_id', models.CharField(max_length=50)),
                (r'changes', models.JSONField(default=dict)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'user_agent', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sec_trail',
            },
        ),
        migrations.CreateModel(
            name=r'BlockedIP',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'ip_address', models.GenericIPAddressField()),
                (r'reason', models.TextField(blank=True)),
                (r'blocked_by', models.CharField(max_length=50)),
                (r'expires_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sec_blocked_ip',
            },
        ),
        migrations.CreateModel(
            name=r'Brand',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50, unique=True)),
                (r'logo_cid', models.TextField(blank=True)),
                (r'primary_color', models.CharField(default='#6366f1', max_length=7)),
                (r'secondary_color', models.CharField(default='#8b5cf6', max_length=7)),
                (r'font_primary', models.CharField(default='Inter', max_length=50)),
                (r'font_secondary', models.CharField(default='Inter', max_length=50)),
                (r'guidelines_cid', models.TextField(blank=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                r'db_table': 'media_brand',
            },
        ),
        migrations.CreateModel(
            name=r'ContentBlock',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'block_type', models.CharField(choices=[('text', 'Text'), ('heading', 'Heading'), ('image', 'Image'), ('code', 'Code'), ('table', 'Table'), ('divider', 'Divider'), ('callout', 'Callout')], max_length=20)),
                (r'content', models.JSONField(default=dict)),
                (r'order', models.PositiveSmallIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'media_block',
            },
        ),
        migrations.CreateModel(
            name=r'DataClassification',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'resource_type', models.CharField(max_length=50)),
                (r'resource_id', models.CharField(max_length=50)),
                (r'classification', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential'), ('secret', 'Secret'), ('top_secret', 'Top Secret')], max_length=20)),
                (r'classified_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sec_classification',
            },
        ),
        migrations.CreateModel(
            name=r'DiagramCanvas',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'diagram_type', models.CharField(choices=[('flowchart', 'Flowchart'), ('er', 'ER Diagram'), ('sequence', 'Sequence'), ('mindmap', 'Mind Map'), ('org', 'Org Chart')], max_length=20)),
                (r'content', models.JSONField(default=dict)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'media_diagram',
            },
        ),
        migrations.CreateModel(
            name=r'FormBuilder',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'fields', models.JSONField(default=list)),
                (r'settings', models.JSONField(default=dict)),
                (r'is_published', models.BooleanField(default=False)),
                (r'response_count', models.PositiveIntegerField(default=0)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'media_form',
            },
        ),
        migrations.CreateModel(
            name=r'LoginAttempt',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(blank=True, max_length=50)),
                (r'username', models.CharField(max_length=100)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'is_success', models.BooleanField(default=False)),
                (r'failure_reason', models.CharField(blank=True, max_length=100)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sec_login',
            },
        ),
        migrations.CreateModel(
            name=r'MediaFile',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'filename', models.CharField(max_length=255)),
                (r'original_name', models.CharField(max_length=255)),
                (r'file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('archive', 'Archive')], max_length=20)),
                (r'mime_type', models.CharField(max_length=100)),
                (r'size_bytes', models.BigIntegerField(default=0)),
                (r'ipfs_cid', models.TextField(blank=True)),
                (r'thumbnail_cid', models.TextField(blank=True)),
                (r'uploaded_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'media_file',
            },
        ),
        migrations.CreateModel(
            name=r'MediaTag',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=50)),
                (r'color', models.CharField(default='#6366f1', max_length=7)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'media_tag',
            },
        ),
        migrations.CreateModel(
            name=r'Permission',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100, unique=True)),
                (r'codename', models.CharField(max_length=100, unique=True)),
                (r'description', models.TextField(blank=True)),
                (r'resource', models.CharField(max_length=50)),
                (r'action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('manage', 'Manage')], max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sec_permission',
            },
        ),
        migrations.CreateModel(
            name=r'Presentation',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'slides', models.JSONField(default=list)),
                (r'theme', models.CharField(default='default', max_length=50)),
                (r'is_published', models.BooleanField(default=False)),
                (r'view_count', models.PositiveIntegerField(default=0)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'media_presentation',
            },
        ),
        migrations.CreateModel(
            name=r'Role',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=50)),
                (r'permissions', models.JSONField(default=list)),
                (r'is_system', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sec_role',
            },
        ),
        migrations.CreateModel(
            name=r'SecurityIncident',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'incident_type', models.CharField(max_length=50)),
                (r'severity', models.CharField(max_length=20)),
                (r'description', models.TextField()),
                (r'affected_users', models.JSONField(default=list)),
                (r'status', models.CharField(default='open', max_length=20)),
                (r'resolved_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sec_incident',
            },
        ),
        migrations.CreateModel(
            name=r'SecurityPolicy',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50, unique=True)),
                (r'min_password_length', models.PositiveSmallIntegerField(default=8)),
                (r'require_uppercase', models.BooleanField(default=True)),
                (r'require_numbers', models.BooleanField(default=True)),
                (r'require_symbols', models.BooleanField(default=False)),
                (r'password_expiry_days', models.PositiveSmallIntegerField(default=90)),
                (r'max_login_attempts', models.PositiveSmallIntegerField(default=5)),
                (r'session_timeout_minutes', models.PositiveSmallIntegerField(default=60)),
                (r'require_mfa', models.BooleanField(default=False)),
                (r'ip_whitelist', models.JSONField(default=list)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                r'db_table': 'sec_security_policy',
            },
        ),
        migrations.CreateModel(
            name=r'Spreadsheet',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'sheets', models.JSONField(default=list)),
                (r'is_published', models.BooleanField(default=False)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                r'db_table': 'media_spreadsheet',
            },
        ),
        migrations.CreateModel(
            name=r'Survey',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'questions', models.JSONField(default=list)),
                (r'is_anonymous', models.BooleanField(default=False)),
                (r'closes_at', models.DateTimeField(null=True)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'media_survey',
            },
        ),
        migrations.CreateModel(
            name=r'Template',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'category', models.CharField(max_length=50)),
                (r'blocks', models.JSONField(default=list)),
                (r'thumbnail_cid', models.TextField(blank=True)),
                (r'is_public', models.BooleanField(default=False)),
                (r'use_count', models.PositiveIntegerField(default=0)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'media_template',
            },
        ),
        migrations.CreateModel(
            name=r'Whiteboard',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'content', models.JSONField(default=dict)),
                (r'thumbnail_cid', models.TextField(blank=True)),
                (r'collaborators', models.JSONField(default=list)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                r'db_table': 'media_whiteboard',
            },
        ),
        migrations.CreateModel(
            name=r'FormResponse',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'respondent_id', models.CharField(blank=True, max_length=50)),
                (r'data', models.JSONField(default=dict)),
                (r'submitted_at', models.DateTimeField(auto_now_add=True)),
                (r'form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='workspace.formbuilder')),
            ],
            options={
                r'db_table': 'media_form_response',
            },
        ),
        migrations.CreateModel(
            name=r'MediaFolder',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfolders', to='workspace.mediafolder')),
            ],
            options={
                r'db_table': 'media_folder',
            },
        ),
        migrations.CreateModel(
            name=r'MediaShare',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'shared_by', models.CharField(max_length=50)),
                (r'shared_with', models.CharField(blank=True, max_length=50)),
                (r'share_link', models.CharField(max_length=100, unique=True)),
                (r'expires_at', models.DateTimeField(null=True)),
                (r'download_count', models.PositiveIntegerField(default=0)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='workspace.mediafile')),
            ],
            options={
                r'db_table': 'media_share',
            },
        ),
        migrations.CreateModel(
            name=r'MediaFileTag',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='workspace.mediafile')),
                (r'tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.mediatag')),
            ],
            options={
                r'db_table': 'media_file_tag',
            },
        ),
        migrations.CreateModel(
            name=r'RoleAssignment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'assigned_by', models.CharField(max_length=50)),
                (r'expires_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.role')),
            ],
            options={
                r'db_table': 'sec_role_assignment',
            },
        ),
        migrations.CreateModel(
            name=r'SurveyResponse',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'respondent_id', models.CharField(blank=True, max_length=50)),
                (r'answers', models.JSONField(default=dict)),
                (r'submitted_at', models.DateTimeField(auto_now_add=True)),
                (r'survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='workspace.survey')),
            ],
            options={
                r'db_table': 'media_survey_response',
            },
        ),
    ]
