# Generated by Django 6.0.1 on 2026-03-15 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0014_accesspolicy_audittrail_blockedip_brand_contentblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'AIInsight',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'insight_type', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField()),
                (r'data', models.JSONField(default=dict)),
                (r'confidence', models.FloatField(default=0)),
                (r'is_dismissed', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'ai_insight',
            },
        ),
        migrations.CreateModel(
            name=r'AIModel',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'model_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('nlp', 'NLP'), ('vision', 'Vision'), ('recommendation', 'Recommendation')], max_length=50)),
                (r'version', models.CharField(max_length=20)),
                (r'accuracy', models.FloatField(default=0)),
                (r'is_active', models.BooleanField(default=True)),
                (r'config', models.JSONField(default=dict)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'ai_model',
            },
        ),
        migrations.CreateModel(
            name=r'AIUsageLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'user_id', models.CharField(max_length=50)),
                (r'feature', models.CharField(max_length=50)),
                (r'tokens_used', models.PositiveIntegerField(default=0)),
                (r'cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'ai_usage',
            },
        ),
        migrations.CreateModel(
            name=r'AssetMaintenance',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'asset_name', models.CharField(max_length=100)),
                (r'maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('emergency', 'Emergency')], max_length=20)),
                (r'description', models.TextField()),
                (r'cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'performed_by', models.CharField(max_length=50)),
                (r'scheduled_date', models.DateField()),
                (r'completed_date', models.DateField(null=True)),
                (r'status', models.CharField(default='scheduled', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'inv_maintenance',
            },
        ),
        migrations.CreateModel(
            name=r'AutomationRule',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'description', models.TextField(blank=True)),
                (r'trigger_event', models.CharField(max_length=50)),
                (r'conditions', models.JSONField(default=list)),
                (r'actions', models.JSONField(default=list)),
                (r'is_active', models.BooleanField(default=True)),
                (r'run_count', models.PositiveIntegerField(default=0)),
                (r'last_run', models.DateTimeField(null=True)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'ai_automation',
            },
        ),
        migrations.CreateModel(
            name=r'CalendarSubscription',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'calendar_type', models.CharField(choices=[('google', 'Google'), ('outlook', 'Outlook'), ('apple', 'Apple'), ('ical', 'iCal')], max_length=20)),
                (r'sync_url', models.URLField(blank=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'last_synced', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'event_cal_sub',
            },
        ),
        migrations.CreateModel(
            name=r'ChatbotFlow',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'trigger_keywords', models.JSONField(default=list)),
                (r'flow_nodes', models.JSONField(default=list)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'ai_flow',
            },
        ),
        migrations.CreateModel(
            name=r'ContentModeration',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'content_type', models.CharField(max_length=20)),
                (r'content_id', models.CharField(max_length=50)),
                (r'flags', models.JSONField(default=list)),
                (r'action_taken', models.CharField(blank=True, max_length=20)),
                (r'reviewed_by', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'ai_moderation',
            },
        ),
        migrations.CreateModel(
            name=r'Event',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'event_type', models.CharField(choices=[('company', 'Company'), ('team', 'Team'), ('training', 'Training'), ('social', 'Social'), ('external', 'External')], max_length=50)),
                (r'location', models.CharField(blank=True, max_length=255)),
                (r'is_virtual', models.BooleanField(default=False)),
                (r'meeting_url', models.URLField(blank=True)),
                (r'start_time', models.DateTimeField()),
                (r'end_time', models.DateTimeField()),
                (r'all_day', models.BooleanField(default=False)),
                (r'is_recurring', models.BooleanField(default=False)),
                (r'recurrence_rule', models.CharField(blank=True, max_length=100)),
                (r'color', models.CharField(default='#6366f1', max_length=7)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'event_event',
            },
        ),
        migrations.CreateModel(
            name=r'Holiday',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'date', models.DateField()),
                (r'country', models.CharField(default='ID', max_length=2)),
                (r'is_optional', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'event_holiday',
            },
        ),
        migrations.CreateModel(
            name=r'Product',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=255)),
                (r'sku', models.CharField(max_length=50)),
                (r'category', models.CharField(max_length=50)),
                (r'unit', models.CharField(max_length=20)),
                (r'unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'stock', models.PositiveIntegerField(default=0)),
                (r'min_stock', models.PositiveIntegerField(default=0)),
                (r'description', models.TextField(blank=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'inv_product',
            },
        ),
        migrations.CreateModel(
            name=r'SentimentAnalysis',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'source_type', models.CharField(max_length=20)),
                (r'source_id', models.CharField(max_length=50)),
                (r'sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                (r'score', models.FloatField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'ai_sentiment',
            },
        ),
        migrations.CreateModel(
            name=r'ShipmentTracking',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'tracking_number', models.CharField(max_length=100)),
                (r'carrier', models.CharField(max_length=50)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed')], max_length=20)),
                (r'origin', models.CharField(max_length=100)),
                (r'destination', models.CharField(max_length=100)),
                (r'estimated_delivery', models.DateField(null=True)),
                (r'events', models.JSONField(default=list)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'inv_shipment',
            },
        ),
        migrations.CreateModel(
            name=r'SmartSuggestion',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'suggestion_type', models.CharField(max_length=50)),
                (r'content', models.TextField()),
                (r'context', models.JSONField(default=dict)),
                (r'is_accepted', models.BooleanField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'ai_suggestion',
            },
        ),
        migrations.CreateModel(
            name=r'TeamOuting',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField()),
                (r'date', models.DateField()),
                (r'location', models.CharField(max_length=255)),
                (r'budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'max_participants', models.PositiveSmallIntegerField(default=50)),
                (r'status', models.CharField(default='planning', max_length=20)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'event_outing',
            },
        ),
        migrations.CreateModel(
            name=r'TranslationCache',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'source_text_hash', models.CharField(max_length=64)),
                (r'source_lang', models.CharField(max_length=10)),
                (r'target_lang', models.CharField(max_length=10)),
                (r'translated_text', models.TextField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'ai_translation',
            },
        ),
        migrations.CreateModel(
            name=r'Vendor',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'email', models.EmailField(max_length=254)),
                (r'phone', models.CharField(blank=True, max_length=20)),
                (r'address', models.TextField(blank=True)),
                (r'category', models.CharField(max_length=50)),
                (r'rating', models.FloatField(default=0)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'inv_vendor',
            },
        ),
        migrations.CreateModel(
            name=r'Warehouse',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'address', models.TextField()),
                (r'capacity', models.PositiveIntegerField(default=0)),
                (r'manager_id', models.CharField(blank=True, max_length=50)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'inv_warehouse',
            },
        ),
        migrations.CreateModel(
            name=r'WorkSchedule',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'schedule', models.JSONField(default=dict)),
                (r'timezone', models.CharField(default='Asia/Jakarta', max_length=50)),
                (r'is_default', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'event_schedule',
            },
        ),
        migrations.CreateModel(
            name=r'AIJob',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'job_type', models.CharField(choices=[('train', 'Train'), ('predict', 'Predict'), ('evaluate', 'Evaluate')], max_length=20)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'input_data', models.JSONField(default=dict)),
                (r'output_data', models.JSONField(default=dict)),
                (r'started_at', models.DateTimeField(null=True)),
                (r'completed_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='workspace.aimodel')),
            ],
            options={
                r'db_table': 'ai_job',
            },
        ),
        migrations.CreateModel(
            name=r'EventAttendee',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative')], max_length=20)),
                (r'responded_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='workspace.event')),
            ],
            options={
                r'db_table': 'event_attendee',
            },
        ),
        migrations.CreateModel(
            name=r'EventReminder',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'remind_before_minutes', models.PositiveSmallIntegerField(default=15)),
                (r'is_sent', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='workspace.event')),
            ],
            options={
                r'db_table': 'event_reminder',
            },
        ),
        migrations.CreateModel(
            name=r'QualityCheck',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'checked_by', models.CharField(max_length=50)),
                (r'result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('partial', 'Partial')], max_length=20)),
                (r'notes', models.TextField(blank=True)),
                (r'defects', models.JSONField(default=list)),
                (r'checked_at', models.DateTimeField(auto_now_add=True)),
                (r'product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.product')),
            ],
            options={
                r'db_table': 'inv_quality',
            },
        ),
        migrations.CreateModel(
            name=r'RoomBooking',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'room_name', models.CharField(max_length=100)),
                (r'booked_by', models.CharField(max_length=50)),
                (r'start_time', models.DateTimeField()),
                (r'end_time', models.DateTimeField()),
                (r'attendee_count', models.PositiveSmallIntegerField(default=1)),
                (r'status', models.CharField(default='confirmed', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.event')),
            ],
            options={
                r'db_table': 'event_room',
            },
        ),
        migrations.CreateModel(
            name=r'StockMovement',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'movement_type', models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('adjust', 'Adjust')], max_length=10)),
                (r'quantity', models.IntegerField()),
                (r'reason', models.CharField(max_length=100)),
                (r'reference', models.CharField(blank=True, max_length=100)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='workspace.product')),
            ],
            options={
                r'db_table': 'inv_movement',
            },
        ),
        migrations.CreateModel(
            name=r'TeamOutingRSVP',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'status', models.CharField(choices=[('attending', 'Attending'), ('not_attending', 'Not Attending'), ('maybe', 'Maybe')], max_length=20)),
                (r'dietary_requirements', models.CharField(blank=True, max_length=100)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'outing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='workspace.teamouting')),
            ],
            options={
                r'db_table': 'event_rsvp',
            },
        ),
        migrations.CreateModel(
            name=r'SupplierContract',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'contract_number', models.CharField(max_length=50)),
                (r'terms', models.TextField()),
                (r'value', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'start_date', models.DateField()),
                (r'end_date', models.DateField()),
                (r'auto_renew', models.BooleanField(default=False)),
                (r'contract_cid', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.vendor')),
            ],
            options={
                r'db_table': 'inv_contract',
            },
        ),
        migrations.CreateModel(
            name=r'PurchaseOrder',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'po_number', models.CharField(max_length=50, unique=True)),
                (r'items', models.JSONField(default=list)),
                (r'total', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                (r'expected_date', models.DateField(null=True)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='workspace.vendor')),
            ],
            options={
                r'db_table': 'inv_po',
            },
        ),
        migrations.CreateModel(
            name=r'WarehouseStock',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'quantity', models.PositiveIntegerField(default=0)),
                (r'location', models.CharField(blank=True, max_length=50)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.product')),
                (r'warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.warehouse')),
            ],
            options={
                r'db_table': 'inv_stock',
            },
        ),
        migrations.CreateModel(
            name=r'UserSchedule',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'custom_schedule', models.JSONField(default=dict)),
                (r'effective_from', models.DateField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.workschedule')),
            ],
            options={
                r'db_table': 'event_user_schedule',
            },
        ),
    ]
