# Generated by Django 6.0.1 on 2026-03-19 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0015_aiinsight_aimodel_aiusagelog_assetmaintenance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'Allowance',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'allowance_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=20)),
                (r'amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'percentage', models.FloatField(default=0)),
                (r'is_taxable', models.BooleanField(default=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pay_allowance',
            },
        ),
        migrations.CreateModel(
            name=r'AttendanceRecord',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'date', models.DateField()),
                (r'check_in', models.TimeField(null=True)),
                (r'check_out', models.TimeField(null=True)),
                (r'work_hours', models.FloatField(default=0)),
                (r'status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('wfh', 'WFH'), ('leave', 'Leave')], default='present', max_length=20)),
                (r'notes', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pay_attendance',
            },
        ),
        migrations.CreateModel(
            name=r'AuditFinding',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'audit_type', models.CharField(max_length=50)),
                (r'finding', models.TextField()),
                (r'severity', models.CharField(max_length=20)),
                (r'recommendation', models.TextField()),
                (r'status', models.CharField(default='open', max_length=20)),
                (r'due_date', models.DateField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_finding',
            },
        ),
        migrations.CreateModel(
            name=r'BankAccount',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'bank_name', models.CharField(max_length=100)),
                (r'account_number', models.CharField(max_length=50)),
                (r'account_name', models.CharField(max_length=100)),
                (r'is_primary', models.BooleanField(default=True)),
                (r'is_verified', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pay_bank',
            },
        ),
        migrations.CreateModel(
            name=r'ComplianceRequirement',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'regulation', models.CharField(max_length=100)),
                (r'description', models.TextField()),
                (r'due_date', models.DateField(null=True)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                (r'assigned_to', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_compliance',
            },
        ),
        migrations.CreateModel(
            name=r'ComplianceTraining',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField()),
                (r'required_for', models.JSONField(default=list)),
                (r'due_date', models.DateField(null=True)),
                (r'is_mandatory', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_training',
            },
        ),
        migrations.CreateModel(
            name=r'ConsentRecord',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'consent_type', models.CharField(max_length=50)),
                (r'granted', models.BooleanField(default=True)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'revoked_at', models.DateTimeField(null=True)),
            ],
            options={
                r'db_table': 'legal_consent',
            },
        ),
        migrations.CreateModel(
            name=r'ContractManagement',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'party_name', models.CharField(max_length=100)),
                (r'contract_type', models.CharField(max_length=50)),
                (r'value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'start_date', models.DateField()),
                (r'end_date', models.DateField(null=True)),
                (r'auto_renew', models.BooleanField(default=False)),
                (r'status', models.CharField(default='active', max_length=20)),
                (r'document_cid', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_contract',
            },
        ),
        migrations.CreateModel(
            name=r'DataBreachRecord',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'description', models.TextField()),
                (r'affected_records', models.PositiveIntegerField(default=0)),
                (r'severity', models.CharField(max_length=20)),
                (r'reported_to_authority', models.BooleanField(default=False)),
                (r'reported_at', models.DateTimeField(null=True)),
                (r'resolved_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_breach',
            },
        ),
        migrations.CreateModel(
            name=r'DataPrivacyRecord',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'data_subject', models.CharField(max_length=100)),
                (r'data_type', models.CharField(max_length=50)),
                (r'purpose', models.TextField()),
                (r'legal_basis', models.CharField(max_length=50)),
                (r'retention_period', models.PositiveSmallIntegerField()),
                (r'is_sensitive', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_privacy',
            },
        ),
        migrations.CreateModel(
            name=r'Deduction',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'deduction_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], max_length=20)),
                (r'amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'percentage', models.FloatField(default=0)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pay_deduction',
            },
        ),
        migrations.CreateModel(
            name=r'EmployeeTransfer',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'from_department', models.CharField(max_length=100)),
                (r'to_department', models.CharField(max_length=100)),
                (r'from_position', models.CharField(max_length=100)),
                (r'to_position', models.CharField(max_length=100)),
                (r'effective_date', models.DateField()),
                (r'reason', models.TextField()),
                (r'approved_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pay_transfer',
            },
        ),
        migrations.CreateModel(
            name=r'EthicsComplaint',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'complaint_type', models.CharField(max_length=50)),
                (r'description', models.TextField()),
                (r'is_anonymous', models.BooleanField(default=False)),
                (r'reporter_id', models.CharField(blank=True, max_length=50)),
                (r'status', models.CharField(default='open', max_length=20)),
                (r'assigned_to', models.CharField(blank=True, max_length=50)),
                (r'resolved_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_ethics',
            },
        ),
        migrations.CreateModel(
            name=r'InsiderThreatLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'user_id', models.CharField(max_length=50)),
                (r'activity', models.TextField()),
                (r'risk_score', models.FloatField(default=0)),
                (r'flagged', models.BooleanField(default=False)),
                (r'reviewed', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_insider',
            },
        ),
        migrations.CreateModel(
            name=r'InsurancePlan',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'provider', models.CharField(max_length=100)),
                (r'plan_name', models.CharField(max_length=100)),
                (r'coverage_type', models.CharField(choices=[('health', 'Health'), ('life', 'Life'), ('accident', 'Accident')], max_length=20)),
                (r'premium', models.DecimalField(decimal_places=2, max_digits=10)),
                (r'coverage_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pay_insurance',
            },
        ),
        migrations.CreateModel(
            name=r'LeaveRequest',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'leave_type', models.CharField(choices=[('annual', 'Annual'), ('sick', 'Sick'), ('maternity', 'Maternity'), ('paternity', 'Paternity'), ('emergency', 'Emergency'), ('unpaid', 'Unpaid')], max_length=20)),
                (r'start_date', models.DateField()),
                (r'end_date', models.DateField()),
                (r'days', models.PositiveSmallIntegerField()),
                (r'reason', models.TextField()),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'approved_by', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pay_leave',
            },
        ),
        migrations.CreateModel(
            name=r'LegalDocument',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'doc_type', models.CharField(choices=[('contract', 'Contract'), ('nda', 'NDA'), ('policy', 'Policy'), ('regulation', 'Regulation'), ('license', 'License')], max_length=50)),
                (r'content_cid', models.TextField(blank=True)),
                (r'effective_date', models.DateField()),
                (r'expiry_date', models.DateField(null=True)),
                (r'status', models.CharField(default='active', max_length=20)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_document',
            },
        ),
        migrations.CreateModel(
            name=r'LicenseTracking',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'software_name', models.CharField(max_length=100)),
                (r'license_type', models.CharField(max_length=50)),
                (r'seats', models.PositiveIntegerField(default=1)),
                (r'used_seats', models.PositiveIntegerField(default=0)),
                (r'cost', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'expiry_date', models.DateField(null=True)),
                (r'vendor', models.CharField(max_length=100)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_license',
            },
        ),
        migrations.CreateModel(
            name=r'OvertimeRecord',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'date', models.DateField()),
                (r'hours', models.FloatField()),
                (r'rate_multiplier', models.FloatField(default=1.5)),
                (r'reason', models.TextField(blank=True)),
                (r'approved_by', models.CharField(blank=True, max_length=50)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pay_overtime',
            },
        ),
        migrations.CreateModel(
            name=r'PayrollPeriod',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'start_date', models.DateField()),
                (r'end_date', models.DateField()),
                (r'pay_date', models.DateField()),
                (r'status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pay_period',
            },
        ),
        migrations.CreateModel(
            name=r'PolicyViolation',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'policy', models.CharField(max_length=255)),
                (r'description', models.TextField()),
                (r'severity', models.CharField(max_length=20)),
                (r'action_taken', models.TextField(blank=True)),
                (r'status', models.CharField(default='open', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_violation',
            },
        ),
        migrations.CreateModel(
            name=r'RegulatoryFiling',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'filing_type', models.CharField(max_length=50)),
                (r'regulator', models.CharField(max_length=100)),
                (r'period', models.CharField(max_length=20)),
                (r'due_date', models.DateField()),
                (r'filed_date', models.DateField(null=True)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'document_cid', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_filing',
            },
        ),
        migrations.CreateModel(
            name=r'RiskAssessment',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'risk_type', models.CharField(max_length=50)),
                (r'likelihood', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                (r'impact', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                (r'risk_score', models.PositiveSmallIntegerField()),
                (r'mitigation', models.TextField()),
                (r'status', models.CharField(default='open', max_length=20)),
                (r'assessed_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'legal_risk',
            },
        ),
        migrations.CreateModel(
            name=r'SalaryAdvance',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'amount', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'reason', models.TextField()),
                (r'repayment_months', models.PositiveSmallIntegerField(default=1)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'approved_by', models.CharField(blank=True, max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pay_advance',
            },
        ),
        migrations.CreateModel(
            name=r'TaxBracket',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'min_income', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'max_income', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                (r'tax_rate', models.FloatField()),
                (r'country', models.CharField(default='ID', max_length=2)),
                (r'year', models.PositiveSmallIntegerField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'pay_tax_bracket',
            },
        ),
        migrations.CreateModel(
            name=r'ComplianceTrainingRecord',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'completed_at', models.DateTimeField(null=True)),
                (r'score', models.FloatField(null=True)),
                (r'passed', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.compliancetraining')),
            ],
            options={
                r'db_table': 'legal_training_record',
            },
        ),
        migrations.CreateModel(
            name=r'PayrollRecord',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'basic_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'allowances', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'net_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='workspace.payrollperiod')),
            ],
            options={
                r'db_table': 'pay_record',
            },
        ),
        migrations.CreateModel(
            name=r'PaySlip',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'slip_number', models.CharField(max_length=50, unique=True)),
                (r'generated_at', models.DateTimeField(auto_now_add=True)),
                (r'pdf_cid', models.TextField(blank=True)),
                (r'is_sent', models.BooleanField(default=False)),
                (r'sent_at', models.DateTimeField(null=True)),
                (r'record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.payrollrecord')),
            ],
            options={
                r'db_table': 'pay_slip',
            },
        ),
        migrations.CreateModel(
            name=r'PensionContribution',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'employee_contribution', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'employer_contribution', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'total', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.payrollperiod')),
            ],
            options={
                r'db_table': 'pay_pension',
            },
        ),
        migrations.CreateModel(
            name=r'PerformanceBonus',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'employee_id', models.CharField(max_length=50)),
                (r'amount', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'reason', models.CharField(max_length=255)),
                (r'approved_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.payrollperiod')),
            ],
            options={
                r'db_table': 'pay_bonus',
            },
        ),
    ]
