# Generated by Django 6.0.1 on 2026-03-19 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'workspace', '0016_allowance_attendancerecord_auditfinding_bankaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name=r'APIKey',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'key_hash', models.CharField(max_length=64)),
                (r'prefix', models.CharField(max_length=8)),
                (r'permissions', models.JSONField(default=list)),
                (r'last_used', models.DateTimeField(null=True)),
                (r'expires_at', models.DateTimeField(null=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sys_api_key',
            },
        ),
        migrations.CreateModel(
            name=r'AppVersion',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'version', models.CharField(max_length=20)),
                (r'release_notes', models.TextField()),
                (r'is_forced_update', models.BooleanField(default=False)),
                (r'min_supported_version', models.CharField(max_length=20)),
                (r'released_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sys_version',
            },
        ),
        migrations.CreateModel(
            name=r'GeoLocation',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'ip_address', models.GenericIPAddressField()),
                (r'country', models.CharField(blank=True, max_length=2)),
                (r'city', models.CharField(blank=True, max_length=100)),
                (r'latitude', models.FloatField(null=True)),
                (r'longitude', models.FloatField(null=True)),
                (r'recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sys_geo',
            },
        ),
        migrations.CreateModel(
            name=r'KnowledgeTag',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=50)),
                (r'color', models.CharField(default='#6366f1', max_length=7)),
                (r'usage_count', models.PositiveIntegerField(default=0)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'km_tag',
            },
        ),
        migrations.CreateModel(
            name=r'MaintenanceWindow',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField()),
                (r'start_time', models.DateTimeField()),
                (r'end_time', models.DateTimeField()),
                (r'affected_services', models.JSONField(default=list)),
                (r'status', models.CharField(default='scheduled', max_length=20)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sys_maintenance',
            },
        ),
        migrations.CreateModel(
            name=r'NotificationTemplate',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'name', models.CharField(max_length=100)),
                (r'event_type', models.CharField(max_length=50)),
                (r'title_template', models.CharField(max_length=255)),
                (r'body_template', models.TextField()),
                (r'channels', models.JSONField(default=list)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'notif_template',
            },
        ),
        migrations.CreateModel(
            name=r'ProjectBudgetV2',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'allocated', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                (r'remaining', models.DecimalField(decimal_places=2, max_digits=15)),
                (r'currency', models.CharField(default='IDR', max_length=3)),
                (r'period', models.CharField(max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'proj_budget_v2',
            },
        ),
        migrations.CreateModel(
            name=r'ProjectMilestoneV2',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField(blank=True)),
                (r'due_date', models.DateField()),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                (r'completed_at', models.DateTimeField(null=True)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'proj_milestone_v2',
            },
        ),
        migrations.CreateModel(
            name=r'SystemConfig',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'key', models.CharField(max_length=100)),
                (r'value', models.TextField()),
                (r'description', models.TextField(blank=True)),
                (r'is_secret', models.BooleanField(default=False)),
                (r'updated_by', models.CharField(max_length=50)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                r'db_table': 'sys_config',
            },
        ),
        migrations.CreateModel(
            name=r'SystemHealth',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'service', models.CharField(max_length=100)),
                (r'status', models.CharField(max_length=20)),
                (r'response_time_ms', models.PositiveIntegerField(default=0)),
                (r'cpu_usage', models.FloatField(default=0)),
                (r'memory_usage', models.FloatField(default=0)),
                (r'disk_usage', models.FloatField(default=0)),
                (r'checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sys_health',
            },
        ),
        migrations.CreateModel(
            name=r'TeamMeeting',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'agenda', models.TextField(blank=True)),
                (r'meeting_date', models.DateTimeField()),
                (r'duration_minutes', models.PositiveSmallIntegerField(default=60)),
                (r'location', models.CharField(blank=True, max_length=255)),
                (r'meeting_url', models.URLField(blank=True)),
                (r'minutes', models.TextField(blank=True)),
                (r'created_by', models.CharField(max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'team_meeting',
            },
        ),
        migrations.CreateModel(
            name=r'UserFeedback',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'workspace_id', models.CharField(max_length=50)),
                (r'category', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('improvement', 'Improvement'), ('other', 'Other')], max_length=50)),
                (r'title', models.CharField(max_length=255)),
                (r'description', models.TextField()),
                (r'status', models.CharField(default='open', max_length=20)),
                (r'priority', models.CharField(default='medium', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'sys_feedback',
            },
        ),
        migrations.CreateModel(
            name=r'MeetingAttendee',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'user_id', models.CharField(max_length=50)),
                (r'status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('attended', 'Attended')], default='invited', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='workspace.teammeeting')),
            ],
            options={
                r'db_table': 'team_meeting_attendee',
            },
        ),
        migrations.CreateModel(
            name=r'ActionItem',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'description', models.TextField()),
                (r'assigned_to', models.CharField(max_length=50)),
                (r'due_date', models.DateField(null=True)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='workspace.teammeeting')),
            ],
            options={
                r'db_table': 'team_action',
            },
        ),
    ]
