# Generated by Django 6.0.1 on 2026-03-19 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0016_allowance_attendancerecord_auditfinding_bankaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('key_hash', models.CharField(max_length=64)),
                ('prefix', models.CharField(max_length=8)),
                ('permissions', models.JSONField(default=list)),
                ('last_used', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_api_key',
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('release_notes', models.TextField()),
                ('is_forced_update', models.BooleanField(default=False)),
                ('min_supported_version', models.CharField(max_length=20)),
                ('released_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_version',
            },
        ),
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_geo',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'km_tag',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('affected_services', models.JSONField(default=list)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_maintenance',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('title_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('channels', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notif_template',
            },
        ),
        migrations.CreateModel(
            name='ProjectBudgetV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('allocated', models.DecimalField(decimal_places=2, max_digits=15)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('period', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proj_budget_v2',
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestoneV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proj_milestone_v2',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('updated_by', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sys_config',
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('cpu_usage', models.FloatField(default=0)),
                ('memory_usage', models.FloatField(default=0)),
                ('disk_usage', models.FloatField(default=0)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_health',
            },
        ),
        migrations.CreateModel(
            name='TeamMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('agenda', models.TextField(blank=True)),
                ('meeting_date', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_url', models.URLField(blank=True)),
                ('minutes', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'team_meeting',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('workspace_id', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature Request'), ('improvement', 'Improvement'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='open', max_length=20)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_feedback',
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('attended', 'Attended')], default='invited', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='workspace.teammeeting')),
            ],
            options={
                'db_table': 'team_meeting_attendee',
            },
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('assigned_to', models.CharField(max_length=50)),
                ('due_date', models.DateField(null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='workspace.teammeeting')),
            ],
            options={
                'db_table': 'team_action',
            },
        ),
    ]
