# Generated by Django 6.0.1 on 2026-03-14 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (r'workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'CorporateIDVault',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'company_name_enc', models.TextField()),
                (r'registration_number_enc', models.TextField()),
                (r'registration_country_enc', models.TextField()),
                (r'registration_date_enc', models.TextField()),
                (r'registered_address_enc', models.TextField()),
                (r'tax_number_enc', models.TextField(blank=True)),
                (r'authorised_signatories_enc', models.TextField(help_text='Encrypted JSON array')),
                (r'certificate_of_incorporation_cid', models.CharField(blank=True, max_length=128)),
                (r'memorandum_of_association_cid', models.CharField(blank=True, max_length=128)),
                (r'board_resolution_cid', models.CharField(blank=True, max_length=128)),
                (r'verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('under_review', 'Under Review')], default='pending', max_length=16)),
                (r'verified_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'key_version', models.PositiveSmallIntegerField(default=1)),
                (r'verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_verifications', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_vault', to='workspace.workspace')),
            ],
            options={
                r'verbose_name': 'Corporate ID Vault',
                r'db_table': 'vault_corporate_id',
            },
        ),
        migrations.CreateModel(
            name=r'HardwareKeyRegistry',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'slot', models.PositiveSmallIntegerField(choices=[(1, 'Primary Key'), (2, 'Backup Key')])),
                (r'key_type', models.CharField(choices=[('fido2_yubikey', 'FIDO2 YubiKey'), ('fido2_generic', 'FIDO2 Generic'), ('piv_smart_card', 'PIV Smart Card'), ('pkcs11_token', 'PKCS#11 Token')], max_length=16)),
                (r'label', models.CharField(help_text="User-visible label e.g. 'YubiKey 5C NFC'", max_length=64)),
                (r'credential_id_enc', models.TextField(help_text='Encrypted FIDO2 credential ID')),
                (r'public_key_enc', models.TextField(help_text='Encrypted COSE public key')),
                (r'aaguid', models.CharField(blank=True, help_text='Authenticator AAGUID', max_length=64)),
                (r'vendor_id', models.CharField(blank=True, help_text='USB Vendor ID hex e.g. 0x1050', max_length=8)),
                (r'product_id', models.CharField(blank=True, help_text='USB Product ID hex e.g. 0x0407', max_length=8)),
                (r'serial_number_enc', models.TextField(blank=True, help_text='Encrypted device serial number')),
                (r'sign_count', models.PositiveBigIntegerField(default=0, help_text='FIDO2 signature counter — detects cloning')),
                (r'is_active', models.BooleanField(default=True)),
                (r'registered_at', models.DateTimeField(auto_now_add=True)),
                (r'last_used', models.DateTimeField(blank=True, null=True)),
                (r'deactivated_at', models.DateTimeField(blank=True, null=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'verbose_name': 'Hardware Key Registry',
                r'db_table': 'vault_hardware_key',
            },
        ),
        migrations.CreateModel(
            name=r'AccessSession',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'session_token_hash', models.CharField(db_index=True, max_length=256, unique=True)),
                (r'ip_address', models.GenericIPAddressField()),
                (r'user_agent', models.CharField(blank=True, max_length=512)),
                (r'fido2_challenge_b64', models.TextField(blank=True)),
                (r'fido2_assertion_b64', models.TextField(blank=True)),
                (r'opened_at', models.DateTimeField(auto_now_add=True)),
                (r'expires_at', models.DateTimeField(db_index=True)),
                (r'last_action_at', models.DateTimeField(auto_now=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'closed_reason', models.CharField(blank=True, max_length=64)),
                (r'action_log', models.JSONField(default=list)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_sessions', to=settings.AUTH_USER_MODEL)),
                (r'hardware_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_sessions', to='vault.hardwarekeyregistry')),
            ],
            options={
                r'verbose_name': 'Vault Access Session',
                r'db_table': 'vault_access_session',
            },
        ),
        migrations.CreateModel(
            name=r'UserKYCVault',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'full_name_enc', models.TextField(help_text='Encrypted legal full name')),
                (r'date_of_birth_enc', models.TextField(help_text='Encrypted DOB (ISO format)')),
                (r'nationality_enc', models.TextField(help_text='Encrypted nationality code')),
                (r'id_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driving_license', 'Driving License')], max_length=16)),
                (r'id_number_enc', models.TextField(help_text='Encrypted ID number')),
                (r'id_expiry_enc', models.TextField(help_text='Encrypted expiry date')),
                (r'id_document_ipfs_cid', models.CharField(blank=True, help_text='Encrypted scan stored on IPFS', max_length=128)),
                (r'address_enc', models.TextField(blank=True, help_text='Encrypted residential address')),
                (r'tax_id_enc', models.TextField(blank=True, help_text='Encrypted tax identification number')),
                (r'kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=16)),
                (r'verified_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'key_version', models.PositiveSmallIntegerField(default=1, help_text='AES key rotation version')),
                (r'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_vault', to=settings.AUTH_USER_MODEL)),
                (r'verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'verbose_name': 'KYC Vault Record',
                r'db_table': 'vault_kyc',
            },
        ),
        migrations.CreateModel(
            name=r'EncryptedBlobStore',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'blob_type', models.CharField(choices=[('document', 'Document'), ('certificate', 'Certificate'), ('evidence', 'Audit Evidence'), ('secure_note', 'Secure Note'), ('key_backup', 'Key Backup')], max_length=16)),
                (r'label', models.CharField(max_length=128)),
                (r'description_enc', models.TextField(blank=True, help_text='Encrypted description')),
                (r'ipfs_cid', models.CharField(db_index=True, help_text='IPFS CID of encrypted blob', max_length=128)),
                (r'content_type', models.CharField(max_length=128)),
                (r'size_bytes', models.PositiveBigIntegerField()),
                (r'blob_key_enc', models.TextField(help_text="Blob AES key, encrypted with owner's Kyber public key")),
                (r'blob_nonce_b64', models.CharField(max_length=32)),
                (r'blob_tag_b64', models.CharField(max_length=32)),
                (r'checksum_sha256', models.CharField(max_length=64)),
                (r'min_clearance', models.PositiveSmallIntegerField(default=3)),
                (r'ttl_seconds', models.PositiveIntegerField(blank=True, null=True)),
                (r'destroy_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                (r'is_destroyed', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'key_version', models.PositiveSmallIntegerField(default=1)),
                (r'owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_blobs', to=settings.AUTH_USER_MODEL)),
                (r'shared_with', models.ManyToManyField(blank=True, related_name='shared_vault_blobs', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_blobs', to='workspace.workspace')),
            ],
            options={
                r'verbose_name': 'Encrypted Blob Store',
                r'db_table': 'vault_blob_store',
                r'indexes': [models.Index(fields=['owner', 'blob_type'], name='vault_blob__owner_i_4da7d7_idx'), models.Index(fields=['destroy_at'], name='vault_blob__destroy_672b17_idx')],
            },
        ),
        migrations.AddIndex(
            model_name=r'hardwarekeyregistry',
            index=models.Index(fields=[r'user', 'is_active'], name='vault_hardw_user_id_cf3d90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name=r'hardwarekeyregistry',
            unique_together={(r'user', 'slot')},
        ),
        migrations.AddIndex(
            model_name=r'accesssession',
            index=models.Index(fields=[r'user', 'is_active'], name='vault_acces_user_id_79d618_idx'),
        ),
        migrations.AddIndex(
            model_name=r'accesssession',
            index=models.Index(fields=[r'expires_at'], name='vault_acces_expires_3d74fd_idx'),
        ),
        migrations.AddIndex(
            model_name=r'userkycvault',
            index=models.Index(fields=[r'kyc_status'], name='vault_kyc_kyc_sta_69b735_idx'),
        ),
        migrations.AddIndex(
            model_name=r'userkycvault',
            index=models.Index(fields=[r'verified_at'], name='vault_kyc_verifie_58a71b_idx'),
        ),
    ]
