# Generated by Django 6.0.1 on 2026-03-14 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'vault', '0001_initial'),
        (r'workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'MasterKeyVersion',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'version', models.PositiveIntegerField(unique=True)),
                (r'key_fingerprint', models.CharField(max_length=64)),
                (r'algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                (r'is_active', models.BooleanField(default=False)),
                (r'activated_at', models.DateTimeField(blank=True, null=True)),
                (r'retired_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                r'db_table': 'vault_master_key_version',
            },
        ),
        migrations.CreateModel(
            name=r'KeyAccessLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'key_type', models.CharField(max_length=50)),
                (r'action', models.CharField(max_length=50)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'success', models.BooleanField(default=True)),
                (r'accessed_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_key_access_log',
            },
        ),
        migrations.CreateModel(
            name=r'KeyDerivationParams',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'salt_b64', models.TextField()),
                (r'info_b64', models.TextField()),
                (r'algorithm', models.CharField(default='HKDF-SHA512', max_length=50)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'rotated_at', models.DateTimeField(auto_now=True)),
                (r'channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_params', to='workspace.channel')),
            ],
            options={
                r'db_table': 'vault_key_derivation_params',
            },
        ),
        migrations.CreateModel(
            name=r'KeyEscrow',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'key_type', models.CharField(max_length=50)),
                (r'encrypted_key_b64', models.TextField()),
                (r'escrow_nonce_b64', models.TextField()),
                (r'escrow_tag_b64', models.TextField()),
                (r'custodian', models.CharField(max_length=100)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_escrows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_key_escrow',
            },
        ),
        migrations.CreateModel(
            name=r'KeyRotationLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'key_type', models.CharField(max_length=50)),
                (r'old_key_fingerprint', models.CharField(max_length=64)),
                (r'new_key_fingerprint', models.CharField(max_length=64)),
                (r'reason', models.CharField(default='scheduled', max_length=100)),
                (r'rotated_at', models.DateTimeField(auto_now_add=True)),
                (r'rotated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_performed', to=settings.AUTH_USER_MODEL)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_rotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_key_rotation_log',
            },
        ),
    ]
