# Generated by Django 6.0.1 on 2026-03-14 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'vault', '0002_masterkeyversion_keyaccesslog_keyderivationparams_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'SWIFTMessage',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'message_type', models.CharField(max_length=10)),
                (r'sender_bic', models.CharField(max_length=11)),
                (r'receiver_bic', models.CharField(max_length=11)),
                (r'amount', models.DecimalField(decimal_places=2, max_digits=20)),
                (r'currency', models.CharField(max_length=3)),
                (r'reference', models.CharField(max_length=50, unique=True)),
                (r'encrypted_payload_b64', models.TextField()),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                r'db_table': 'vault_swift_message',
            },
        ),
        migrations.CreateModel(
            name=r'DocumentSignature',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'document_hash', models.CharField(max_length=64)),
                (r'document_name', models.CharField(max_length=255)),
                (r'document_cid', models.TextField(blank=True)),
                (r'signature_b64', models.TextField()),
                (r'signature_algorithm', models.CharField(default='Dilithium3', max_length=50)),
                (r'public_key_fingerprint', models.CharField(max_length=64)),
                (r'is_valid', models.BooleanField(default=True)),
                (r'revoked_at', models.DateTimeField(blank=True, null=True)),
                (r'signed_at', models.DateTimeField(auto_now_add=True)),
                (r'signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_document_signature',
            },
        ),
        migrations.CreateModel(
            name=r'MultiPartySignature',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'document_hash', models.CharField(max_length=64)),
                (r'document_name', models.CharField(max_length=255)),
                (r'is_complete', models.BooleanField(default=False)),
                (r'completed_at', models.DateTimeField(blank=True, null=True)),
                (r'deadline', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_signatures', models.ManyToManyField(related_name='multi_party', to='vault.documentsignature')),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'required_signers', models.ManyToManyField(related_name='pending_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_multi_party_signature',
            },
        ),
    ]
