# Generated by Django 6.0.1 on 2026-03-14 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'vault', '0003_swiftmessage_documentsignature_multipartysignature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'HSMKeySlot',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'slot_id', models.PositiveIntegerField(unique=True)),
                (r'label', models.CharField(max_length=100)),
                (r'key_type', models.CharField(choices=[('rsa_4096', 'RSA-4096'), ('ecdsa_p384', 'ECDSA-P384'), ('aes_256', 'AES-256'), ('kyber_1024', 'Kyber-1024'), ('ml_dsa_65', 'Dilithium3')], max_length=50)),
                (r'key_fingerprint', models.CharField(blank=True, max_length=64)),
                (r'is_active', models.BooleanField(default=True)),
                (r'usage_count', models.BigIntegerField(default=0)),
                (r'last_used', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                r'db_table': 'vault_hsm_key_slot',
            },
        ),
        migrations.CreateModel(
            name=r'CertificateAuthority',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'certificate_pem', models.TextField()),
                (r'public_key_b64', models.TextField()),
                (r'is_root', models.BooleanField(default=False)),
                (r'is_active', models.BooleanField(default=True)),
                (r'valid_from', models.DateTimeField()),
                (r'valid_until', models.DateTimeField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.certificateauthority')),
            ],
            options={
                r'db_table': 'vault_certificate_authority',
            },
        ),
        migrations.CreateModel(
            name=r'IssuedCertificate',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'serial_number', models.CharField(max_length=50, unique=True)),
                (r'subject', models.CharField(max_length=255)),
                (r'certificate_pem', models.TextField()),
                (r'public_key_b64', models.TextField()),
                (r'is_revoked', models.BooleanField(default=False)),
                (r'revoked_at', models.DateTimeField(blank=True, null=True)),
                (r'revoke_reason', models.CharField(blank=True, max_length=100)),
                (r'valid_from', models.DateTimeField()),
                (r'valid_until', models.DateTimeField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certs', to='vault.certificateauthority')),
                (r'user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_issued_certificate',
            },
        ),
        migrations.CreateModel(
            name=r'SecureEnvelope',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'subject_encrypted_b64', models.TextField()),
                (r'content_cid', models.TextField()),
                (r'kyber_ciphertext_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'dilithium_signature_b64', models.TextField(blank=True)),
                (r'is_opened', models.BooleanField(default=False)),
                (r'opened_at', models.DateTimeField(blank=True, null=True)),
                (r'destroy_after_read', models.BooleanField(default=False)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_envelopes', to=settings.AUTH_USER_MODEL)),
                (r'sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_envelopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_secure_envelope',
            },
        ),
        migrations.CreateModel(
            name=r'TokenVault',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'token', models.CharField(max_length=64, unique=True)),
                (r'data_type', models.CharField(choices=[('card_number', 'Card Number'), ('account_number', 'Account Number'), ('swift_bic', 'SWIFT BIC'), ('iban', 'IBAN'), ('ssn', 'SSN/NIK')], max_length=50)),
                (r'encrypted_value_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'usage_count', models.PositiveIntegerField(default=0)),
                (r'last_used', models.DateTimeField(blank=True, null=True)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_token',
            },
        ),
    ]
