# Generated by Django 6.0.1 on 2026-03-14 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'vault', '0004_hsmkeyslot_certificateauthority_issuedcertificate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'DisasterRecoveryPlan',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'plan_name', models.CharField(max_length=100)),
                (r'plan_type', models.CharField(choices=[('bcp', 'Business Continuity Plan'), ('drp', 'Disaster Recovery Plan'), ('irp', 'Incident Response Plan'), ('crisis', 'Crisis Management')], max_length=50)),
                (r'rto_minutes', models.PositiveIntegerField(default=60)),
                (r'rpo_minutes', models.PositiveIntegerField(default=30)),
                (r'steps', models.JSONField(default=list)),
                (r'contacts', models.JSONField(default=list)),
                (r'last_tested', models.DateTimeField(blank=True, null=True)),
                (r'next_test', models.DateTimeField(blank=True, null=True)),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_disaster_recovery',
            },
        ),
        migrations.CreateModel(
            name=r'SecureNotepad',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'title_encrypted_b64', models.TextField()),
                (r'content_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'category', models.CharField(choices=[('credentials', 'Credentials'), ('meeting_notes', 'Meeting Notes'), ('deal_notes', 'Deal Notes'), ('personal', 'Personal'), ('compliance', 'Compliance')], default='personal', max_length=50)),
                (r'is_pinned', models.BooleanField(default=False)),
                (r'destroy_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_secure_notepad',
            },
        ),
        migrations.CreateModel(
            name=r'SecureSharing',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'resource_type', models.CharField(max_length=50)),
                (r'resource_id', models.CharField(max_length=50)),
                (r'access_token', models.CharField(max_length=64, unique=True)),
                (r'max_access_count', models.PositiveIntegerField(default=1)),
                (r'access_count', models.PositiveIntegerField(default=0)),
                (r'requires_mfa', models.BooleanField(default=True)),
                (r'expires_at', models.DateTimeField()),
                (r'is_active', models.BooleanField(default=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_items', to=settings.AUTH_USER_MODEL)),
                (r'shared_with', models.ManyToManyField(related_name='received_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_secure_sharing',
            },
        ),
        migrations.CreateModel(
            name=r'VaultAccessPolicy',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'resource_type', models.CharField(choices=[('kyc', 'KYC Records'), ('blob', 'Blob Store'), ('signature', 'Digital Signatures'), ('certificate', 'Certificates'), ('token', 'Token Vault'), ('notepad', 'Secure Notepad')], max_length=50)),
                (r'allowed_roles', models.JSONField(default=list)),
                (r'min_clearance', models.PositiveSmallIntegerField(default=1)),
                (r'requires_mfa', models.BooleanField(default=True)),
                (r'requires_hardware_key', models.BooleanField(default=False)),
                (r'time_restrictions', models.JSONField(default=dict)),
                (r'ip_restrictions', models.JSONField(default=list)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_access_policy',
            },
        ),
    ]
