# Generated by Django 6.0.1 on 2026-03-14 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'vault', '0005_disasterrecoveryplan_securenotepad_securesharing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'CBDCTransaction',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'amount', models.DecimalField(decimal_places=8, max_digits=30)),
                (r'currency', models.CharField(default='e-IDR', max_length=10)),
                (r'transaction_hash', models.CharField(max_length=64, unique=True)),
                (r'block_number', models.BigIntegerField(null=True)),
                (r'smart_contract_address', models.CharField(blank=True, max_length=100)),
                (r'status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'confirmed_at', models.DateTimeField(blank=True, null=True)),
                (r'receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbdc_received', to=settings.AUTH_USER_MODEL)),
                (r'sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbdc_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_cbdc_transaction',
            },
        ),
        migrations.CreateModel(
            name=r'DigitalAssetCustody',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'asset_type', models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('cbdc', 'CBDC'), ('stablecoin', 'Stablecoin'), ('tokenized_asset', 'Tokenized Asset')], max_length=50)),
                (r'wallet_address_encrypted_b64', models.TextField()),
                (r'private_key_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'balance', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                (r'is_cold_storage', models.BooleanField(default=True)),
                (r'custodian', models.CharField(blank=True, max_length=100)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_digital_asset',
            },
        ),
        migrations.CreateModel(
            name=r'SmartContractAudit',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'contract_address', models.CharField(max_length=100)),
                (r'contract_name', models.CharField(max_length=100)),
                (r'audit_type', models.CharField(choices=[('security', 'Security Audit'), ('compliance', 'Compliance Audit'), ('functional', 'Functional Audit')], max_length=50)),
                (r'vulnerabilities_found', models.PositiveIntegerField(default=0)),
                (r'critical_issues', models.PositiveIntegerField(default=0)),
                (r'audit_report_cid', models.TextField(blank=True)),
                (r'passed', models.BooleanField(default=False)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'audited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_smart_contract_audit',
            },
        ),
    ]
