# Generated by Django 6.0.1 on 2026-03-15 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'vault', '0007_postquantummigration_quantumkeydistribution'),
        (r'workspace', '0008_documenttemplate_githubevent_meetingnotes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'APIKeyVault',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'service', models.CharField(max_length=100)),
                (r'key_name', models.CharField(max_length=100)),
                (r'api_key_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development')], default='development', max_length=20)),
                (r'expires_at', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys_vault', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_api_key',
            },
        ),
        migrations.CreateModel(
            name=r'PasswordVault',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'service_name', models.CharField(max_length=100)),
                (r'username_encrypted_b64', models.TextField()),
                (r'password_encrypted_b64', models.TextField()),
                (r'url', models.URLField(blank=True)),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'notes_encrypted_b64', models.TextField(blank=True)),
                (r'category', models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('social', 'Social'), ('finance', 'Finance'), ('other', 'Other')], default='work', max_length=50)),
                (r'last_used', models.DateTimeField(blank=True, null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'updated_at', models.DateTimeField(auto_now=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passwords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_password',
            },
        ),
        migrations.CreateModel(
            name=r'SSHKey',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'public_key', models.TextField()),
                (r'private_key_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'key_type', models.CharField(choices=[('rsa', 'RSA'), ('ed25519', 'Ed25519'), ('ecdsa', 'ECDSA')], default='ed25519', max_length=20)),
                (r'passphrase_hint', models.CharField(blank=True, max_length=100)),
                (r'servers', models.JSONField(default=list)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_ssh_key',
            },
        ),
        migrations.CreateModel(
            name=r'EnvironmentSecret',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'key_name', models.CharField(max_length=100)),
                (r'value_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development')], max_length=20)),
                (r'description', models.TextField(blank=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_secrets', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'vault_env_secret',
                r'unique_together': {('workspace', 'key_name', 'environment')},
            },
        ),
    ]
