# Generated by Django 6.0.1 on 2026-03-15 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (r'vault', '0008_apikeyvault_passwordvault_sshkey_environmentsecret'),
        (r'workspace', '0009_budgettracker_budgetexpense_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name=r'SharedSecret',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'name', models.CharField(max_length=100)),
                (r'value_encrypted_b64', models.TextField()),
                (r'nonce_b64', models.TextField()),
                (r'auth_tag_b64', models.TextField()),
                (r'expires_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'shared_with', models.ManyToManyField(blank=True, related_name='shared_secrets_access', to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_secrets', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'vault_shared_secret',
            },
        ),
        migrations.CreateModel(
            name=r'TrustedDevice',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'device_name', models.CharField(max_length=100)),
                (r'device_token_hash', models.CharField(max_length=64, unique=True)),
                (r'last_used', models.DateTimeField(auto_now=True)),
                (r'expires_at', models.DateTimeField()),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_trusted_device',
            },
        ),
        migrations.CreateModel(
            name=r'TwoFactorBackupCode',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'code_hash', models.CharField(max_length=64)),
                (r'is_used', models.BooleanField(default=False)),
                (r'used_at', models.DateTimeField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_2fa_backup_code',
            },
        ),
        migrations.CreateModel(
            name=r'VaultAuditLog',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'action', models.CharField(max_length=50)),
                (r'resource_type', models.CharField(max_length=50)),
                (r'resource_id', models.CharField(max_length=50)),
                (r'ip_address', models.GenericIPAddressField(null=True)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                r'db_table': 'vault_audit',
            },
        ),
        migrations.CreateModel(
            name=r'WorkspaceBackup',
            fields=[
                (r'id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (r'backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('messages', 'Messages Only'), ('files', 'Files Only')], max_length=20)),
                (r'size_bytes', models.BigIntegerField(default=0)),
                (r'storage_cid', models.TextField(blank=True)),
                (r'status', models.CharField(default='pending', max_length=20)),
                (r'created_at', models.DateTimeField(auto_now_add=True)),
                (r'completed_at', models.DateTimeField(null=True)),
                (r'created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (r'workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='workspace.workspace')),
            ],
            options={
                r'db_table': 'vault_workspace_backup',
            },
        ),
    ]
